### ISSUE TITLE
mouse.screen is nil after using arandr in Xephyr

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#1003]
Output of `awesome --version`:

git-master

**How to reproduce the issue:**

    Xephyr :1 -screen 1280x800

2) Open `arandr` and resize the screen to `1024x768`
3) apply
4) enjoy errors due to screen being nil when it is assumed mouse.screen is always valid.

**Actual result:**

capi.mouse.screen is nil

**Can be reproduced using the default config:**

yes

**Expected result:**

capi.screen.mouse return the first screen object

**Comment by psychon** [comment]
"Fixed" by the following patch:
```diff
diff --git a/objects/screen.c b/objects/screen.c
index 99e3a78..dd087d1 100644
--- a/objects/screen.c
+++ b/objects/screen.c
@@ -377,7 +377,7 @@ screen_scan_randr_crtcs(lua_State *L, screen_array_t *screens)
 
             p_delete(&output_info_r);
 
-            if (A_STREQ(name, "default"))
+            if (false && A_STREQ(name, "default"))
             {
                 /* non RandR 1.2+ X driver don't return any usable multihead
                  * data. I'm looking at you, nvidia binary blob!
```
This means there are two issues here:

- [ ] We do not correctly disable RandR when we decide to ignore it and a following RandR event corrupts our state
- [ ] Just because an output with name "default" exists does not mean that no "real" RandR is available (and I thought copying GTK's behavior meant that everything was fine...)
