### ISSUE TITLE
System tray disappears

### ISSUE THREAD

**Issue by poisonby** [awesomeWM/awesome#1022]
**Output of `awesome --version`:**

    awesome v3.5.9 (Mighty Ravendark)
     • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
     • Compiled against Lua 5.3.2 (running with Lua 5.3)
     • D-Bus support: ✔

**How to reproduce the issue:**

Don't do anything for a few seconds and the system tray will disappear. The system tray will reappear once you focus another window.

**Actual result:**

![awesomewm][tray1]

**Expected result:**

![awesomewm][tray2]

[tray1]: https://ptpb.pw/T4dn
[tray2]: https://ptpb.pw/IxLf

**Comment by psychon** [comment]
Could you run `xwininfo -frame -root` and click e.g. on your textclock? This will print information (mainly important here: position) about the wibar and all of its children. The easiest thing to do might be: Run this once while the icons are visible and again when they disappear. Check if the output between the two runs is different.
If no difference occurs, then the icons are still placed correctly, but for some reason they are overdrawn.

Example output:
```

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x800010 (has no name)

  Root window id: 0xd6 (the root window) (has no name)
  Parent window id: 0xd6 (the root window) (has no name)
     1 child:
     0x800003 (has no name): ()  20x20+1763+0  +3683+0
        1 child:
        0xc00172 "Updates Available": ("update-notifier.py" "Update-notifier.py")  20x20+0+0  +3683+0
           1 child:
           0xc00173 (has no name): ()  1x1+-1+-1  +3682+-1
```
Here I have a tray icon telling me that updates are available (even though they are not...). It has window id 0xc00172.

The next thing that I would like to do is to run `xev -id 0xc00172` (replace the ID with one of the window ids of your tray icons) while the tray icon is visible and wait for the tray icon to disappear. Does `xev` produce any output when the tray icon disappears?


And now that I look at your screenshots again:
"Don't do anything for a few seconds and the system tray will disappear."
Does this perhaps happen when your textclock is updated?
The default config has `mytextclock = awful.widget.textclock()`. If you still use the textclock like this (no arguments): Do the tray icons disappear when the textclock changes from e.g. `18:54` to `18:55`?
If you provide an argument with a timeout... could you somehow else check if this is due to the textclock? For example, change the first argument into `"%a %b %d, %H:%M:%S"` so that you have a seconds display and can see when the textclock updates.

**Comment by poisonby** [comment]
@psychon Hey, thanks for the help! I can't actually reproduce it now after I turned off the computer for the night. I'll come back should I be able to reproduce it again.
