### ISSUE TITLE
Spawning a client with callback properties on screen 1 will tag it on screen 2

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1028]
The following code, run through `awesome-client` on screen 1 (internal monitor) will spawn rxvt-unicode on that screen, but it gets tagged with the selected tag on screen 2 (external display):

    require("awful").spawn('urxvt', {})

The following works as a workaround, but should probably be the default behavior:

    require("awful").spawn('urxvt', {floating=true, screen=require("awful").screen.focused})

For programs launched without properties `c:tags()` seems to be empty when `rules.execute`

I've attached to signals for debugging:

    client.connect_signal("tagged", tag_screen_debug)
    client.connect_signal("property::screen", tag_screen_debug)

This is the output:
```
Client got tagged:
c.screen: 2, awful.tag.getscreen(t): 2, c window/client(urxvt): 0x418ff378, c.name urxvt, t tag: 0x40bcc3b0
stack traceback:
        /home/daniel/.config/awesome/rc.lua:2231: in function </home/daniel/.config/awesome/rc.lua:2227>
        [C]: in function 'tags'
        /usr/share/awesome/lib/awful/client.lua:461: in function 'to_selected_tags'
        /usr/share/awesome/lib/awful/ewmh.lua:138: in function </usr/share/awesome/lib/awful/ewmh.lua:133>
        [C]: in function 'emit_signal'
        /usr/share/awesome/lib/awful/rules.lua:432: in function 'execute'
        /usr/share/awesome/lib/awful/rules.lua:497: in function </usr/share/awesome/lib/awful/rules.lua:496>
        [C]: in function 'emit_signal'
        /usr/share/awesome/lib/awful/spawn.lua:76: in function </usr/share/awesome/lib/awful/spawn.lua:73>
Client got tagged:
c.screen: 1, awful.tag.getscreen(t): nil, c window/client(urxvt): 0x418ff378, c.name urxvt, t screen: 0x402e1698
stack traceback:
        /home/daniel/.config/awesome/rc.lua:2231: in function </home/daniel/.config/awesome/rc.lua:2227>
        [C]: in function '__newindex'
        /usr/share/awesome/lib/awful/tag.lua:1284: in function </usr/share/awesome/lib/awful/tag.lua:1273>
```

Apparently the tag gets set to screen 2 from the beginning, via `to_selected_tags`.

Will have to investigate further.

**Comment by psychon** [comment]
Sigh.

So:
- The C code assigns screens based on the client's position. Urxvt starts (apparently) at (0,0) and so is assigned to screen 1.
- `awful.rules` does its thing. Since nothing says otherwise, it assigns the tags based on screen 1.
- `awful.tag` runs. It is connected to the `manage` signal and does (basically) `c.screen = awful.screen.focused()`. Urxvt is now assigned to the other screen, but tags are left as they were.

This was apparently introduced(?) with the combination of commits 90fde1393f697ca0d7201e385293a5ac4778d136 and 254e50d88c5f58cb8b736dbb4681d020ddb88919 + 1c6463822e590508d40862a47ecd86a9a0b8c776 + 055ad392ee5dbfed0ea38b70f9c9855c884b0eb6 + 055ad392ee5dbfed0ea38b70f9c9855c884b0eb6. I don't really know what was going on there, but it looks weird.

If we move the `c:connect_signal("property::screen", ..` in `tag.lua` up to the beginning of the callback function, then this specific bug would go away. However, I bet that this would now override changes done by `awful.rules`.

So... how about doing something like before commit 90fde1393f697ca0d7201e385293a5ac4778d136? `awful.rules` disconnects the signal from `tag.lua` and calls that function directly where convenient for it. Alternatively, how about wrapping the application of rules into a `delayed_call()`?

**Comment by blueyed** [comment]
Thanks for the great investigation once again!

> Alternatively, how about wrapping the application of rules into a `delayed_call()`?

Seems to be the least intrusive / easiest?

**Comment by Elv13** [comment]
That would break even more things downstream. Anything that uses a `"manage"` callback would get the "wrong" values.

**Comment by psychon** [comment]
The current situation is "never ever use the manage signal, because you cannot be sure that awful.rules is done". That's not really nice either (AFAIK we do not guarantee anything about the order in which signal callbacks are done; heck, we do not even say what happens if you connect to a signal from within the same signal callback).

So... how can something like awful.rules work properly?

**Comment by Elv13** [comment]
^ Here is an implementation of @psychon suggestion. It will need some testing even before being turned into a PR.

**Comment by Bew78LesellB** [comment]
This made me think about something I wanted to do a while ago : 
Event handlers with priority..

A simple implementation would be to use string to reprensent the priority
Example with 3 priority level `"low"`, `"high"` & `"normal"` (this is the default) : 

```lua
client.connect_signal("manage", rules.apply, "low") -- will be executed last

-- add later some other handlers :
client.connect_signal("manage", my_manage)
client.connect_signal("manage", do_something_urgent, "high")

client.emit_signal("manage", myclient)
-- order of execution :
-- do_something_urgent
-- my_manage
-- rules.apply
```

what do you think ?

PS: maybe this should go in a new issue ?

**Comment by Elv13** [comment]
> Event handlers with priority.

I think it just move the problem down the line. As soon as the is 4 hooks on the same signal, then there will be a race again. Given how sensitive manage is, it _will_ cause side effects. I prefer the #1056 (and  #824, and a bunch of other PRs) "solution". Those PR simply add more signals emitted at a predictable point in the "bigger picture". Instead of moving the problem elsewhere, it cuts it into smaller problems with less side effects (if any). So now there is `request::activate` and `request::tag` signals instead of "manage does everything".
