### ISSUE TITLE
Can't screen.focus() from empty tag

### ISSUE THREAD

**Issue by Architektor** [awesomeWM/awesome#1029]
awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔

**Reproduce:**

1. Setup multiple screens with xrandr one by the other
2. Bind F1, F2 to `awful.screen.focus()`
3. Go to empty tag without clients.
4. Try switch between screens.

**Actual result:**

So it doesn't switch, you have to move to populated tag before that.

**Expected result:**

Really annoys sometimes. Is there a workaround?

**Comment by Elv13** [comment]
The workaround is to add this in your `rc.lua`

```lua
function awful.screen.focus()
    return client.focus and client.focus.screen or mouse.screen
end
```

This issue has been fixed in the git version

**Comment by Architektor** [comment]
@Elv13 Sorry, but your module doesn't solve it for me. I tried it, and the `collision.select_screen(1)` don't throw focus to adjacent screen, only switching number-circles and arrows around mouse apper for me, but focus remains same.

**Comment by jtcwang** [comment]
I'm still getting this issue in AwesomeWM 4 - can someone confirm?

**Comment by psychon** [comment]
@jtcwang Can you describe what exactly you are doing? From the original comment here:
- I have multiple screens.
- I add keybindings, somehow
- I go(?) to a tag without any clients
- The above keybinding does not work

From this, all I can say right now is that the new keybinding should be in `globalkeys` and not in `clientkeys`, since it is not client-specific (and this would explain why it does not work without a focused client (but the issue does not say that there is no focused client!)). Besides that: I feel like I do not understand / something is missing.

**Comment by jtcwang** [comment]
You're right. It was set within client keys. I switched them to global keys and it's working correctly now. Thanks for your help!
