### ISSUE TITLE
Travis: codecov coverage went down by 10%

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#1049]
See https://codecov.io/gh/awesomeWM/awesome/commits

Many files are missing from (for example) `lib/awful` and coverage for other files went for ~90% to ~60% (like placement.lua, and this one really has 90%, for all the **** time it took me to get there). Coverall seems unaffected.

I didn't investigate yet.

**Comment by psychon** [comment]
Looks like the functional tests went missing. I cannot find any file which has any kind of coverage from functional tests. I don't have much time to investigate either.

**Comment by blueyed** [comment]
The "do_codecov functionaltests" part seems to run.  Search for "functionaltest" in e.g. https://s3.amazonaws.com/archive.travis-ci.org/jobs/153899494/log.txt.

**Comment by blueyed** [comment]
Some example from #1088:
Searching for "&flags" in the build output (https://s3.amazonaws.com/archive.travis-ci.org/jobs/159271723/log.txt) shows that there are three uploads.
In https://codecov.io/gh/awesomeWM/awesome/tree/45e8c6083c047f0278ca8cf4cb8f22450a2bcc67 however I cannot see the flags (as documented in https://codecov.readme.io/docs/flags#section-usage).

While I can imagine that we end up in the wrong directory through https://github.com/awesomeWM/awesome/blob/0014b275a80bf35ab5646e7d5b840a675cbd8962/.travis.yml#L159-L160, I've contacted the codecov support already, since I would assume that flags should show up anyway, and there's maybe (another) issue with that.

**Comment by blueyed** [comment]
This seems to be caused by e723d18 (#1011), by looking at https://codecov.io/gh/awesomeWM/awesome/commits?page=3.

**Comment by psychon** [comment]
Thanks for looking into that! So I guess this means that more than just awesome was using `$LUA_PATH`....

**Comment by stevepeak** [comment]
Hey @blueyed which flag is missing? I'm still [seeing 3 uploads](https://codecov.io/gh/awesomeWM/awesome/commit/78300f24d5025630ed5f655db64d1e5c7f123d4e/builds) and [three flags here](https://codecov.io/gh/awesomeWM/awesome/src/78300f24d5025630ed5f655db64d1e5c7f123d4e/tests/examples/text/template.lua)

Thanks!

**Comment by blueyed** [comment]
@stevepeak 
Thanks for looking into it!  I was expecting to see the flags also in the dir view apparently.
Do you have an idea why setting `LUA_PATH` (https://github.com/awesomeWM/awesome/pull/1105/commits/2f7b9543000c82719b3f8b4c2e393b4ccc91de59) fixes this?

**Comment by blueyed** [comment]
The `LUA_PATH="$(lua -e 'print(package.path)');lib/?.lua;lib/?/init.lua"` seems to be the crucial part (https://github.com/awesomeWM/awesome/pull/1105/commits/a5e364e53cfefd27ac97f0d8cb15d4e082090d1f).

But why?
Should not be related to `luacov`, since that is also used by coverall?!
Maybe `luacov-coveralls` handles this?

**Comment by psychon** [comment]
Grepping through busted, ldoc, luacheck, luacov, luassert, pl, say, socket and term (all the libs I have installed through luarocks), only ldoc seems to use `package.path` in some way. I didn't find anything in `luacov-coveralls` either.

> Hey @blueyed which flag is missing? I'm still [seeing 3 uploads](https://codecov.io/gh/awesomeWM/awesome/commit/78300f24d5025630ed5f655db64d1e5c7f123d4e/builds) and [three flags here](https://codecov.io/gh/awesomeWM/awesome/src/78300f24d5025630ed5f655db64d1e5c7f123d4e/tests/examples/text/template.lua)

Hm, looking at these three uploads, they all seem to produce different file names. For example, `awful.util` ends up being loaded from:
* `lib//awful/util.lua`
* `/home/travis/build/awesomeWM/awesome/lib/awful/util.lua`
* `/home/travis/build/awesomeWM/awesome/.build-testing-gce-dc6b0395-7678-4eae-ae6a-40186859f93b-x86_64-linux-gnu-4.8/lib/awful/util.lua`.

Looking at an ["older, working example"](https://codecov.io/gh/awesomeWM/awesome/commit/aa04557b54daab6afa1e2f3ca7c0185cd8e51636/builds), we have:
* `lib/awful/util.lua`
* `/home/travis/build/awesomeWM/awesome/lib/awful/util.lua`
* `/home/travis/build/awesomeWM/awesome/.build-testing-gce-dc5599c9-c332-4095-863c-cf3a07be322f-x86_64-linux-gnu-4.8/lib/awful/util.lua`

The obvious difference is `lib//awful/util.lua` vs `lib/awful/util.lua`. No idea why/how `PACKAGE_PATH` can cause this, but @stevepeak could this explain why some of the coverage info "disappears" (= is not mapped to the corresponding file in our git repo)
