### ISSUE TITLE
Awesome fails to place windows in correct screen on non-rectangular multi-monitor setups

### ISSUE THREAD

**Issue by globalundo** [awesomeWM/awesome#1069]
Output of `awesome --version`:

awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 20 2016 10:57:28 for x86_64 by gcc version 4.8.4 (buildd@lgw01-02)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

**How to reproduce the issue:**

1) Configure 3 or more screens via **(a|x)randr** in non-rectangular shape:
![2016-09-05-144057_485x369_scrot](https://cloud.githubusercontent.com/assets/184496/18248148/eb7b92fc-7376-11e6-838f-5271905290b0.png)
2) Restart awesomewm
3) Move focus to any screen but #1. Spawn a new client (e.g. terminal window).

**Actual result:**

New client will be always spawned on screen #1

**Expected result:**

New client will be always spawned on mouse.screen 

**Notes**

The only reference to this issue I found on awesome bug tracker system dated Jan 2013: [FS#1083 - Awesome fails to place windows in correct screen on non-rectangular multi-monitor setups.](https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1083). No issue is present if the screens are aligned properly.

![2016-09-05-144151_485x369_scrot](https://cloud.githubusercontent.com/assets/184496/18248299/9c01ade6-7377-11e6-8ba0-b0ba5ec9643a.png)

**Comment by psychon** [comment]
I think the key point here is if coordinate (0,0) falls inside of any screen or not. Put differently: I *think* (but did not actually check) that this will work correctly if you put VGA1 to the right side of the other two outputs (and I also do not remember why this would make a difference... but somehow I feel like there was something like this somewhere). Could you check this theory?

For the actual issue: @Elv13 will ask you to test if this bug is still present in the git/master version of awesome, because a lot of things changed since the 3.5 branch was branched. Can you do this?

**Comment by Elv13** [comment]
This is related to https://github.com/awesomeWM/awesome/issues/154

**Comment by globalundo** [comment]
Can confirm solved: issue is not present when VGA1 is rightmost to other outputs:

![2016-09-06-092630_486x367_scrot](https://cloud.githubusercontent.com/assets/184496/18265093/382fee52-7414-11e6-98dd-fefdb1da0eb0.png)

Also the issue is gone in git-master. Thanks for the help, you're awesome <3
