### ISSUE TITLE
Port awful.placement.no_offscreen to the new awful.placement conventions

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#1092]
Those functions are older than the others and don't fully comply to conventions that make some composition scenarios work.

Under_mouse and no_offscreen also need to be unit tested.

**Comment by psychon** [comment]
(Perhaps it would also be nice to add some comments (to `wrap_client`? Dunno, I don't get all the magic) that explain what the "conventions that make some composition scenarios work" actually are, for whoever wants to add the next placement functions.)

(Also, is the pretend-mode really necessary? I tried to look into this issue and it seems that due to pretend, `under_mouse` doesn't actually do anything and then `no_offscreen` works based on the old position of the client. Without pretend-mode, things could be easier. (And there is so much more (undocumented?) modes in there that seem to make stuff more complicated...))

**Comment by Elv13** [comment]
> Also, is the pretend-mode really necessary?

Yes, changing the resolution during the composition mess up the pre-conditions and the end result changes. Try to disable it with a semi-complex composition, the output will change and wont be as predictable. It has side effects like this, but I don't think there is a way to remove it without breaking more use cases.

**Comment by blueyed** [comment]
Is this the reason why `properties = { placement = (awful.placement.under_mouse + awful.placement.no_offscreen) }` does not work?

I've tried to use one of them as `callback`, but it seems they cannot be combined currently?!

**Comment by blueyed** [comment]
It should work according to the FAQ (https://github.com/awesomeWM/awesome/blob/8f6e80f5c6870cb47305689e31854d795664f03e/docs/90-FAQ.md#how-to-make-windows-spawn-under-the-mouse-cursor), but does not:
```
    -- Open CopyQ window at/under mouse.
    { rule = {
      instance = 'copyq',
      type = 'normal',
      name = ' - CopyQ',
      }, properties = {
        placement = awful.placement.under_mouse+awful.placement.no_overlap+awful.placement.no_offscreen }},
```

**Comment by psychon** [comment]
Removed the milestone since it is easily visible that it is meaningless here

**Comment by sigprof** [comment]
After `awful.placement.no_overlap` was ported to the new conventions, the default configuration (which contains `placement = awful.placement.no_overlap+awful.placement.no_offscreen`) became broken — all new windows are placed at the top left corner of the workspace area. The change from https://github.com/actionless/awesome/commit/7b1b7d415af7b7d67171958f9d3a04e9ef34dc1b fixes the problem.

**Comment by Elv13** [comment]
adding as a blocker for v4.3

**Comment by sigprof** [comment]
After #2033 the problem with `awful.placement.no_overlap+awful.placement.no_offscreen` was still there, so I investigated further and found a difference between the old commit (https://github.com/actionless/awesome/commit/7b1b7d415af7b7d67171958f9d3a04e9ef34dc1b) which worked, and the newer commit which got merged (https://github.com/awesomeWM/awesome/pull/2033/commits/fec8d6aa8fe257f2d1fbab9a908b1e3a9a98bed3) but did not work.

The working commit contained:

    local geometry = geometry_common(c, args)

The newer but broken commit contained:

     local geometry = area_common(c) 

The important difference is that `geometry_common(c, args)` uses `args.override_geometry` if it is present, and the `compose` function puts the result of the previous placement function into `args.override_geometry` and expects the next placement function to use it instead of the real geometry. When using just `area_common(c)`, the result of the previous placement function is lost.

The problem with the first approach is that `geometry_common()` is called twice; in my PR #2386 I used this instead:

    local geometry = area_common(c, nil, false, args)

With this change the default configuration (`placement = awful.placement.no_overlap+awful.placement.no_offscreen`) works for me — windows fill the whole workspace area instead of being placed just at the top left corner.
