### ISSUE TITLE
Allow testing for valid object in LUA ("invalid object"); obj:isvalid()

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#110]
After a client has become invalid, e.g. after `c:kill()`, testing for it should be false.

Currently a test for it is true, but then calling a method on it generates error ("invalid object").

So, whenever `luaA_checkudata` ([source ref](https://github.com/blueyed/awesome/blob/client-set-name/common/luaclass.c#L81)) would generate that error, testing the object itself should return false/nil already.

**Comment by psychon** [comment]
You meaning testing like in `if foo then`, right? Well, lua can't let you do that, because a userdata is a userdata. Only `false` and `nil` ever can be, well, false.

If you want something like this, I'd rather propose a `obj:isvalid()` (suggestions for the name welcome) to be added to `common/luaobjects.h` (so that it is available on all objects, not only clients).

**Comment by blueyed** [comment]
> You meaning testing like in `if foo then`, right?

Yes.

> Only false and nil ever can be, well, false.

Can we change a client object to `nil` after it has been destroyed?

**Comment by psychon** [comment]
A client object is a userdata and always will be (and can't be changed into e.g. `nil`). As I said, all that we can do is adding something like `obj:isvalid()`. Only `nil` and `false` ever evaluate to false.

**Comment by blueyed** [comment]
I see.  `obj:isvalid()` seems to be good then.
