### ISSUE TITLE
progressbar: takes all space, removing tasklist, clock etc

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1140]
> -- By default, this widget will take all the available size. To prevent this,
> -- a `wibox.container.constraint` widget or the `forced_width`/`forced_height`
> -- properties have to be used.

(https://github.com/awesomeWM/awesome/blob/26d3c5eb1aa3a9f5930dcae609580649f62289ad/lib/wibox/widget/progressbar.lua#L12-L14)

I think there should be a default limit in some regard, and especially it should not push out the tasklist, textclock etc, when used without a width in the wibar.

/cc @Elv13

**Comment by Elv13** [comment]
Well, this is what `forced_width` and the `constraint` containers are for. For the sake of separations of concerns, the widgets should not implement their own width/height/margins/padding/spacing logic unless it affect the widget output (like the arcchart and a few other). Now that there is no abusive full redraw, using these containers is now mostly "free". So I decided to remove some bloat from the progressbar. I know some people wont be happy about it. I still think it was the right call. No?

**Comment by blueyed** [comment]
In general, yes.
But why does it have to push out (remove) other widgets?
I only see the logo (with the menu) the taskbar, the systray and 3 other custom widgets.

![2016-10-04-224642_1919x33_scrot](https://cloud.githubusercontent.com/assets/9766/19091835/7ea35f00-8a84-11e6-83e2-3e84ab794496.png)

**Comment by Elv13** [comment]
> But why does it have to push out (remove) other widgets?

This is a limitation of the widget system. GTK/Qt have much "size policies" to avoid it. But we only have a `:fit()` function and no control over the order it is executed. The `align` layout have a `strategy` property to mitigate this, but the issue is much deeper and mostly unfixable with the current API. The closest we could have a is an optional `:get_fit_policy()` and execute the "expand" `:ft()` functions only once the "minimum", "fixed" and "preferred"/`nil` ones are executed like Qt does. Then split the remaining space with the "maximum" ones. This is required in both horizontal and vertical dimensions, so the current "fit" with 2 return values will have unfixable issues.

**Comment by blueyed** [comment]
> The closest we could have a is an optional :get_fit_policy() and execute the "expand" :fit() functions only once the "minimum", "fixed" and "preferred"/nil ones are executed like Qt does.

Sounds reasonable.
I am not sure if I understand it correctly, but would that be possible - or isn't it?

What about just sharing all the available space equally?

**Comment by Elv13** [comment]
It isn't possible because it requires fit to be called twice. So it would require an extra optional `fit_horizontal()` and `fit_vertical()` for the widgets that implement  `get_fit_policy`. Then `check_widget` would need to be more complex. It goes on and on. It is why I never complained about this. It is a limitation. I ran into it a looooong time ago and just live with it to avoid unnecessary complexity and to burnout @psychon on complex corner cases ;). Having a whole widget framework is crazy enough already :). Can our framework define everything? No. Should it? I don't think so. We don't have the resources or userbase to re-implement EFL. We have a partial solution to this issue and it's called the `align` layout `strategy`.

**Comment by Elv13** [comment]
Can this be closed?

**Comment by Elv13** [comment]
I assume it can
