### ISSUE TITLE
awesome.spawn does not handle errors well

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1281]
> a,b = require("awful").spawn("FOO=1 bar"); return a
> boolean true

On stderr:

> 2016-12-21 01:32:30 …/ib/awful/spawn.lua:107: W: Failed to execute child process "FOO=1" (No such file or directory)

I think it should not return a trueish value!?

```
% awesome-client
awesome# return awesome.spawn("FOO=1 bar")
   string "FOO=1 bar"
```

**Comment by psychon** [comment]
Sigh. The error handling in `awesome.spawn` is just broken. It returns its last argument on error. -.-
Breakage comes from 5e6a8932078e3352c972dfb811669f3b96cb3978 and no one noticed it in the last year.

The docs for `awesome.spawn` say that it just returns a string on errors. Do we really want that, or wouldn't `false, "error message"` make more sense?
Anyway, patch could be (this also gets rid of the warnings, I do not like them anyway):
```diff
diff --git a/spawn.c b/spawn.c
index f65c68d..9dd626b 100644
--- a/spawn.c
+++ b/spawn.c
@@ -414,11 +414,11 @@ luaA_spawn(lua_State *L)
     {
         g_strfreev(argv);
         if (error) {
-            luaA_warn(L, "spawn: parse error: %s", error->message);
+            lua_pushfstring(L, "parse error: %s", error->message);
             g_error_free(error);
         }
         else
-            luaA_warn(L, "spawn: There is nothing to execute");
+            lua_pushliteral(L, "There is nothing to execute");
         return 1;
     }
 
@@ -443,7 +443,7 @@ luaA_spawn(lua_State *L)
     g_strfreev(argv);
     if(!retval)
     {
-        luaA_warn(L, "%s", error->message);
+        lua_pushstring(L, error->message);
         g_error_free(error);
         if(context)
             sn_launcher_context_complete(context);
```
Due to my usual not-having-much-time: Anyone is free to pick up the above patch and submit a pull request, as long as we also get a test for this.

**Comment by blueyed** [comment]
> The docs for `awesome.spawn` say that it just returns a string on errors. Do we really want that, or wouldn't `false, "error message"` make more sense?

Yes, it would make more sense, but is 
Should `luaA_spawn` be changed then, too?
(https://github.com/awesomeWM/awesome/blob/0444bf30cf57e6f222ad1dc6d82e5342037f1b93/spawn.c#L372-L377)
Also `spawn.with_line_callback` would need to be changed then (https://github.com/awesomeWM/awesome/blob/0444bf30cf57e6f222ad1dc6d82e5342037f1b93/lib/awful/spawn.lua#L154-L157).

btw: the "Error: no command to execute" (mentioned in https://github.com/awesomeWM/awesome/issues/1282) is coming from there, too (https://github.com/awesomeWM/awesome/blob/0444bf30cf57e6f222ad1dc6d82e5342037f1b93/lib/awful/spawn.lua#L116).

I suggest using the above patch first/already.  I'll adopt it and add some tests.
