### ISSUE TITLE
Support Multi-pointer X

### ISSUE THREAD

**Issue by Oreolek** [awesomeWM/awesome#1319]
Right now the [Multi-Pointer X](https://wiki.archlinux.org/index.php/Multi-pointer_X) is very, very buggy. Using it opens all sorts of issues and redraw bugs. Maybe it's worth looking into?

#### How to test it
You'll need a second mouse. Follow the instructions on the Arch wiki.

**Comment by psychon** [comment]
Redraw bugs? Huh? That's surprising, since input does not have much to do with redrawing.

Besides that: Does any WM properly support multiple master input devices? Last time I was thinking loudly about this, @Elv13 stopped me, because it would lead to quite an ABI break on the Lua side (e.g. `client.focus` needs to be split into something for every single master input pair) for little gain (how many people use MPX? What's the use case?).

**Comment by Elv13** [comment]
> @Elv13 stopped me,

I did not *stop* you ;). I just said not to break the `mouse.screen` and `client.focus` paradigms because it's relevant to 99.95% of the userbase and breaking them would increase the code complexity by an unacceptable quantity, let alone seriously piss off (and lose) many users with large configs for the sake of 0.05% of users. Those arguments still stands.

However, if you want to invest this much time and keep the current API as an abstraction layer, feel free ;).

**Comment by actionless** [comment]
i accidentally discovered less crazy usecase for multi-cursor X - touch screens

i think the solution could be defining focus layers and assigning them to inputs

for example if i have 2 screens, 2 touchscreens and 1 trackball, i could assign main focus focus layer to trackball, and 2 extra focuslayers on each touch screen

(and assuming that first/main focus layer - is default one, so all existing code with .focus() api should work)
