### ISSUE TITLE
Error when opening hotkeys dialog on small screen sizes

### ISSUE THREAD

**Issue by samis** [awesomeWM/awesome#1328]
Output of `awesome --version`:
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0

**How to reproduce the issue:**

1. Run `Xephyr :1 &` in a shell
2. Run `DISPLAY=:1 awesome` in a shell (using the default rc.lua)
3. Open the menu and click the 'hotkeys' button

Edit by psychon: I did not understand step 3, but can reproduce with: Ctrl-Shirt (so that Xephyr grabs input) and then Mod4+S

**Actual result:**

The following error is produced:
```
2016-12-29 22:51:57 W: awesome: luaA_dofunction:77: error while running function!
stack traceback:
        ...usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:317: in function 'create_wibox'
        ...usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:412: in function <...usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:381>
        (tail call): ?
        /usr/share/awesome/lib/awful/menu.lua:311: in function 'exec'
        /usr/share/awesome/lib/awful/menu.lua:441: in function 'press'
        /usr/share/awesome/lib/awful/button.lua:46: in function </usr/share/awesome/lib/awful/button.lua:46>
        [C]: in function 'emit_signal'
        /usr/share/awesome/lib/wibox/widget/base.lua:381: in function </usr/share/awesome/lib/wibox/widget/base.lua:348>
        (tail call): ?
        /usr/share/awesome/lib/gears/object.lua:116: in function 'emit_signal'
        /usr/share/awesome/lib/wibox/drawable.lua:415: in function </usr/share/awesome/lib/wibox/drawable.lua:410>
error: ...usr/share/awesome/lib/awful/hotkeys_popup/widget.lua:317: attempt to get length of field 'widgets' (a nil value)
```

**Expected result:**
A dialog pops up showing all the set hotkeys

**Comment by psychon** [comment]
The code in `lib/awful/hotkeys_popup/widget.lua` around line 317 is just broken.

When not enough space is available (`if item.max_width > available_width_px then`), the code tries to add "PgDn - Next Page". However, it does so via `columns.widgets[#columns.widgets]['widget']:add`, i.e. it accesses internal implementation details of the widget directly. I always try to tell people not to do that and this shows why: The implementation details changed and now `.widgets` is just `nil` and causes an error.

CC @actionless just because he is the authors of most of the commits touching this file.
