### ISSUE TITLE
Can't spawn program in another screen

### ISSUE THREAD

**Issue by martinber** [awesomeWM/awesome#1482]
Output of `awesome --version`:

~~~~~
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.8.0
~~~~~

**How to reproduce the issue:**

I have two monitors. I've created some tags with unique names. I want to start a program in a specific tag, the problem it's that I can't spawn on a tag located on an unfocused tag. I'm not a native English speaker so sorry if I make some mistakes, also I don't know if what I'm trying to do it's possible.

Starting from a default rc.lua, I've commented out this line (around line 183):
~~~~~
awful.tag({ "1", "2", "3", "4", "5", "6", "7", "8", "9" }, s, awful.layout.layouts[1])
~~~~~

And at the end of the file, I've created my own tags and tried to spawn apps on my tags using `awful.spawn()`. AFAIK by reading the docs I can set the tag and screen from there

~~~~~
-- Set names for tags
mytags = {}
tags_names = {}
tags_layouts = {}

layout_tile = awful.layout.layouts[2]

tags_names[1] = {'editor',
                'terminal',
                'files1',
                'view2',
                'etc2',
                'etc3'}

tags_names[2] = {'www',
                'config',
                'view1',
                'files2',
                'etc1'}

for s = 1, screen.count() do
    mytags[s] = awful.tag(tags_names[s], s, layout_tile)
end

-- Returns the screen and tag object from a tag name
-- I can't use awful.tag.find_by_name() because I need to previously know his screen
function get_screen_and_tag(name)
    for s in screen do
        for i, tag in ipairs(s.tags) do
            if name == tag.name then
                return s, tag
            end
        end
    end
end

-- Spawns my program in a tag
function spawn_in_tag(program, tag_name)
    s, t = get_screen_and_tag(tag_name)
    awful.spawn(program, {
        tag = t,
        screen = s,
    })
end

spawn_in_tag("mate-terminal", "view1") -- in screen 2
spawn_in_tag("mate-terminal", "files2") -- in screen 2
spawn_in_tag("mate-terminal", "etc1") -- in screen 2
spawn_in_tag("mate-terminal", "view2") -- in screen 1
spawn_in_tag("mate-terminal", "etc2") -- in screen 1
spawn_in_tag("mate-terminal", "etc3") -- in screen 1
~~~~~

**Actual result:**

The terminals that should spawn on the first screen are in the right places. But the terminals that should spawn in the second screen are in the first tag of my first screen.

Looks like I can't spawn programs in the screen currently unfocused. If I focus the second screen (moving the mouse) and restart Awesome, the opposite happens, programs sent to the second screen are right, but programs sent to the first screen end on the first tag of the second screen.

**Expected result:**

Three terminals should appear in tags on the first screen and three more terminals should appear in tags on the second screen

**Something else**
Maybe I should try the workaround posted in this issue: https://github.com/awesomeWM/awesome/issues/1211  
That looks too hacky to me

**Comment by Elv13** [comment]
This indeed looks like a bug. It's strange because we have tests for this, but not that surprising given how complex that code is.

Can you debug this? I think I can see why it happens with the default config but not to me (this totally works here with Tyrannical)

     client.disconnect_signal("request::tag", awful.ewmh.tag)

Does this help? (it is **bad** and will cause more problems that it solves). If that helps, then it will require another bad if in the rules code... The patch will make psychon angry... But well, there *is* a race condition.

**Comment by martinber** [comment]
I pasted that in my rc.lua just before spawning, and it works! You are right about that this line cause problems, I had problems on the layout of the windows and some things, so I removed it. 

Also this issue might be related https://github.com/awesomeWM/awesome/issues/988

I'm not a developer but I'd love to help in everything a can!

**Comment by Elv13** [comment]
> I'm not a developer but I'd love to help in everything a can!

Yet it looks like you wrote quite some code to get this far already ;)

As far as fixing this. It, again, wont be easy. As #988, #1236, #1267, #1091 and other have already shown, this is not simple. There is many way to select the tag and the screen that in many cases they end up with a mismatch. #1267 is the closest to your issue.

The problem here is this (in ewmh.lua)

    if not t and #get_valid_tags(c, c.screen) > 0 then return end

This function check if any of the currently selected tag match the screen. The `tag` property (before the ewmh code shown above) does:

    if c.screen ~= value.screen then
        c.screen = value.screen
        props.screen = value.screen -- In case another rule query it
    end

So something *in between* those 2 set of lines being executed mess the screen.

Do you have custom rules? Can you post them?

**Comment by martinber** [comment]
> > I'm not a developer but I'd love to help in everything a can!
>
> Yet it looks like you wrote quite some code to get this far already ;)

I wanted to say that I never worked in some project, I always wanted to help somewhere but I need to learn more

Anyway, I don't have custom rules. I started from a default rc.lua and did the changes listed above. 

```
awful.rules.rules = {
    -- All clients will match this rule.
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = awful.client.focus.filter,
                     raise = true,
                     keys = clientkeys,
                     buttons = clientbuttons,
                     screen = awful.screen.preferred,
                     placement = awful.placement.no_overlap+awful.placement.no_offscreen
     }
    },

    -- Floating clients.
    { rule_any = {
        instance = {
          "DTA",  -- Firefox addon DownThemAll.
          "copyq",  -- Includes session name in class.
        },
        class = {
          "Arandr",
          "Gpick",
          "Kruler",
          "MessageWin",  -- kalarm.
          "Sxiv",
          "Wpa_gui",
          "pinentry",
          "veromix",
          "xtightvncviewer"},

        name = {
          "Event Tester",  -- xev.
        },
        role = {
          "AlarmWindow",  -- Thunderbird's calendar.
          "pop-up",       -- e.g. Google Chrome's (detached) Developer Tools.
        }
      }, properties = { floating = true }},

    -- Add titlebars to normal clients and dialogs
    { rule_any = {type = { "normal", "dialog" }
      }, properties = { titlebars_enabled = true }
    },
}
-- }}}
```

**Comment by Elv13** [comment]
Sigh... Right. That's one my Tyrannical module fixed a long time ago, but I never backported that monkey-patch into Awesome (3 years ago). I just totally forgot about that patch, again. This is a know issue caught by Tyrannical tests and fixed there. I event told in https://github.com/mindeunix/clientdb/issues/1 that I would upstream it and never did.

Simplified: The rule is executed twice. The first time it's right and the second wrong.

Technical: Given rules can come from 2 sources, it needs a chain of responsibility between each rules providers to avoid shooting itself in the foot. The last elements of the chain "overwrite" the previous ones. `awful.rules` itself does it, but only when there is multiple matching rules. It doesn't support external providers. For example, if you have `awful.rules`, ClientDB, Tyrannical and `awful.spawn` providers, it should do

1. Match `awful.rules`
2. Create the final rule table
    2.1. Squash the awful.rules into the table (lowest priority, but executed first)
    2.2. Squash Tyrannical rules into the table (also quite low priority)
    2.3. Squash ClientDB rules into the table ("saved state", high priority)
    2.4. Squash `awful.spawn` rules into the table (override whatever was there, this one should win)
3. Call `awful.rules.execute`
    3.1 Execute high priority rules
    3.2 Look for a tag and screen if nothing was found
    3.3 Execute the normal rules
    3.4 Execute the delayed rules
4. Return

Right now, due to the bug, it does:

1. Get `awful.spawn` rules
    1.1 Execute high priority rules
    1.2 Look for a tag and screen if nothing was found
    1.3 Execute the normal rules
    1.4 Execute the delayed rules
1. Match `awful.rules`
    2.1 Execute high priority rules
    2.2 Look for a tag and screen if nothing was found
    2.3 Execute the normal rules
    2.4 Execute the delayed rules
4. Return

I will try to cleanup the patch and give it a proper API. The workaround for now is to use Tyrannical, has it monkey-patch the fix on top of `awful.rules`.

**Comment by Elv13** [comment]
Prototype https://gist.github.com/Elv13/d450c1269f229b288861d26f9ff0c14d

**Comment by psychon** [comment]
```
  dependencies = type(dependencies) == "string"
        and {dependencies} or dependencies or {}
```
Since that API is new, can't we keep it simple? :-(
```
if max_index < min_index then return nil end
```
No one will check for or handle that. At least print a warning. Also, due to KISS I'd like to just drop this priorities stuff...
```
 return max_index
```
I fail to see why the caller needs the index.

I did not read further than this.

I would just do an (unordered? I know you will make it ordered...) list of callbacks which can modify the table of "computed properties" after awful is done applying things internally.
