### ISSUE TITLE
descriptions of keybindings

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#151]
What do you think about passing hotkey description to `awful.key()` as an optional argument (and when describing all of them in default rc.lua)?

It will be useful for 3rd party widgets (i seen at least 4 different ones) which shows list of current hotkeys. And at the same time it still will be readable from config (sort of replacement to commenting each hotkey).

Later it can be agreed on design for such widget and it can be implemented as part of awesome's lua libraries.

I think to have such cheatsheet will be very useful.

**Comment by blueyed** [comment]
:+1:

**Comment by blueyed** [comment]
`awful.key` might get changed to accept an optional table of arguments, where `desc` would be part of (to make it more flexible for future changes).  But then, adding `desc` as a new arg by itself would make it easier to use by default (no table/key needed).

**Comment by actionless** [comment]
mb it can be like:

```
function key.new(mod, _key, press, release, ...)
    allkeys[mod][_key]['keydata'] = ...
```
```
    desc = foo.keydata[1]
```

**Comment by Elv13** [comment]
Just as a side note, I also would like to have categories. I made a module for that, but after implementing it, the syntax isn't as nice looking as I thought it would be:

https://github.com/Elv13/awesome-configs/blob/master/shortcuts.lua#L136

The reason for this is to implement this as the welcome page:
!(Unity)[http://upload.wikimedia.org/wikipedia/commons/9/93/Ubuntu_Unity_Keyboard_shortcuts_-_En.png]

Here is how it look:
!(Awesome)[http://i.imgur.com/aMDMeii.png]

Many complains about tiled WM is that they are hard to learn (meh...) because they lack WYSIWYG hints. This kind of welcome screen help with that. Actionless edition with the visual keyboard layout is very useful too, maybe an hybrid of both could be used. The `Shorter` module used here have many issues, so I don't think it is the way forward versus upgrading awful.key. However, maybe we could break things a little more to make this use case better covered. What do you think?

**Comment by actionless** [comment]
so the solution with `...` should help with categories, ie it can be like
```
awful.key({modkey}, 'a', do_action, 'Do some action', 'Misc stuff')


category = foo.keydata[2]
```

**Comment by Elv13** [comment]
maybe more like 

```
awful.key({modkey}, 'a', do_action, {desc='Do some action', category='Misc stuff'})
```
?

**Comment by actionless** [comment]
it's more straight-forward, i am agree.
but a tricky thing to remember here what it will be repeated about 100 times in a row, so imho specifiying keys every time will be to verbose

**Comment by Elv13** [comment]
At the same time, if we want to add another parameter at some point, the function will have 6 arguments, this start to be problematic. It also allow shortcuts helper implementations like yours and mine to have different metadata fields (color, icons?)

**Comment by actionless** [comment]
yup, if starting to think about more additional parameters using table keys will make sense and will be less complicated, but i still would like to make it like:
```lua
function key.new(mod, _key, press, release, keydata)
    if type(release) == 'table' then
       keydata = release
       release = nil
    end  
```

**Comment by actionless** [comment]
is example in a message below seems ok to you, guys?

also there is a second topic to discuss is how to store bindings?
i was thinking about storing it like:
```
{
  "joined_modifiers_repr": {
    "key": { keydata },
    "key2": { keydata },
  }, "Control_Mod4": {
    "r" :{ keydata },
    "q" :{ keydata }
  }
}
```

what do you think about it?


after some agreement on both cases i will start implementing it

**Comment by actionless** [comment]
also just noticed GNOME plans on that topic:
https://wiki.gnome.org/Design/OS/HelpOverlay

**Comment by actionless** [comment]
@blueyed @Elv13 any comments on code examples above?

**Comment by actionless** [comment]
bump

**Comment by blueyed** [comment]
@actionless 
I think your code examples are fine.

**Comment by Elv13** [comment]
Yes, I like the storage example. `awful.util.table.join` "format" is unusable.

**Comment by psychon** [comment]
If I understand correctly, the merge of #421 fixed this
