### ISSUE TITLE
awful.util.pread?

### ISSUE THREAD

**Issue by twentytwoo** [awesomeWM/awesome#1542]
Did this get removed in the awesome 4.0? Previously I was using it likee `awful.util.pread("ls -t | head -n1") ` but now that doesn't work? I looked on the new wiki and found `awful.spawn` but that doesn't seem to be the same, any ideas?

**Comment by Elv13** [comment]
Yes, it got removed. It prints a warning in Awesome log. It was removed because it is a blocking call and caused many users to have massive slowdown they then blamed on Awesome. There is a new `easy_async` function that replaces it. The name was changed because their signature is different. This is all documented in:

https://awesomewm.org/apidoc/libraries/awful.spawn.html

Also, if you need a shell, Awesome 4.1 will have `easy_async_with_shell` (thanks to @copycat-killer). Right now use `{"bash", -"c", "ls -t | head -n1"}`

I will close this, feel free to ask more questions.
