### ISSUE TITLE
Widgets displayed conditionally disappear after adding/removing screens

### ISSUE THREAD

**Issue by doctaweeks** [awesomeWM/awesome#1565]
In addition to the documentation issue confirmed in #1562 there also appears to be a bug when using conditionals in the declarative method. When adding or removing screens the widgets disappear from every screen until awesome is restarted.

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.0

**Comment by psychon** [comment]
Well, the `s.index == 1` is not really that much of a good idea, since screen index might change when you add/remove screens. When you remove a screen and another screen becomes screen 1, the code here does not run again and so the widget is not visible on the "new screen 1".

What is it that you really want to achieve? For example "Only ever show the widget on VGA1" or "if VGA1 is disconnected, show the widget on the first screen. Otherwise, show it on VGA1" (the latter would require some way to remove the widget from elsewhere when VGA1 is added).

**Comment by doctaweeks** [comment]
I'll clarify the situation: This is a laptop. I have widgets set to display only on screen one so when I have it docked with multiple monitors the widgets only show up on the primary display instead of all of them.

From my perspective, this is a regression or at least a significant change in behavior that wasn't documented. If my understanding is correct, it's a side-effect of the change to no longer restart on xrandr changes (since previously the config was just processed over again with a new screen 1).

I recommend, to support the old behavior, that there is an automatic pass over the widgets during a refresh that corrects placement if it was conditional.
