### ISSUE TITLE
doc: Porting tips: add link to old (3.5) rc.lua and tell people to diff from that

### ISSUE THREAD

**Issue by asmunder** [awesomeWM/awesome#1576]
The 3.5 -> 4.0 porting tips at https://awesomewm.org/doc/api/documentation/17-porting-tips.md.html, as written now, could be a bit more helpful. Specifically, after the first paragraph, which goes 

"""
The **best advice is to start from the default rc.lua and backport any changes** you might have added to your rc.lua. This avoids most of the possible errors due to missing important changes.
"""

I would like to add another paragraph that instructs the user how to do so (the main point is having links to the new and old defaults). As an example:

"""
To do this, you can download the default rc.lua for 3.5.9 from <insert_permalink>, and then compare your existing rc.lua with the 3.5.9 default using your diff tool of choice. Write down the changes, then apply these to the 4.0 default rc.lua, which you can find at /etc/xdg/awesome/rc.lua after the upgrade, or at <this_permalink> if you have not yet performed the upgrade.
"""

Before the "I warned you, but here is the difficult way" text that is most of the page today, I would then like to see included a list of changes that are needed for the new rc.lua to go back to the 3.5.9 defaults. In my case, that meant digging up how to disable the titlebars (now on by default, I don't like them personally). Probably there are a few more such "frequent requests".

**Comment by psychon** [comment]
One small problem that I see: Thanks to the magic done to add documentation to the default config, the actual default config as it is installed is not in Git anymore. Thus we cannot link to it.
The 3.5.9 default config can easily be linked to, I think.

**Comment by Elv13** [comment]
>One small problem that I see: Thanks to the magic done to add documentation to the default config,
> the actual default config as it is installed is not in Git anymore. Thus we cannot link to it.
>The 3.5.9 default config can easily be linked to, I think.

That's not really new/true. The v3.5 `awesomerc.lua.in` have `beautiful.init("@AWESOME_THEMES_PATH@/default/theme.lua")`. The current `rc.lua` is usable as-is. It has some commented lines with `-- @section_name`, but none of them prevents it from being used. It could be argued they even make it more readable. Is it *exactly* the same as the one installed in `/etc/xdg`? No. But the lines it adds don't really hurt anyone and/or confuse diff utilities. 

I can also instruct `cmake` to place a copy of the "real" (sanitized) file in the doc. `ldoc` has a special mode for "scripts" (`@script` instead of `@module`). We currently don't use it, but it would be nice to expose rc.lua that way. We could also add the default theme to the "script" section. Thanks to the recent removal or all hardcoded paths, it's now possible. There's also an option to rename the "Scripts". We could use "Sample files".

**Comment by blueyed** [comment]
Sounds good to me, @Elv13.

**Comment by asmunder** [comment]
@Elv13 thanks for fixing the rc.lua :) Will you also update the porting tips Markdown, per suggestions in first post here?

**Comment by Elv13** [comment]
Could you submit a pull request for it? I don't have much time right now

**Comment by asmunder** [comment]
Sure thing, I will submit a PR.

**Comment by Elv13** [comment]
thanks

**Comment by psychon** [comment]
> Sure thing, I will submit a PR.

@asmunder Ping?

**Comment by asmunder** [comment]
Sorry about the lag, this fell off my stack. I'm not sure I can properly test the markdown (relative link in particular) myself, but I think it should be OK.
