### ISSUE TITLE
Indexing issue

### ISSUE THREAD

**Issue by latach** [awesomeWM/awesome#1695]
Output of `awesome --version`:

awesome v4.1-ga9f1aa3 (Technologic)
(Please see screenshot attached)
I'm running ubuntu 16.04.02 LTS on virtualbox (Host is ubuntu 16.10).

**How to reproduce the issue:**
1. Build it from source (I built it yesterday).
2. sudo make install
3. restart ubuntu
4. select awesome from the login WM selector
5. Press *MOD4 + r* (or do anything really)

**Actual result:**
I get the error as in the screenshot attached. (/etc/xdg/awesome/rc.lua:268: attempt to index field '?' (a nil value)

**Expected result:**
The expected output from perssing *MOD4 + r*
![aaa](https://cloud.githubusercontent.com/assets/21196400/24586010/a5aa7ce4-178f-11e7-9faf-b6422911a3cd.png)

**Comment by latach** [comment]
I have tried checking out version 4.1, and I still have the same issue.

![screenshot from 2017-04-02 12-44-20](https://cloud.githubusercontent.com/assets/21196400/24586849/22d302b0-17a2-11e7-80d4-727ba0e01c76.png)

**Comment by psychon** [comment]
Sigh. No idea how to properly fix this, but here is what is going on:

I guess your `make install` installed the default config to `/usr/local/etc/` (don't ask me why, but CMake does it). I also guess that you had awesome 3.5 installed before you installed 4.0. So your `/etc/xdg/awesome/rc.lua` is the default config for awesome 3.5, but you are running awesome 4.0.

The fix is simple: Don't run an old config on awesome 4.
(I'm only 90% sure of the above; your line 268 doesn't fit anything that I can find, but at least for the 3.5 default config it's just seven lines off of something that could cause such an error; all other awesome default configs are further away).

**Comment by latach** [comment]
That's correct I had 3.5 installed before this one.
Wow, I just removed the file * /etc/xdg/awesome/rc.lua * and this fixed the issue, thank you.

It's strange, why is the file still being read?

**Comment by psychon** [comment]
The [search order](https://github.com/awesomeWM/awesome/blob/a9f1aa3237f6ae41235a417894870ddf3162402b/luaa.c#L929-L960) is:
* The path given to awesome on the commandline with the `-c` argument
* All `awesome/rc.lua`-entries that are in the [standard locations](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) (this includes `~/.config`, but also `/etc/xdg`)
* The location where the default config was installed to

We do not have much influence on the XDG search order. It's defined by the standard, after all. Everything here is working as intended, I guess...

**Comment by latach** [comment]
Thank you psychon. I'll close the issue now.
