### ISSUE TITLE
textual layout icons in awesome 4.0?

### ISSUE THREAD

**Issue by sphaugh** [awesomeWM/awesome#1723]
Output of `awesome --version`:
```
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

i'd like to be able to use siji ([here](https://github.com/stark/siji)) for my layout icons, and i'm pretty sure this [was possible at one point](https://github.com/TheReverend403/awesome-config)

it looks like `layout_tile` only accepts an image path, though, is this true? it'd be a shame because siji has icons that seem specifically designed for some of the common awesome layouts

**Comment by psychon** [comment]
> and i'm pretty sure this was possible at one point

What exactly makes you say so? Your link just goes to some GitHub repository. That's not much of a helpful link.

I guess you are referring to [this](https://github.com/TheReverend403/awesome-config/blob/2699834c61b3923ca36290d014224fcb80ce4324/themes/leliana/theme.lua#L55-L58). Well, the commit which introduced that part of the theme is https://github.com/TheReverend403/awesome-config/commit/6f73c23d5f434186fa1da2a63f73a04a282236af. This commit also introduces its own layoutbox (starting in line 277 of the new file and up to about 298) instead of using the one provided by awesome.

> it looks like layout_tile only accepts an image path, though, is this true?

Yes.

How would the code know the difference between "this string is a path to an image" and "this string should be displayed as-is". (And please do not suggest to just check if there is an image at that file path - displaying long filenames just because an image was not found is quite ugly.)

**Comment by sphaugh** [comment]
@psychon I see. Thanks for the detailed explanation. Sorry for being a help vampire :)

**Comment by sphaugh** [comment]
@psychon Btw, this was actually pretty easy! Thanks for pointing me in the right direction.

```
s.mylayoutbox = wibox.widget.textbox()
s.mylayoutbox.text = theme["layout_" .. awful.layout.getname(awful.layout.get(s))]
s.mylayoutbox.font = "Wuncon Siji 9"
```

**Comment by blueyed** [comment]
@sphaugh 
> s.mylayoutbox.text = theme["layout_" .. awful.layout.getname(awful.layout.get(s))]

What is `theme` here?  The result from `beautiful.get()`?  Or some custom mapping table?

**Comment by sphaugh** [comment]
@blueyed yes, if you replace e.g. layout_tile image path with the siji glyph. i think you may still need to do connect and emit signals for your buttons/hotkeys
