### ISSUE TITLE
cygwin: proper iconv detection is missing

### ISSUE THREAD

**Issue by ncaldwell** [awesomeWM/awesome#1753]
Compiling from the 4.1 stable tarball in cygwin I was getting linker reallocate issues when building awesome. I found IF(APPLE) block at awesomeConfig.cmake:167 and made it true, and was able to compile it.

**Comment by psychon** [comment]
I guess https://github.com/awesomeWM/awesome/blob/2bb07343c6893d29222c87785c063ea15b1e05b2/awesomeConfig.cmake#L163-L198 has to be replaced with a proper check for libiconv (that tests if its available in libc, then in libiconv, then fails). Hopefully CMake was improved by now and our comment is wrong ("CMake does not provide a module for looking up the library").

**Comment by ncaldwell** [comment]
Perhaps instead of checking for the system you could call pkg-config libiconv, and see if it returns a string or returns nothing. Not sure if this possible with cmake.

**Comment by blueyed** [comment]
@ncaldwell 
Would be great if you could investigate there, since you are able to reproduce the issue yourself.

btw: I wonder how good awesome behaves in general on cygwin.. what do you use to run it?

**Comment by ncaldwell** [comment]
Can you confirm for me that `pkg-config --libs libiconv` is what you call to get libiconv packages?

Apparently I can do it with execute_process, which will put stdout into a cmake variable. I can also put stderr in a variable, which would then not get used. It would ensure that changes to cmake are less likely to cause it to break (it looks like some people seem to think that stderr should go in with stdout unless specified otherwise.) Currently not specifying where stderr should go sends it to cmake's stderr, so this shows up in the output:

```
Package libiconv was not found in the pkg-config search path.
Perhaps you should add the directory containing `libiconv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libiconv' found
```

Calling pkg-config should be fine, as cmake is checking for it earlier in the script... though I've made the assumption that that check stops cmake if it failes.

I'm running a Surface Pro 4, which is why I'm using cygwin. My use case is that work has me living in a terminal and I end up having many open. I've not actually used AwesomeWM before, so I can't provide a comparison, but I've been wanting to try a tiling window manager for a while. At first glance it works pretty well.

**Comment by psychon** [comment]
> Can you confirm for me that pkg-config --libs libiconv is what you call to get libiconv packages?

Hahaha. No, CMake has a tradition of not liking pkg-config (because Windows!!1111oneone). Google found https://cmake.org/pipermail/cmake/2007-October/017032.html which basically does not work: https://cmake.org/pipermail/cmake/2007-October/017044.html

Also, here on Debian testing I get the following:
```
$ pkg-config --libs libiconv
Package libiconv was not found in the pkg-config search path.
Perhaps you should add the directory containing `libiconv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libiconv', required by 'world', not found
```
So nope, that's not going to fly.

I guess the "proper" check needs to verify if `iconv()` is available in libc, then check for the function in libiconv and then give up. Right now we instead guess between "in libc" and "in libiconv" based on "is it Apply or FreeBSD?".

Isn't it great that CMake doesn't have a ready-made "go find iconv"-module and makes it hard to write one?

Another random Google result is https://github.com/PDAL/PDAL/blob/master/cmake/modules/FindICONV.cmake#L75-L82 which is copied from here: https://github.com/tinygettext/tinygettext/blob/master/FindICONV.cmake
(But this code is under a BSD license and so cannot just be copied into awesome... or at least the license header has to stay intact.)
Urgh, CMake...

**Comment by ncaldwell** [comment]
Okay, so making a point not to look at your BSD licenced links, just in case we hit on the same thing.

Can you run ```nm `find /lib /usr/lib -name "*libc.a"` | grep -w T | grep iconv```. Do we have to check that it is in libiconv instead of just checking that libiconv is installed if we find that it isn't in libc?

If what you already have is locating libiconv, and errored out if it isn't there, will it be enough to call this? We just need to get the find command right, i think.

I'm not 100% where we should be searching. I would have thought /lib, /usr/lib and /opt/lib, but noticed that you are searching /usr/local and all of /opt, so I checked where libc was:
```
$ find /lib /usr /opt -name "*libc.a"
/lib/libc.a
/usr/i686-pc-cygwin/sys-root/usr/lib/libc.a
/usr/lib/libc.a
find: ‘/opt’: No such file or directory
```

If we get that right, https://github.com/ncaldwell/awesome/commit/ece87a98a69b58c693232b038e6be8a84aeb49ee might work. Not to confident its not more than a hack, though, as I've never done anything with CMake.

**Comment by psychon** [comment]
> Can you run nm `find /lib /usr/lib -name "*libc.a"` | grep -w T | grep iconv. 

```
00000000000000f0 T iconv_open
0000000000000000 T iconv
0000000000000000 T iconv_close
nm: sigvec.o: no symbols
nm: old_atexit.o: no symbols
nm: strtoll.o: no symbols
nm: strtoull.o: no symbols
nm: strtoll_l.o: no symbols
nm: strtoull_l.o: no symbols
nm: udiv_qrnnd.o: no symbols
nm: mp_clz_tab.o: no symbols
nm: _itowa.o: no symbols
nm: tmpfile64.o: no symbols
nm: iofgetpos64.o: no symbols
nm: iofopen64.o: no symbols
nm: iofsetpos64.o: no symbols
nm: fseeko64.o: no symbols
nm: ftello64.o: no symbols
nm: oldfmemopen.o: no symbols
nm: mempcpy.o: no symbols
nm: bzero.o: no symbols
nm: strcasecmp.o: no symbols
nm: strncase.o: no symbols
nm: memcpy.o: no symbols
nm: wordcopy.o: no symbols
nm: strncmp-ssse3.o: no symbols
nm: memcpy-ssse3.o: no symbols
nm: memcpy-ssse3-back.o: no symbols
nm: strpbrk-c.o: no symbols
nm: wcstoll.o: no symbols
nm: wcstoull.o: no symbols
nm: wcstoll_l.o: no symbols
nm: wcstoull_l.o: no symbols
nm: getdents64.o: no symbols
nm: readdir64.o: no symbols
nm: readdir64_r.o: no symbols
nm: scandir64.o: no symbols
nm: alphasort64.o: no symbols
nm: versionsort64.o: no symbols
nm: scandirat64.o: no symbols
nm: scandir64-tail.o: no symbols
nm: getdirentries64.o: no symbols
nm: glob64.o: no symbols
nm: getopt_init.o: no symbols
nm: pread.o: no symbols
nm: pwrite.o: no symbols
nm: init-posix.o: no symbols
nm: xstat64.o: no symbols
nm: fxstat64.o: no symbols
nm: lxstat64.o: no symbols
nm: fxstatat64.o: no symbols
nm: statfs64.o: no symbols
nm: fstatfs64.o: no symbols
nm: statvfs64.o: no symbols
nm: fstatvfs64.o: no symbols
nm: open64.o: no symbols
nm: openat64.o: no symbols
nm: lseek.o: no symbols
nm: lseek64.o: no symbols
nm: lockf64.o: no symbols
nm: creat64.o: no symbols
nm: ftw64.o: no symbols
nm: fts64.o: no symbols
nm: posix_fadvise64.o: no symbols
nm: posix_fallocate64.o: no symbols
nm: sendfile64.o: no symbols
nm: have_o_cloexec.o: no symbols
nm: xstatconv.o: no symbols
nm: internal_statvfs64.o: no symbols
nm: fallocate64.o: no symbols
nm: getrlimit64.o: no symbols
nm: setrlimit64.o: no symbols
nm: preadv.o: no symbols
nm: pwritev.o: no symbols
nm: mkstemp64.o: no symbols
nm: mkostemp64.o: no symbols
nm: mkstemps64.o: no symbols
nm: mkostemps64.o: no symbols
nm: truncate64.o: no symbols
nm: ftruncate64.o: no symbols
nm: mmap64.o: no symbols
nm: regexp.o: no symbols
nm: lseek.o: no symbols
nm: have_sock_cloexec.o: no symbols
nm: getutmpx.o: no symbols
```

> Do we have to check that it is in libiconv instead of just checking that libiconv is installed if we find that it isn't in libc?

I'd say "no". If something calls itself `libiconv`, it should be safe to assume it is until someone shows up and tells us otherwise.

> If what you already have is locating libiconv, and errored out if it isn't there,

What we already have is:
- If `APPLE` or `FreeBSD`, do the following, else just skip all of it.
- Find `iconv.h`
- Find a library called `iconv`
- Error out if the library was not found (but the header is ignored....?)

> ...will it be enough to call this? 

On systems where iconv is in an extra library: Yes, sure. On other systems: Nope, it would wrongly error out.

> If we get that right, ncaldwell@ece87a9 might work.

I'm not sure. Perhaps just using https://cmake.org/cmake/help/v3.0/module/CheckFunctionExists.html might be enough....

--------

Another idea: What are we using iconv for anyway? Can we just drop it? It seems like we are (wrongly, but whatever) assuming that everything is UTF8 anyway.

**Comment by psychon** [comment]
https://github.com/awesomeWM/awesome/pull/1772 will just drop our use of iconv.
