### ISSUE TITLE
Clipboard cleared after window is closed

### ISSUE THREAD

**Issue by latach** [awesomeWM/awesome#1767]
**Output of `awesome --version`:**
awesome v4.1 (Technologic)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

**How to reproduce the issue:**
1. Select/copy text from a window.
2. Close window.
3. Try pasting text.

**Actual result:**
No text is pasted.

**Expected result:**
Copied text should be pasted

**Comment by blueyed** [comment]
AFAIK the PRIMARY clipboard (text selected with the mouse) gets requested from the owner when pasted, and if the client/window/owner is gone, it does not work.
You might want to use a clipboard manager.  See also https://wiki.archlinux.org/index.php/clipboard#How_to_use_the_selections_.28clipboards.29.

Closing since this is not an issue with Awesome really.
Related: https://github.com/awesomeWM/awesome/pull/1578.

**Comment by latach** [comment]
Okay thanks!
