### ISSUE TITLE
A bug with magnifier mode

### ISSUE THREAD

**Issue by alekcacko** [awesomeWM/awesome#1799]
Output of `awesome --version`:

awesome v4.1 (Technologic)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

NOTE0: Running on Ubuntu 16.10
NOTE1: Using the default config

**How to reproduce the issue:**

1. Change the mode of tiling to magnifier

2. Open few windows.

3. Focus on different window from the tag.

4. Focus on different tag.

5. Return to previous tag

**Actual result:**

The windows are not ordered  the same way.

**Expected result:**

The windows should stay in the same place.

**Screenshots:**

1. Before changing tag
https://s22.postimg.org/4f2klsp1t/before.png

2. After changing tag
https://s21.postimg.org/lko9dm6nr/after.png

**Comment by psychon** [comment]
I tried to bisect this, but it seems like `magnifier` was broken in different ways for a long time without anyone noticing...

What happens is: `magnifier` tries to put the currently focused client on top, but when coming back from another tag, then no client has the focus yet because `awful.autofocus` is waiting and delaying things until later. Thus, the (later) focusd client does not end up at the top.

**Comment by psychon** [comment]
Oh, found it. Commit 55190646c4912a091be54dabd40ae49bff746bb5 caused this.
CC @Elv13 How unhappy would you be with the following diff (which basically reverts the main part of the above commit)? What are the alternatives?
```diff
diff --git a/lib/awful/layout/init.lua b/lib/awful/layout/init.lua
index b8100bb..b78d159 100644
--- a/lib/awful/layout/init.lua
+++ b/lib/awful/layout/init.lua
@@ -269,6 +269,7 @@ capi.tag.connect_signal("tagged", arrange_tag)
 capi.screen.connect_signal("property::workarea", layout.arrange)
 capi.screen.connect_signal("padding", layout.arrange)
 
+capi.client.connect_signal("focus", function(c) layout.arrange(c.screen) end)
 capi.client.connect_signal("raised", function(c) layout.arrange(c.screen) end)
 capi.client.connect_signal("lowered", function(c) layout.arrange(c.screen) end)
 capi.client.connect_signal("list", function()
```
(Adding to v4.2 tag since only after seeing again how it is supposed to work did I notice how broken the magnifier layout still is.)

**Comment by Elv13** [comment]
> CC @Elv13 How unhappy would you be with the following diff (which basically reverts the main part of the above commit)? What are the alternatives?

Rather unhappy indeed. This will cause `arrange` to be called many time when you move the mouse. Also, the bug isn't only in the magnifier layout, it is in the `max` and `fullscreen` ones too (similar issues, different cause). This is another case of "lets add more signals so the thing flicker until it gets it right" I tried to get rid of for #644 to work properly.

If you have a client tagged in many tags (`A` and `B`), one (or more) of them with the `max` layout (here called `A`) and have focus of a client, then go to tag `B` then go back to `A`, then the [clients] union of `A` and `B` will steal the topmost layers and move the last focused client below. This is (almost) the same kind of issue here.

As I recently mentioned in #644, this is also a big problem in my layout rewrite (for the tabbed blocks). The most obvious solution seems to move history and the stack per tag (in C and Lua). It isn't a trivial fix like the one you just propose, but done right, it will close this issue and a couple other. With a stack per tag, it would be possible to restore the layout as it was (assuming the stateless layout is deterministic). With the history per tag, it allows to restore the right focused client. It *will* require some other fixes so this issue is really fixed, but it gets us at least 75% of the way there.

Another option is to remove the `v4.2` tag and leave it as-is for now. While the magnifier layout used to work better, this class of bugs has always existed.

**Comment by psychon** [comment]
> If you have a client tagged in many tags (A and B), one (or more) of them with the max layout (here called A) and have focus of a client, then go to tag B then go back to A, then the [clients] union of A and B will steal the topmost layers and move the last focused client below. This is (almost) the same kind of issue here.

I'll treat this as a different issue for now. The issue here is that raising a client to the top only raises it above all currently visible clients, and not above clients which are currently not visible.

...except that I am wrong and the C code already raises above all clients. Then I am not quite sure what is going on here, but at least max and fullscreen do not handle the currently focused client specially, in contrast to magnifier.

> This is another case of "lets add more signals so the thing flicker until it gets it right" I tried to get rid of for #644 to work properly.

Ok, then how about the following (untested)?
```diff
diff --git a/lib/awful/layout/init.lua b/lib/awful/layout/init.lua
index b8100bb..93315a4 100644
--- a/lib/awful/layout/init.lua
+++ b/lib/awful/layout/init.lua
@@ -269,6 +269,12 @@ capi.tag.connect_signal("tagged", arrange_tag)
 capi.screen.connect_signal("property::workarea", layout.arrange)
 capi.screen.connect_signal("padding", layout.arrange)
 
+capi.client.connect_signal("focus", function(c)
+    local screen = c.screen
+    if layout.get(screen).need_focus_update then
+        layout.arrange(screen)
+    end
+end)
 capi.client.connect_signal("raised", function(c) layout.arrange(c.screen) end)
 capi.client.connect_signal("lowered", function(c) layout.arrange(c.screen) end)
 capi.client.connect_signal("list", function()
diff --git a/lib/awful/layout/suit/magnifier.lua b/lib/awful/layout/suit/magnifier.lua
index fb4df4c..9417722 100644
--- a/lib/awful/layout/suit/magnifier.lua
+++ b/lib/awful/layout/suit/magnifier.lua
@@ -146,6 +146,10 @@ end
 
 magnifier.name = "magnifier"
 
+-- This layout handles the currently focused client specially and needs to be
+-- called again when the focus changes.
+magnifier.need_focus_update = true
+
 return magnifier
 
 -- vim: filetype=lua:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:textwidth=80
```
>  "lets add more signals so the thing flicker until it gets it right"

If I were to argue semantics, I would say that the layout itself always gets it right immediately. Its only that the current state at the time that "it gets it right" is changes 0.0001 seconds later (hm, do we need priorities for delayed calls so that `awful.autofocus` runs earlier?).

> It will require some other fixes so this issue is really fixed, but it gets us at least 75% of the way there.

Sounds like a good long term plan, but it is unlikely to happen in the v4 series (or at least: good luck doing that without breaking user configs).

**Comment by Elv13** [comment]
> Sounds like a good long term plan, but it is unlikely to happen in the v4 series (or at least: good luck doing that without breaking user configs).

That's the `Another option is to remove the v4.2 tag and leave it as-is for now.` part ;)

> Ok, then how about the following (untested)?

I did something similar in the first version of #644 (now cleaned up and done "right"), so I guess it's a possibility. This would also be a good idea for `v5` **if** #644 get integrated (that will *only* happen once it's ready and clean, don't worry) and we want to keep the old layout system as a deprecated feature. #644 needs very few `arrange` calls. For most operation, it doesn't need them at all.

I vote for the second patch
