### ISSUE TITLE
don't use setenv() after process start

### ISSUE THREAD

**Issue by cgwalters** [awesomeWM/awesome#1812]
This is a follow up to https://github.com/awesomeWM/awesome/pull/1809 - basically, don't use `setenv()` after `main()`. 

https://github.com/rust-lang/rust/pull/24741#issuecomment-99860102

In particular, GLib does make threads internally for both a worker thread and GDBus at least.

Rather than passing state via environment to the new process, I'd make a temporary file (`g_mkstemp()`), then call `unlink()` on the resulting file, giving you an anonymous FD.  Next, make a `GVariant` of type `a{sv}` (basically a serialized map) of all the state you want to preserve across `execve()`.  For example, the pids could be a `child-pids` → `at` (array of uint64).  Write that `GVariant` to the tempfile fd.

Then on process startup, read from that fd to deserialize, and close it.

I'd also recommend doing something like distinguishing the *initial* process from all re-`exec`'d ones via something like injecting a `--reexec $tempfd` argument into `argv` for the subsequent `execve`s.  (That's how you know the fd number to read).

Alternatively rather than the fd approach, you could use a (named) tempfile.

**Comment by psychon** [comment]
Sigh. Thanks for breaking my fresh code again. ;-)

Since we do not have much state to preserve (I think our aim is to make restarts unnecessary and Lua's state cannot be serialised anyway), just getting rid of these zombie processes is the only thing that we want to do. I guess that just passing the list of children via the command line is the easiest thing to do, since a temporary file does not add much to this anyway and should be more code to create.
So... `awesome --reap 1234 --reap 2345 --reap 3456` so that `getopt` does most of the parsing for me and I can just use `atoll` on the result.

**Comment by cgwalters** [comment]
Yeah, if you don't have a lot of state, passing via `argv` seems nice and simple.
