### ISSUE TITLE
Generated background takes up only single screen in multi monitor setup

### ISSUE THREAD

**Issue by mrschyte** [awesomeWM/awesome#1818]
Output of `awesome --version`:

awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

Change the theme to "xresources" in rc.lua on a multimonitor setup.

**Actual result:**

Background takes up only a single monitor.

**Expected result:**

Background generated for all desktops.

I've patched the theme_assets.lua file locally to achieve the expected result. Maybe this could be included in the default distribution with some sanity checks for different monitor layouts.

    diff -ur beautiful/theme_assets.lua beautiful-mm/theme_assets.lua
    --- beautiful/theme_assets.lua	2017-06-05 19:07:44.317631889 +0200
    +++ beautiful-mm/theme_assets.lua	2017-06-05 19:08:35.690253037 +0200
    @@ -189,7 +189,7 @@
     function theme_assets.wallpaper(bg, fg, alt_fg, s)
         s = s or screen.primary
         local height = s.geometry.height
    -    local width = s.geometry.width
    +    local width = screen.count() * s.geometry.width
         local img = cairo.RecordingSurface(cairo.Content.COLOR,
             cairo.Rectangle { x = 0, y = 0, width = width, height = height })
         local cr = cairo.Context(img)

**Comment by psychon** [comment]
What does `xrandr` show for you? What does `awesome-client 'local res = {} for s in screen do res[s.index] = s.geometry end return require("gears.debug").dump_return(res)'` produce?
Could you show us your config etc? The only effect of your patch should be that the string "awesome" becomes smaller on your wallpaper, because the calling code scales it down so that it fits onto the screen.

**Comment by mrschyte** [comment]
Hey, thanks for the quick response!

The patch does work on my setup; I see the desktops filled up with the background color and the "awesome" string on my 3rd display in regular size.

Here's my rc.lua file (it's almost the same as the default with some extra key bindings)
https://gist.github.com/anonymous/85b7c21aaa2023c5db5a772367752a8f

Here's the xrandr output:
https://gist.github.com/anonymous/8c65fffbb164dbb6090c45a96ce9c51a

And finally the output from awesome-client:
https://gist.github.com/anonymous/7bdf1a54e93d9edb6f9eb89c32d8341a

**Comment by psychon** [comment]
Your config (line 168): `gears.wallpaper.centered(wallpaper, nil)`
The default config (around line 182): `gears.wallpaper.maximized(wallpaper, s, true)`
So the default config sets the same wallpaper for each screen (the `s` argument). In your config, you pass in `nil` for the screen. This means "set this wallpaper across all screens instead of just for a specific screen". With your `centered`, if the provided wallpaper is too small, then the remaining screens display the color that is provided as the third argument to `centered`. Providing no color means that black is used, which I guess is what you were seeing.

Closing because your wanted behaviour is what the default config does and your unwanted behaviour is what your own config does.

**Comment by mrschyte** [comment]
Thanks for the help, much appreciated. I'll guess I'll stick with my current config for now since I don't want the "awesome" banner on all screens.
