### ISSUE TITLE
Progressbar color can't be modified unless a color is set in the theme

### ISSUE THREAD

**Issue by axujen** [awesomeWM/awesome#1851]
Output of `awesome --version`:
```
awesome v4.1-32-g8fa802d4-dirty (Technologic)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**
Use (or modify) a theme that doesn't define ```beautiful.progressbar_fg```
create a progressbar and attempt to set its color ```progbar = wibox.widget.progressbar({ color = "#FFE000"})```

The resulting progressbar will always be red regardless of what color was given as an argument.

**Actual result:**
Red progressbar

**Expected result:**
Colored progressbar

Note this happens with beautiful.progressbar_bg aswell.
Also using ```beautiful.progressbar_fg = nil``` after the theme is loaded will not reproduce the problem

**Comment by Elv13** [comment]
progbar = wibox.widget.progressbar({ color = "#FFE000"})

The color cannot be set that way. The old constructor syntax isn't very flexible (and never was). Almost no widgets support setting all their properties that way. Please use either the imperative syntax or the newer one:

**Imperative:**

```
local pb = wibox.widget.progressbar()
pb:set_color("#0000ff")
```

**Declarative:**

```lua
local pb = wibox.widget {
    value = 0.5,
    color = "#0000ff",
    border_color = "#00ff00",
    border_width = 3,
    bar_corder_color="#ff00ff",
    bar_border_width = 2,
    background_color = "#ffff00",
    forced_width = 300,
    widget = wibox.widget.progressbar
}
```

![pick13](https://user-images.githubusercontent.com/340384/27210806-f856b3f4-5222-11e7-9bc6-3242783e71d1.png)

It is normal that it will fallback to the theme color when no color is set:

    cr:set_source(color(pbar._private.color or beautiful.progressbar_fg or "#ff0000"))

`pbar._private.color` is *not* set by args. Nor is it documented to do so. I agree it's confusing, as each widgets have their own constructor prototype instead of an unified one. I consider the new syntax to be the unifying aspect while the old one is still supported, but a bit legacy.
