### ISSUE TITLE
naughty.dbus causes a Lua error if naughty.config.notify_callback returns nil/false

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1879]
See https://github.com/awesomeWM/awesome/pull/1875#discussion_r124061762
`naughty.notify` will return `nil` as well and `naughty.dbus` then indexes a `nil` value trying to get the notification id.

**Comment by timroes** [comment]
The problem is: what should be returned? The specification doesn't talk about that a notification server could possibly decide to not show a notification. So it clearly states, 0 shouldn't be returned at all, and that it should always be a unique integer for this notification. I don't know how clients would behave if you just return -1 or even doesn't respond at all. Maybe the client wants to update this notification later and simply passes the returned id again as a replacement id. So I don't know what would be the best solution for this issue, but I don't see a solid solution not breaking with the spec.

**Comment by psychon** [comment]
If we can "invent" a notification id, we could send a proper reply and then immediately afterwards emit the signal that indicates that the notification was closed. Still, sounds complex...

**Comment by Elv13** [comment]
The code causing this issue no longer exists. If the issue still happen, it is a new bug.
