### ISSUE TITLE
Remove widget in runtime

### ISSUE THREAD

**Issue by straf3r** [awesomeWM/awesome#192]
There is function [set_widget()](https://awesome.naquadah.org/doc/api/modules/wibox.layout.margin.html#set_widget) and we can add widget to wibox in runtime.
But there isn't function for runtime widget removing. Yes, we can use [reset()](https://awesome.naquadah.org/doc/api/modules/wibox.layout.margin.html#reset) but it's reset entire layout and it isn't handy for multiple widgets in one layout.

Please implement such function.

**Comment by Elv13** [comment]
Widgets removing can be done using layouts. You can use `table.remove` on the layout `widgets` property of the `flex` or `fixed` layouts. There is no magic. It might not be documented very well, but it just work.

**Comment by straf3r** [comment]
Thank you, i've tried this method and it works (and even without emit_signal).

**Comment by straf3r** [comment]
I see, layout size don't change without signal. Thank you again.

**Comment by psychon** [comment]
You are linking to the margin layout, so I assume you are talking about that one.
The documentation might not make it very clear, but doing `:set_widget(nil)` works fine. For other layouts, what would be a good API? `:remove(3)` removes the third entry of a flex layout? We can't really give a widget to `:remove()`, since a widget can be added multiple times.

However, since things work with the margin layout, I'm closing this. Feel free to reopen if I misunderstood.

**Comment by blueyed** [comment]
@psychon 
> We can't really give a widget to `:remove()`, since a widget can be added multiple times.

It could remove either all of them, or the first one - controlled through some argument.

I could imagine a function `remove_widget()`, which would call `set_widget(nil)` for the margin layout, and would be `remove_widget(w, only_first)` (or something similar) for other layouts.
