### ISSUE TITLE
Update to v4.2

### ISSUE THREAD

**Issue by NoSoyTsundere** [awesomeWM/awesome#1943]
Hello.

I've installed awesome v4.1 from source two months ago on Ubuntu 16.04.

How can upgrade to v4.2?

I've search on internet and found nothing.

**Comment by Elv13** [comment]
The instructions for v4.1 and v4.2 are exactly the same. If you used `make package` (as you should have done), then installing the new package should "just work". Installing Awesome 4.2 on top of 4.1 should also work (but please use the `.deb` packages from `make package` instead of doing that). There is no other steps. Awesome 4.x is backward compatible with every previous versions of Awesome 4.

**Comment by NoSoyTsundere** [comment]
I've installed from source without making a .deb :(

Is there a way to remove v4.1 to install v4.2 or I need to install v4.2 on top of v4.1 as you said?

**Comment by blueyed** [comment]
You need to `make install` it on top then.

**Comment by Elv13** [comment]
> Is there a way to remove v4.1 to install v4.2 or I need to install v4.2 on top of v4.1 as you said?

That's what the package is for. So unfortunately, you will have to do it by hand. First, find which prefix was used when installing Awesome (probably `/usr/local` or `/usr`) when delete the files like `$yourprefix/share/awesome` and `$yourprefix/bin/awesome/`). Using  a `.deb` helps a lot to keep your system clean. Awesome does not provide a `make uninstall` (as we suggest using packages whenever possible).

Or, as @blueyed suggestion, use `make install` on top, but this only make things worst. In the past, some releases removed files and simply using `make install` caused them to stay behind and introduce subtle bugs as they were still loaded by Awesome.

**Comment by NoSoyTsundere** [comment]
Install v4.2 on top of v4.1 works.

I will remove the files whenever I get a free time.

Thank you.

Ps. I'll be using the package option on future installs.
