### ISSUE TITLE
awesome + xpra + urxvt issue

### ISSUE THREAD

**Issue by chiraag-nataraj** [awesomeWM/awesome#1954]
Output of `awesome --version`:
````
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
````

**How to reproduce the issue:**

1. Start an `xpra` server  _without OpenGL_ and attach to it: `xpra start :300 --opengl=no; xpra attach :300 --opengl=no`
2. Open a `urxvt` window inside `xpra`: `DISPLAY=:300 urxvt`

**Actual result:**

The window does not update until I force a repaint (in my case, I toggle the appearance of the wibox at the top).

**Expected result:**

The window should update without my forcing a repaint.

**More info:**

I filed a bug with `xpra` [here](https://www.xpra.org/trac/ticket/1610) and they directed me here.

**Comment by psychon** [comment]
From the bug report you link to:

> My guess is that your window manager is unhelpfully intercepting the expose events. Not much we can do about this.

Please read https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html and tell me how something like this is possible (hint: It is not; AFAIK no protocol extension makes it possible to intercept events either).

Awesome is a window manager. All that awesome does is telling the X11 server where windows are (position, size, stacking order). Awesome is not involved in redrawing windows. At all. And it certainly does not do things that are technically impossible.

-----

Could you try running awesome with `--no-argb` and see if that fixes this issue? If yes, the bug is in your X11 server and/or video driver.
I hope that https://bugs.freedesktop.org/show_bug.cgi?id=99220 is the only bug here, but so far I haven't seen any confirmations. This bug was supposedly fixed in May, but [it seems like](https://cgit.freedesktop.org/xorg/xserver/) no version of the X11 server was released since then.

**Comment by psychon** [comment]
> The window does not update until I force a repaint (in my case, I toggle the appearance of the wibox at the top).

Just to avoid confusion: What exactly does "toggle the appearance" mean? Do you mean hiding/unhiding it? Which means you basically resize urxvt to make it update?

**Comment by totaam** [comment]
BTW, the correct and simplest xpra command lines to use (the rest is either a waste of space or a bad idea):
`xpra start --start=urxvt`
`xpra attach --opengl=no`

**Comment by chiraag-nataraj** [comment]
> Just to avoid confusion: What exactly does "toggle the appearance" mean? Do you mean hiding/unhiding it? Which means you basically resize urxvt to make it update?

Yes. I hide/unhide it.

**Comment by chiraag-nataraj** [comment]
> BTW, the correct and simplest xpra command lines to use (the rest is either a waste of space or a bad idea):
`xpra start --start=urxvt`
`xpra attach --opengl=no`

I didn't use `--start` because that's not how I'm currently using `xpra` (at least in this case). I'm setting up a display and then creating (and destroying) windows over the course of a session (I'm using `xpra` to jail the program), but all of that is somewhat irrelevant as this bug that I'm talking about is happening regardless of whether I start `urxvt` this way or by manually attaching to that display.

**Comment by chiraag-nataraj** [comment]
>Could you try running awesome with `--no-argb` and see if that fixes this issue?

No, I am having the same issue even if I run `awesome --no-argb`.

**Comment by psychon** [comment]
Hm, okay. Let's see...

> awesome v4.0

This might be a duplicate of #1369 / #1340. You don't happen to be able to test awesome 4.1 or v4.2?
If not, does this issue also happen when you are on a tag with a floating layout / when urxvt is already floating when it starts? If the issue goes away there, this might indicate that the missing ConfigureNotify that the two other bugs are about also causes this issue.

**Comment by chiraag-nataraj** [comment]
Yup, that's the problem. If I set up a rule to make URxvt floating by default, the bug is fixed. I'm using Debian unstable/experimental, and apparently they haven't upgraded awesome yet to 4.2...
