### ISSUE TITLE
Move to single-instance client opened (minimized or not) in unfocused tag

### ISSUE THREAD

**Issue by nickdiego** [awesomeWM/awesome#1987]
Output of `awesome --version`:

awesome v4.2-54-g4f0c71c73778 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

This seems to be specifically for clients that implement single-instance mechanism (for example, TelegramDesktop), the problem begins when I've set a rule keep its windows in a specific tag (with `switchtotag = true` to make sure to move immediately to that tag when the client gets focus). Considering my rule is:
```lua
{ rule_any = { class = {"Slack", "Telegram", "discord"} },
      properties = { screen = 1, tag = "chat", floating = true, switchtotag = true }
}
``` 
There are two cases I'd like to confirm with you guys whether are expected to happen or are bugs:
- Case 1: With telegram client opened and **not minimized** in tag `chat`, and `chat` not present in `awful.screen.focused().selected_tags`, click on telegram's systray icon (or even lauch it via menubar, the result is the same)
- Case 2: With telegram client opened and **minimized** in tag `chat`, and `chat` not present in `awful.screen.focused().selected_tags`, click on telegram's systray icon

**Actual result:**

- In Case 1: It won't switch to tag `chat` (only flags client as urgent), unless I add the follwing snippet to my `rc.lua`:

```lua
client.connect_signal("request::activate",
    function(c, context, hints)
        if c and not c:isvisible() then
            awful.tag.viewmore(c:tags(), c.screen)
        end
    end)
```

- In Case 2: Neither it switches to tag `chat` nor the client is flagged as urgent. I didn't realize any way to restore the client or at least move to the tag in this case. 

**Expected result:**

- For both cases, I think with the rule setting `switchtotag = true`, awesome should move to the corresponding tag and (maybe) focus/raise the client.

_I noticed that rules only applied when the clients are spawned. Is there any way to apply them in another situations? (AFAIK I can also call `awful.rules.apply(c)`)_

**Comment by nickdiego** [comment]
Hi @psychon , 

> Sorry, but rules do not have anything to do with this. A rule applies when a new client appears. I am not totally sure what happens when you click on the telegram icon, but I guess that telegram asks the WM to give the input focus to its window (the other option would be that Telegram tells the WM that its window is urgent).

Ok, got it.

> This request then ends up as a request::activate signal on the client which is handled by awful.ewmh. Since the client is not visible (it is not tagged with any selected tag), the code just ends up making the client urgent.

That seems to be the point, when the client is not visible (minimized) the `awful.ewmh.activate` function is not called (I checked it here). **The question is, is this expected ? or is it a bug?** 

 >For case (1), I'll defer to @Elv13 for "the proper solution", but my local hack would be...
I'm ok with the "hack", actually I'm already using this in my `rc.lua` :)

Thanks

**Comment by psychon** [comment]
Are you saying that my proposal above fixes case (1) for you?

For (2), you are saying that the following does nothing in case (2)? `client.connect_signal("request::activate", function(c) naughty.notify({ text = "Got request from " .. c.name }) end)`?
Do you still see the Telegram icon in the tasklist when it is minimized, or does its entry disappear from there? Alternatively: When you click a tasklist entry, the corresponding client gets minimized (at least in the default config). Does minimizing Telegram look the same? Alternatively: How exactly are you minimizing Telegram? Through awesome or through something that Telegram offers?

Could you run `xev -root` and compare its output between case (1) and (2)? (I would expect a `ClientMessage` with `type` set to `_NET_ACTIVE_WINDOW`)

**Comment by nickdiego** [comment]
>Are you saying that my proposal above fixes case (1) for you?

Yes, still not sure if it causes some indirect side effect (??)

>For (2), you are saying that the following does nothing in case (2)? client.connect_signal("request::activate", function(c) naughty.notify({ text = "Got request from " .. c.name }) end)?
Oh, sorry. Yes, the `request::activate` seems to not be emitted for this case :(

>Do you still see the Telegram icon in the tasklist when it is minimized, or does its entry disappear from there? 

Yep, I do.

>Alternatively: When you click a tasklist entry, the corresponding client gets minimized (at least in the default config). 

Yes

>Does minimizing Telegram look the same? Alternatively: How exactly are you minimizing Telegram? Through awesome or through something that Telegram offers?

No, just using `modkey+n` std keybinding using awesome api to minimize...

**Oh, something new:**
when I minimize it and click on its systray icon, being in the "chat" tag, it work correctly (unminimize it and give focus). :thinking: 

_PS :tested also with Discord app, it has the same behavior_

>Could you run xev -root and compare its output between case (1) and (2)? (I would expect a ClientMessage with type set to _NET_ACTIVE_WINDOW)
Ok, I'll send this in a separate commend.

**Comment by nickdiego** [comment]
```lua
client.connect_signal("request::activate", function(c)
    if c.class == "Telegram" then
        c.first_tag:view_only()
        c.minimized = false
        client.focus = c
    end
end)
```
@psychon indeed this caused a side effect when restarting awesome.
I'm using some [Lain's quake windows](https://github.com/copycat-killer/lain/wiki/Utilities#quake), and when they are hidden _(with this hook set)_ they are restored/shown after awesome restarts.

Any insight on how to work around this?

**Comment by psychon** [comment]
Are you really, really sure that this code is responsible for that? It only does something with clients which have class `Telegram` and AFAIK this "quake window" thing is used with terminals, i.e. not with Telegram.

**Comment by nickdiego** [comment]
Oh sorry, you're right! Actually I was using a little bit different one:
```lua
client.connect_signal("request::activate", function(c, context, hints)
    if c and not c:isvisible() then
        c.first_tag:view_only()
        c.minimized = false
        client.focus = c
    end
end)
```
Because I need to handle some other programs (such as, Slack, Discord, Telegram..).
But I guess that's causing the problem I mentioned :( Anyway, even checking the `c.class` it causes some misbehavior when restarting awesome (e.g: if some of those chat apps is open, it gets focused after the restart, what's expected with this new hook).

**Comment by nickdiego** [comment]
> **Oh, something new:**
when I minimize it and click on its systray icon, being in the "chat" tag, it work correctly (unminimize it and give focus). :thinking:

What about this?
It means at least we have no uniform behavior for this kind of use case.

**Comment by psychon** [comment]
> when restarting awesome (

You can detect this case with `awesome.startup`, I think, so `if not awesome.startup and ....`

> What about this?
> It means at least we have no uniform behavior for this kind of use case.

So far I'm still not sure what your programs are doing, plus I am not sure what awesome is doing. I'm still waiting for:

> Ok, I'll send this in a separate commend.

Alternatively, I'd have to figure out which of those is the easiest to install (suggestions? I don't suppose one of them is packaged in Debian?) and try things out for myself. But that would have to wait until at least October.

**Comment by nickdiego** [comment]
>You can detect this case with awesome.startup, I think, so if not awesome.startup and ....

Tried this but it didn't work, actually a realized that the rules are re-applied when the awesome is restarted :thinking: so, when I use "switchtotag" in any rule, it jumps to the latest client it applied the rules to after restarting awesome.

>So far I'm still not sure what your programs are doing, plus I am not sure what awesome is doing. I'm still waiting for:

Oops, sorry, had forgot it.. I'll capture those logs now.

>Alternatively, I'd have to figure out which of those is the easiest to install (suggestions? I don't suppose one of them is packaged in Debian?) and try things out for myself. But that would have to wait until at least October.

Not sure about debian, AFAIK there are packages to Ubuntu.. Here I'm using Arch.. so, if you have some insights on how to solve this I may try to make a patch :)

_getting the logs..._

**Comment by nickdiego** [comment]
@psychon 

Here are the `xev --root` logs, for cases

1. Unminimized: Successfully focus client and switch to its tag;
2. Minimized: Neither focus client nor urgent its tag/client

 https://gist.github.com/nickdiego/dedaa9c66f074f8e3901aa22fd67a17e

**Comment by nickdiego** [comment]
UPDATE:

Digging into the `ewmh` and `client` implementation and analyzing the `xev -root` logs (I'm pretty new to x11/xcb internals), I've realized that when the client is minimized and you switch to other tag and tries to switch back that client (by clicking on its systray icon) the event `_NET_ACTIVE_WINDOW` for the client does not appears in the `xev` output. As far as I could understand, this event would be handled by `ewmh.c::ewmh_process_client_message()` > `ewmh.lua::activate()`...

When follow the same steps, except moving to another tag, for some reason X server sends the `_NET_ACTIVE_WINDOW` event, and the client gets focused as expected.

So, maybe "move to tag" process is making something that's causing this bug.

**Comment by psychon** [comment]
Are you sure you did not mix up case (1) and (2)?

Hm, I fear there is nothing that awesome can do about this then.

In case (2), there is a `ClientMessage` of type `_NET_ACTIVE_WINDOW` (line 215). This tells the WM "please give me the input focus". Since your program was not on an visible tag, this is what caused awesome to mark the window as urgent instead. (There is also some kind of startup sequence (lines 260 to 267, meaning that something is reported as just starting and opening a new window?!?).

In case (1) there is no such `ClientMessage`, so of course nothing happens. There are only the following kinds of events:
- `MotionNotify`: The mouse cursor moved. Not interesting to us
- `LeaveNotify` / `EnterNotify`: The mouse cursor moved to another window. Not interesting to us.
- `CreateNotify`: A new window was created (but is not visible at this point!). Not interesting to us.
- `MapNotify`: Some window was made visible. Since this has `override YES`, it is some window that is not managed by the WM. Perhaps a tooltip? I don't know.
- `KeymapNotify`: Keyboard layout changed (in some tiny way). Just ignore this.
- `UnmapNotify` / `DestroyNotify`: Some window was mapped invisible again and destroyed. Also not relevant here.

**Comment by psychon** [comment]
> When follow the same steps, except moving to another tag, for some reason X server sends the _NET_ACTIVE_WINDOW event, and the client gets focused as expected.

That's not sent from the X server. Some other program (I would bet it is Telegram (or whatever you are using)) sends this message to the WM. It means "please give the input focus to me".

When no such message happens, well, what should we do? We do not even know that you clicked on the tray icon, and even if we did, we couldn't map that information to any window.

So I think it is Telegram which does nothing here.

**Comment by nickdiego** [comment]
>That's not sent from the X server. Some other program (I would bet it is Telegram (or whatever you are using)) sends this message to the WM. It means "please give the input focus to me".

Hmmm, got it and makes sense :)

>When no such message happens, well, what should we do? We do not even know that you clicked on the tray icon, and even if we did, we couldn't map that information to any window.

Agreed.

So, rephrasing...

>When follow the same steps, except moving to another tag, for some reason the client in question sends the _NET_ACTIVE_WINDOW event, and the client gets focused as expected.
> So, maybe "move to tag" process is making something that's causing this bug.

Also, other clients have the same behavior - tested at least with Telegram (uses Qt5 I guess), Discord (not sure but I think it uses GTK), and Slack (WebkitGTK, Electron or somthing like this). This makes me believe it is still something from awesome side, maybe when "tag:view_only()" is used with those clients.. not sure :(

**Comment by psychon** [comment]
Clients know about being minimized (`_NET_WM_STATE_HIDDEN` in their `_NET_WM_STATE` property and the Iconic flag in their `WM_STATE` property), so I would still think that for some reason the clients do not send the "please focus me"-request when they are minimized.

Clients could also know about not being on a visible tag (`_NET_WM_DESKTOP` on their window and `_NET_CURRENT_DESKTOP` on the root window), so this might as well influence their behaviour.

Anyway, there is no way for awesome to prevent a `_NET_ACTIVE_WINDOW`-message to be received. If it is sent, it shows up somewhere.

I took a look at gtk+-3.22.18: The `_NET_ACTIVE_WINDOW`-request is sent by `gdk_x11_window_focus` (static function in `gdk/x11/gdkwindow-x11.c`, easily found by `grep`). This function is used to implement the `focus` virtual method of `GdkWindow` and thus is called directly by `gdk_window_focus()`.

The only (relevant: the rest has win32 in their name) caller for `gdk_window_focus` is `gtk_window_present_with_time` and `gtk_window_present` (which just calls the `_with_time` variant). This function has an `if (gtk_widget_get_visible (widget))` and only calls `gdk_window_focus` if this returns true.

So I guess GTK does not believe that focusing a minimized window makes sense (I did not check if minimizing really ends up making `_get_visible` return false, but I guess so). Thus, it is GTK that "eats up" the request. Also, I am not sure what happens in the "not visible" case (`gtk_widget_show` is called and this ends up calling function pointers which I cannot easily follow).

All together: Sorry, but I think the cases where we can help you with were handled and the remaining problem cannot be worked around since nothing tells us that "something" happened. Thus, I'll close this. However, feel free to leave more comments here and I'll try to answer as good as I can. I hope you do not feel let down and I hope I was helpful.

Cheers,
Uli

**Comment by psychon** [comment]
> (uses Qt5 I guess),

Well, okay. qtbase-opensource-src-5.9.1. Grepping for `_NET_ACTIVE_WINDOW` finds `QXcbWindow::requestActivateWindow()`. This function has an `if (!m_mapped)` in which case it does not do much. This boolean is set to false when an `UnmapNotify` is received and Qt gets such a notification when its window is minimized. Thus, Qt also does not send us a "please focus this window"-request for minimized windows.

**Comment by nickdiego** [comment]
Thanks for the kind and detailed explanation @psychon
Yes, you're really helpful!
