### ISSUE TITLE
Fullscreen/maximized windows should not be able to resize themselves or be resized by the user

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#2036]
**How to reproduce the issue:**

* Run urxvt
* Fullscreen it
* Run `printf '\33]50;%s%d\007' "xft:Terminus:pixelsize=" 10`
* Run `printf '\33]50;%s%d\007' "xft:Terminus:pixelsize=" 20`
* Continue however you want with messing with the font size

**Actual result:**

* Urxvt no longer has fullscreen size

**Expected result:**

* Urxvt cannot resize itself like this.

**Investigation:**

This is a regression introduced in 631e75a7573e69d16c6636882e05301d76ff20d6. Before that, `awful.ewmh` connected to `property::geometry` in clients and "fixed things up". To quote the commit message:

> And stop listening to property::geometry, it's no longer needed.

Well, apparently it is.

-----

Looking at the C code, a client resizing itself these days ends up emitting a `request::geometry` signal on the client object. This signal is caught by  `awful.ewmh` and the case of "client resizes itself" is handled by `awful.ewmh.client_geometry_requests`. So... I guess just teaching that function to ignore such requests for fullscreen/maximized clients would be enough, right?

"Original report" by @blueyed. Analysis mine. :-)

**Comment by kajzersoze** [comment]
I'm new to AwesomeWM and I've noticed that there is no true fullscreen, for example in Kodi while watching some video or while playing some game in Steam I can still see desktop notifications (they are not visible in other DE's while in fullscreen) , also because of that I can see slight lag in Kodi, same everything (distro and hardware) I just logout from awesomewm and login to i3wm for example (same with mate, xfce, gnome, plasma) and it works fine there.
Apart from that I really like AwesomeWM, but this fullscreen issue is just not good for me, I tried to google about it but couldn't find anything, am I missing something or it's like that and that's it?

**Comment by blueyed** [comment]
@kajzersoze 
It should be a separate issue.
You are using the fullscreen mode (meta-f) vs. the maximized mode (meta-m)?
Please create a new issue with this information added.

**Comment by psychon** [comment]
Related: #2061

**Comment by Elv13** [comment]
The API is:

     client.disconnect_signal("request::geometry", awful.ewmh.client_geometry_requests)

To disable the codepath that honor this request
