### ISSUE TITLE
True fullscreen -> disable notifications 

### ISSUE THREAD

**Issue by kajzersoze** [awesomeWM/awesome#2047]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.0

**How to reproduce the issue:**

Start Kodi , in settings for display select fullscreen.

**Actual result:**

Desktop notifications are visible.

**Expected result:**

Desktop notifications are not visible.

I'm new to AwesomeWM and I've noticed that there is no true fullscreen, for example in Kodi while watching some video or while playing some game in Steam I can still see desktop notifications (they are not visible in other DE's while in fullscreen) , also because of that I can see slight lag in Kodi, same everything (distro and hardware) I just logout from awesomewm and login to i3wm for example (same with mate, xfce, gnome, plasma) and it works fine there.
Apart from that I really like AwesomeWM, but this fullscreen issue is just not good for me, I tried to google about it but couldn't find anything, am I missing something or it's like that and that's it?

**Comment by kajzersoze** [comment]
Maybe naughty needs something like[ this](https://github.com/mate-desktop/mate-notification-daemon/blob/c556e09077bb820e752d7266d2b20328db629883/src/daemon/daemon.c#L1630) , to detect if fullscreen is active and if so to disable notifications in that case (except if timeout for that notification is 0, in which case it will be shown)

**Comment by blueyed** [comment]
ah.. so you only see naughty's notifications then?
I've thought it was about notifications in general.

**Comment by kajzersoze** [comment]
In other DE's I don't see them in fullscreen (except if timeout is 0), in Awesome I see them, I thought that it had something to do with fullscreen code somewhere since I've seen lots of other issues regarding fullscreen and because I can notice a slight lag while watching videos in fullscreen (minor but still noticeable), same software same movie different wm and there's no lag.

**Comment by Elv13** [comment]
For the lag, it's IMO confirmation bias. Some WMs/DE disable compositing when apps are in full screen. Awesome doesn't have compositing, so we don't have to do that. Fullscreen is just maximization, but bigger. Otherwise there is no changes. Awesome keeps painting the wibars and doing all you asked it to do. If you want more speed, maybe try to enable LuaJIT. Awesome isn't the fastest WM in the universe. Its API focuses on being powerful and easy to use rather than targeting raw speed. The LGI library we use for GLib and Cairo is also doing some slow atrocities and none of us dare to fix it to avoid a regression apocalypse.

For the notifications, you can suspend them when fullscreen is active, but I guess that's not what you want.

**Comment by kajzersoze** [comment]
I see, okay I'll try with LuaJIT and see if that makes any difference.

As for notifications, I'm Lua noob, but I guess I can probably figure out how to add FS detection and if timeout=0, and if so to disable showing them.

**Comment by kajzersoze** [comment]
LuaJIT didn't help, in fact I think it's even worse.

btw I use Compton, i3wm doesn't have compositor as well and it's fine there with Compton.
Anyway, it's not a big deal but it's there for sure, I had to ask because I couldn't find more info about this. I'll leave it open and you guys can close it if you feel it should be closed.

**Comment by psychon** [comment]
Some untested code idea (this does not detect the fullscreen layout, only individual fullscreen clients):
```
local function update_naughty_suspended()
    for _, c in awful.screen.object.get_clients() do
        if c.fullscreen then
            naughty.suspend()
            return
        end
    end
    naughty.resume()
end
client.connect_signal("property::fullscreen", update_naughty_suspended)
tag.connect_signal("tagged", update_naughty_suspended)
tag.connect_signal("property::selected", update_naughty_suspended)
```
While a fullscreen client is visible, this should suspend naughty.

**Comment by kajzersoze** [comment]
Got "Oops, an error happened!" , for this line :
`for _, c in awful.screen.object.get_clients() do`

error says "attempt to call a table value"

**Comment by kajzersoze** [comment]
I managed to make it work, it's working fine thus far.

```
function naughty.config.notify_callback(args)
  local c = client.focus
  if c then
	if c.fullscreen and args.timeout ~= 0 then
		naughty.suspend()
		return
	else
		naughty.resume()
		return args
	end
  end
end
```

**Comment by kajzersoze** [comment]
Well, it does what I wanted, I even included sounds.
There's that lag left but it's sporadic and it only happens with Kodi, playing the same videos with mpv and there's no lag, tried to understand why it happens with Kodi but I wasn't able to figure it out,  exactly the same settings in different WM and there's no lag, tried to change few settings but it's still there. Interesting, hopefully I'll figure it out at some point. 
Anyway... I'll close this, thanks everyone!

**Comment by Elv13** [comment]
Is your rc.lua doing some sync I/O (gmail/weather download or reading big files) or execute commands using `io.open()`? Those are 2 giant performance killers and should not be used.

**Comment by kajzersoze** [comment]
Well, I'm using [this](https://github.com/lcpz/awesome-copycats), Multicolor theme.
I would have to inspect everything from there (didn't have much time for that, this is all new to me), but I would say no, there is weather widget but I think there's nothing to it, besides I would notice that everywhere, not just in Kodi. I think but can't remember now, that this was happening with stock rc.lua, not a problem to test that but I'm sure it was happening with it as well. It's something with Kodi and Awesome, there is one thing that is interesting, in every other WM/DE there was a segfault in Kodi when I exit from it and return to desktop, in AwesomeWM it's not happening.

**Comment by psychon** [comment]
You could also try running awesome with `--no-argb`.

**Comment by kajzersoze** [comment]
Same thing with `--no-argb` , didn't make any difference.

**Comment by cuu** [comment]
it's funny I am facing a problem is I want notify on when enter into a fullscreen window
like retroarch
retroarch can cover naughty  in fullscreen's mode

the only thing I find out is if I set `video_windowed_fullscreen = "true"`  then I can see naughty 

I want naughty on even `video_windowed_fullscreen = "false"`

**Comment by Elv13** [comment]
> hopely there is an option force a window on absolutely TOP of others ,no matter what

Awesome z-index support sucks. We have hardcoded layers and placing clients/wibox on top relative to each other or prevent "z-index stealing" is not currently possible. There was discussions on IRC over the years about that. At some point I had patches to implement a indexed-bucket based z-indexing instead of hardcoded layers. In theory I need to merge them before I propose the dynamic layout system again, but meh, I am lazy and it will cause a *lot* of review cycles before it gets merged.

Currently, you can use signals to watch `request::activate` for clients (and you are on your own for wiboxes). Then you can loop trough all clients and wiboxes and `:raise()` them in the right order. It sucks, but works.

The idea behind the bucket `z-index` is having a private C-API and exposing the `z_index` property in Lua. Setting that send `request::z_index` and you can have filters on that like focus filters and `awful.rules` to implement the behavior you want. A default filter would re-implement the old layer API on top of that bucket API to preserve compatibility. A second default handler would allow `c:raise_above(c_or_w)` and `c:lower_below(c_or_w)` to be implemented, which solve the problem I have with the dynamic layouts tabs.

The current patches is ancient and is almost just a bunch of `TODO` comments. @psychon, what do you think? Do you mind doing the C side so we avoid the usual million reviews everytime I touch those code paths.


Core-API (capi):

 * client._z_index = int *and* wibox._z_index in the same buckets
 * root._get_z_index_drawins(int)
 * root._get_z_index_clients(int)
 * root._move_above(origin_c_or_w, target_c_or_w, "above_or_below")
 * Make sure `c:swap()` swaps the object of they are in the same bucket
 * Remove all the layer code

(in any case, this if for v4.4/v5.0, not v4.3)

**Comment by psychon** [comment]
Uhm... so what is the resulting stacking order that you want?
Right now we have something (basically) like:
- For each layer
  - Go through `globalconf.stack` and stack objects that are assigned to this layer in the order that they are seen

I have two possible interpretations for your proposed z-indicies:
- "Everything" is put into a big array that defines the stacking order. The z-index is the index in this array. (But then I don't really see how the C code should handle assignment of a new index)
- (Since you talk about buckets, I guess you rather mean:) there is a global array. Each index is a z-index and this contains a list of "everything" with that index. But then, how are things inside of the buckets ordered?

Also, what exactly does `move_above` do? Is it "if they are in different buckets, do nothing; if they are in the same bucket, change their order"?

Also, so far I do not really see what problems this proposed API solves (but I guess it would cause awesome to require more CPU time since implementing the current/old system requires each bucket to have only one entry, so if something in the stacking order changes, "everything" needs to be assigned a new z-index).

If this is merely about having naughty ontop of fullscreen clients, then naughty's `ontop = true` option does that (see #2373).

**Comment by Elv13** [comment]
> (Since you talk about buckets, I guess you rather mean:) there is a global array. Each index is a z-index and this contains a list of "everything" with that index. 

Yes

> But then, how are things inside of the buckets ordered?

Another index given it's an array

> Also, what exactly does move_above do? 

Reorder the array elements for that z_index array.

> Also, so far I do not really see what problems this proposed API solves

* Being able to raise clients and wiboxes relative to each other.
* Not having an hardcoded list of layers. For example, of you want to display the size of the clients in a wibox when resizing (blueyed do it), then having `optop` is not even enough. You also have to raise them every time to make sure they are above `ontop` clients. Having a layer just for that would make this kind of use case easier to implement.
* Being able to add filters to prevent z_index stealing (this issue) so random wibox and clients can't get above fullscreen ones even if they try. This is not limited to notifications, `request::urgent` and `request::active` from clients can currently do it too.
* In case of my dynamic layout system, the tabs are a pita to handle. Placing the tabbar at the "right" index to match it's content is hard and ugly. Also placing the clients within the tab stack correctly require looping all clients and calling ":raise()"
* Restoring a tag is currently broken when clients are in multiple tags. When you swap them in `tag2` and then select `tag1` again, the layout changed. That's very visible, but there is the same bug with the stack order (and current focus) too. This is a pair of bugs I don't want my dynamic layout system to have because, especially with tabs, it is **a lot** more visible than it currently is.

> but I guess it would cause awesome to require more CPU time since implementing the current/old system requires each bucket to have only one entry, so if something in the stacking order changes, "everything" needs to be assigned a new z-index).

No, a "bucket"/"array" (whatever you want to call those groups) per layer is enough. So that gives between 1 and 4 buckets/array (but usually just one unless you use `ontop`/`below`)

**Comment by psychon** [comment]
Okay, so you are not aiming at traditional z-indicies here. Instead, let's call them `layer`s. Now, you want to create layers dynamically and "mess with" the order between them. Both clients and wiboxes can be assigned to a layer, but only to a single one. Inside the layers, the behaviour of `:swap` is the same as it is today.

So...
- Layers should be objects instead of integers. Hardcoding integers just means that "oh noes, I cannot move A between B and C, because `C = B+1`".
- Each wibox and client has a `.layer` property that is writable (that is `nil` by default? That's just the first layer by default? Dunno, but both these options are ugly)
- Layers have `.windows`, `.clients`, and `.drawins` as properties (which return an array, i.e. a table with integer keys; things are in this order inside the layer).
- If you want, you can have `root.layers()` similar to `client.get()` and `root.tags()` to get a list of layers.
- I'm not quite sure what to do with `root._move_above`, but actually, I think that this is orthogonal to layers; something like `c:move_below(c2)` and `c:move_above(c2)` should already be possible today (but I guess needs to be generalised to also be able to handle drawins; no idea yet how to implement that...)

**Comment by Elv13** [comment]
Sound very good.

(I didn't want to propose layers as objects because of the comments in #1487, but I also prefer them to be objects.)

**Comment by Elv13** [comment]
> So, feel free to open an issue (possibly only when time has come?)

The time came? #2512

**Comment by kajzersoze** [comment]
Little update on this, I was talking about two issues, second one was the lag in Kodi when watching videos. For about two weeks maybe I am running Awesome with `--no-argb` and the lag is gone.
Back then I said it didn't make any difference but most likely I didn't run it right that time.
