### ISSUE TITLE
"urxvt -bl" (borderLess) creates unmanagable client

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#209]
With `urxvt -bl` I am getting a rxvt-unicode window that cannot be focused / closed easily, and is present on all tags.

From `urxvt(1)`:

       -bl Compile frills: Set MWM hints to request a borderless window, i.e.  if
           honoured by the WM, the rxvt-unicode window will not have window
           decorations; resource borderLess. If the window manager does not
           support MWM hints (e.g. kwin), enables override-redirect mode.

Is this the override-redirect effect?

**Comment by psychon** [comment]
Yeah, "redirect" is the WM "redirecting" things so that it can manage windows (e.g. when you want to map a window, that operation is redirected and instead a MapRequest is sent to the WM). "override-redirect" basically means "the WM won't notice anything about this".

So either this should be "implement MWM hints in awesome" or "urxvt is doing the wrong thing".
