### ISSUE TITLE
startx crash: org.awesome.awful not provided by any service files

### ISSUE THREAD

**Issue by twentytwoo** [awesomeWM/awesome#2105]
awesome 4.2
Booted up computer (working fine earlier), X crashes because of:
`org.freedesktop.DBus.Error.ServiceUnknown: ... org.awesome.awful was not provided any service files DBus send failed. ...`, see below image for full error;

https://my.mixtape.moe/yfgqzt.jpeg

Apologies for the image, it's the best I can do considering my computers current state.
Grateful for any help.

**Comment by psychon** [comment]
Sorry, but that is not an error message from awesome. That is `/usr/bin/dbus-send` (used by `awesome-client`, likely) saying that it could not contact a running awesome instance. Thus, this doesn't say us anything about why awesome does not start.

Do you know what prints this weird list of `.desktop` files? Is there anything in `/var/log/xorg.0.log` that seems like an error? What's in your `~/.xinitrc` (or how do you start awesome?)? What if, instead of starting awesome, you start something else, for example xterm? Does that work? One last idea: Anything in `dmesg` saying that something crashed?

**Comment by twentytwoo** [comment]
No idea what's printing the `.desktops`, it's always done that for me...
xorg log:
https://hastebin.com/efexafoyek.txt

These lines look interesting:
```
[   201.446] (WW) xf86CloseConsole: KDSETMODE failed: Input/output error
[   201.446] (WW) xf86CloseConsole: VT_GETMODE failed: Input/output error
[   201.446] (WW) xf86CloseConsole: VT_ACTIVATE failed: Input/output error
```

dmesg:
https://hastebin.com/dogoruhube.txt

Starting GNOME works fine (I think that's on wayland now though), in any case I'll try putting xterm into my xinit...

**Comment by twentytwoo** [comment]
Opening xterm on its work doesn't crash X, so it's definitely something awesome related

**Comment by psychon** [comment]
> [  169.275219] DiscordCanary[2315]: segfault at 968 ip 00007fcd71550ed3 sp 00007ffca08d5ba0 error 4 in libX11.so.6.3.0[7fcd71523000+13a000]

Looks unrelated, but still: huh?!?

What happens when you start without awesome, but with an xterm, and then start awesome from that xterm? This would also make sure that all of awesome's output and possible error messages end up in that xterm. (Also, you could then start some other WM from this xterm, if you have any installed; that might make it easier to capture output).

**Comment by twentytwoo** [comment]
awesome still crashes doing that, I managed to capture the stderr though...
https://www.hastebin.com/sahaharozu.txt

Here's my config,
https://github.com/twentytwoo/awesome

**Comment by Elv13** [comment]
```
error while running function!
stack traceback:
	/usr/share/awesome/lib/wibox/init.lua:328: in function 'wibox._apply_shape'
	/usr/share/awesome/lib/wibox/init.lua:361: in function 'wibox.set_shape'
	/usr/share/awesome/lib/wibox/init.lua:519: in metamethod '__newindex'
	/usr/share/awesome/lib/wibox/init.lua:541: in function </usr/share/awesome/lib/wibox/init.lua:462>
	(...tail calls...)
	/usr/share/awesome/lib/naughty/core.lua:773: in function 'naughty.core.notify'
	/etc/xdg/awesome/rc.lua:24: in main chunk
error: /usr/share/awesome/lib/wibox/init.lua:328: attempt to call a string value (local 'shape')
```

In your theme:

    theme.notification_shape = ""

The shape is not a string, it's a function

**Comment by twentytwoo** [comment]
I just commented that out and it works - strange, I must've had it like that for months and it never complained, was there an update or something recently?

**Comment by Elv13** [comment]
Not recently, but type errors are likely to appear as Awesome does *not* protect itself against these since they fall in the "garbage in garbage out" type of problem. Having a message on stderr is cleaner than doing random things to mitigate type errors. That's the problem with dynamic languages in general, checking every single input would pollute the code and slow it down.

By the way, most of the deprecated messages there are simple find&replace type of changes, you should fix them so the errors stand out.

Finally, you should post your config in the screenshot page so other users can take inspiration from your code/work.

**Comment by twentytwoo** [comment]
I see, I'll get around to fixing those errors sooner or later, as for now I'm glad to be "home" (gnome sux).
I'll be uploading that screenshot now.

**Comment by psychon** [comment]
Side note: You seem to be on debian and debian recently had an update to awesome in testing which, for example, switched to Lua 5.3.
