### ISSUE TITLE
wibox.widget.textclock + %W Week Number not working

### ISSUE THREAD

**Issue by adebruyn-abit** [awesomeWM/awesome#2118]
Hi Everybody,

Since 4.0, mytextclock is not working anymore. The week number of the year seems to be broken.

With mytextclock = wibox.widget.textclock(" %a %d %b (W%W/D%j), %H:%M:%S ")  nothing is displayed.
If I remove the %W, the textclock is displayed.

Thanks for the feedback.

**Comment by psychon** [comment]
This comes from the fix for #249. Previously, we used Lua's `os.date` which is documented to use the C function `strftime`. The fix for #249 switched to `g_date_time_format`. The [documentation for this function](https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format) states:

> The format strings understood by this function are a subset of the strftime() format language as specified by C99. The %D, %U and %W conversions are not supported, nor is the 'E' modifier. The GNU extensions %k, %l, %s and %P are supported, however, as are the '0', '_' and '-' modifiers.

I don't know why they do not support `%W`, but this is where the problem comes from. Dunno what should be done about this. My preferred solution would be for someone to add support for `%W` to glib, but I guess that will not happen...

**Comment by psychon** [comment]
@adebruyn-abit Do you perhaps want `%V` instead of `%W`? `LC_ALL=C man strftime` describes `%V` as:

 The ISO 8601 week number (see NOTES) of the current year as a decimal number, range 01 to 53, where week 1 is the first week that has at least 4 days in the new year.  See also %U and %W.  (Calculated from tm_year, tm_yday, and tm_wday.)  (SU)

and `%W` as:

The  week  number  of  the  current  year  as  a  decimal number, range 00 to 53, starting with the first Monday as the first day of week 01.  (Calculated from tm_yday and tm_wday.)

and the NOTES say:

%G,  %g,  and  %V  yield  values calculated from the week-based year defined by the ISO 8601 standard.  In this system, weeks start on a Monday, and are numbered from 01, for the first week, up to 52 or 53, for the last week.  Week 1 is the first week where four or more days fall within the new year (or, synonymously, week 01 is: the  first  week  of  the year  that  contains  a Thursday; or, the week that has 4 January in it).  When three of fewer days of the first calendar week of the new year fall within that year, then the ISO 8601 week-based system counts those days as part of week 53 of the preceding year.  For example, 1 January 2010 is a Friday, meaning that just three days of  that  calendar  week fall in 2010.  Thus, the ISO 8601 week-based system considers these days to be part of week 53 (%V) of the year 2009 (%G); week 01 of ISO 8601 year 2010 starts on Monday, 4 January 2010.

I'll close this under the assumption that you are fine with using `%V` instead of `%W`. Feel free to complain if this is wrong.

**Comment by adebruyn-abit** [comment]
Thanks Psychon, I now use %V which suits my need.
