### ISSUE TITLE
Emacs (make-frame-visible) ignoring rules and window placement.

### ISSUE THREAD

**Issue by djgalvan** [awesomeWM/awesome#2137]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. Create a bash script to toggle emacsclient visibility.
```
#!/bin/bash

if [[ $(emacsclient -e '(visible-frame-list)' | grep "$HOSTNAME" | head -c1 | wc -c) -ne 0 ]]; then 
	emacsclient -e '(make-frame-invisible)'
else 
	emacsclient -e '(make-frame-visible)'
	if [[ $(emacsclient -e '(visible-frame-list)' | grep "$HOSTNAME" | head -c1 | wc -c) -ne 1 ]]; then 
		emacsclient -c
	fi
fi
```
2. Set binding to toggle visibility
`    awful.key({ modkey }, "a", function () awful.spawn.with_shell(guieditor) end,
              {description = "run gui editor", group = "launcher"}),
`
3. Allow emacs to float by default or set rule to enforce maximization.

4. Toggle visibility 3x-6x.......

**Actual result:**

Frame walks off screen on each toggle. Issue not present on KDE or XFCE.

**Expected result:**

The frame should reappear in place.

**Comment by psychon** [comment]
Hi,
Vim user here (and my OS is GNU/Linux, sorry). Is it correct that `make-frame-[in]visible` basically hides and shows the whole emacs window, so that from Awesome's point of view the window disappears completely and eventually a new window shows up?
If so, could you change your `border_width` in awesome to 42 and see if emacs' window now moves by 42x42 pixels to the bottom left?

If so, I bet that this is a bug in emacs and is basically the same issue as https://github.com/awesomeWM/awesome/issues/532#issuecomment-148742967: Awesome actually uses X11 borders while everything else does not. Thus, no code adds in the border width when placing windows.

**Comment by djgalvan** [comment]
Ah, yes it does move accordingly. I lined the window up to the top and it actually shifts up the border_width + the titlebar height.

**Comment by psychon** [comment]
Could you get me the output of `/usr/bin/xwininfo` for your emacs window? If `WM_NORMAL_HINTS` has `window gravity: NorthWest` (which I guess it has), then this code here is wrong: https://sources.debian.org/src/emacs25/25.2+1-2/src/xterm.c/?hl=10893#L10979-L10991
(Since I didn't do this in a while: Thank you @stapelberg for Debian Codesearch! I only had to search for `make-frame-visible` and then `x_make_frame_visible` to find this nonsense of code.)

Also, the bug here is in emacs. The author of that comment should read ICCCM's definition of window gravity and then remove all that code. Querying the position of the emacs window here will always end up with position zero/zero in a reparenting WM. And the unexpected offset that the comment talks about is the required behaviour for NorthWestGravity....

**Comment by psychon** [comment]
Okay, I found a computer with emacs (getting `emacsclient` to work is annoying). During `make-frame-visible`, emacs does the following:
```
391.562 002:>:83ff:32: Reply to GetGeometry: depth=0x18 root=0x00000127 x=726 y=210 width=590 height=499 border-width=0
391.562 002:<:28400: 20: Request(12): ConfigureWindow window=0x05000387 values={x=724 y=182}
```
So basically emacs moves itself by `-2 x -28` pixels. Why it does that is beyond me, I don't want to look at that mess of code anymore, and I would bet that just withdrawing and re-mapping the window would work correctly.
