### ISSUE TITLE
tasklist: Use higher-resolution client icons

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#2143]
This is basically a follow-up to #299. The issue is the same, but since #299 is supposedly fixed, I am reporting as a new issue...

Note: This is tasklist-specific. #299 was indeed fixed for titlebars, but the tasklist still does not support this.

**Comment by Elv13** [comment]
This now landed in my branch. I reworked a lot of little details about how templates work to get rid of the annoying boilerplate code. Before these changes, the way it worked using a bunch of callbacks was too ugly to use. Now, with the changes, you can just put a `awful.widget.clienticon` as-is in the template and it just works. Of course, this was done for the notification icon, but since I originally created the template API for the notifications anyway, it has the nice side effect of working for the tasklist too.
