### ISSUE TITLE
Maximized clients leave gaps instead of filling out hidden titlebars 

### ISSUE THREAD

**Issue by Frederikam** [awesomeWM/awesome#2148]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

1) Script awesomewm to respectively hide and show titlebars upon maximizing and un-maximizing a client. Example code: https://github.com/Frederikam/dotfiles/commit/ecb0d9b766ad35d44a3991f103d79a2adefe27c5
2) Maximize a client

<details> 
<summary>Before maximizing </summary>

![image](https://user-images.githubusercontent.com/2582617/34556298-0d618eba-f136-11e7-919c-a59af2960c95.png)

</details>

<details> 
<summary>After maximizing </summary>

![image](https://user-images.githubusercontent.com/2582617/34556310-18792a2e-f136-11e7-9c95-dc369c71041a.png)

</details>

**Actual result:**
The maximized client leaves a gap the same height below the client content (tested only with a top titlebar).

**Expected result:**
The client should fill the gap as it is maximized

**Comment by psychon** [comment]
@Elv13 Why does `awful.placement` track (=re-force placement) the signals for width, height and border_width, bot does not track x/y (or just `property::geometry` instead of the individual parts)?

What happens here is that first `request::geometry` is emitted to resize the client to maximized size and then `property::maximized` to notify that the maximized state changes. However, since @Frederikam is (effectively) resizing the client in response to `property::maximized`, the maximized size was already applied at this point...

**Comment by Elv13** [comment]
> @Elv13 Why does awful.placement track 

Because some users (including, but not limited to, @blueyed) were not happy when it tracked x/y. It had something about moving maximized clients across screens then unmaximizing them. IMO it was nicer without that hack, but whatever makes people happy...

@Frederikam: To fix the issue, you need to replace the `request::geometry` handler found in `awful.ewmh` with one that add/remove the titlebar. These handlers exist for such use case. They allow to disconnect the default Awesome behavior and replace it with something custom.

As @psychon noted, the current "bug" is not really a bug, but a race condition between the `request::geometry` signal handler and the `property::maximized` signal handler. It isn't "really" a bug, it is normal in the sense you run 2 pieces of code that contradict each other.

Note that Awesome-git has an extra feature called "immobilization" that tracks if a client can be moved/resized and prevent many instanced of such accidental offsets. It will be part of 4.3. However it will only make it worst for you until you replace the `request::geometry` handler. It is the only way you will get your feature to work properly.

**Comment by psychon** [comment]
@Elv13 So, you are saying that something like the following (untested) is needed and should work?
```lua
client.disconnect_signal("request::geometry", awful.ewmh.geometry)
client.connect_signal("request::geometry", function(c, ...)
    if c.maximized then
        awful.titlebar.show(c)
    else
        awful.titlebar.hide(c)
    end
    return awful.ewmh.geometry(c, ...)
end)
```
@Frederikam Could you test this, please?

**Comment by Frederikam** [comment]
Sorry for the late reply, I was very busy.

Thanks @psychon and @Elv13, that snippet works like a charm, albeit I had to negate the condition.

Closing this as it was a race condition in my code.
