### ISSUE TITLE
menubar.utils.lookup_icon() not finding icons in ~/.icons

### ISSUE THREAD

**Issue by varingst** [awesomeWM/awesome#2152]
**Hello fine folks of awesome**

Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.0

I run awesome on gentoo, built from the `awesome-releases/4.2` tarball.

**How to reproduce the issue:**

I have an icon theme in `~/.icons/ACYLS`. All icons are svg.

In my theme I have `theme.icon_theme = "ACYLS"`

(I couldn't find any mention of `theme.icon_theme` in the [docs](https://awesomewm.org/apidoc/libraries/beautiful.html#Theme_variables) btw)

Disclaimer, what follows is not pasted from running code and output, but merely representative of what I've been tinkering with, so it may contain typos, etc:

```
local m_utils = require("menubar.utils")
local icons = require("menubar.icon_theme")()
local function find(icon)
    print("looking for icon '" .. icon .. "'")
    print("find_path", icons:find_icon_path(icon))
    print("lookup(c)", m_utils.lookup_icon(icon))
    print("lookup", m_utils.lookup_icon_uncached(icon))
end
find('gtk-stop')
find('transmission') 
```

**Actual result:**

```
looking for icon 'gtk-stop'
find_path    $HOME/.icons/ACYLS/scalable/actions/gtk-stop.svg
lookup(c)    nil
lookup       false
looking for icon 'transmission'
find_path    $HOME/.icons/ACYLS/scalable/apps/transmission.svg
lookup(c)    /usr/share/icons/hicolor/48x48/apps/transmission.png
lookup       /usr/share/icons/hicolor/48x48/apps/transmission.png
```

**Expected:**

For `lookup*` to produce what `find_icon_path` does

**What is up, from what I can tell:**

[Here](https://github.com/awesomeWM/awesome/blob/cc68ac929209c8b33c2ece662d075ab20ec1458f/lib/menubar/utils.lua#L168#L171) you are looking in `~/.icons/icons` instead of `~/.icons`

Then you are iterating over all possible fixed size icon sizes, looking for an `apps` dir. You'll miss `/scalable/apps`

**Question:**

Why are you deprecating `menubar.{icon_theme,index_theme}` ? It parses the `index.theme` metadata, and you can even add and cache your own icon paths. For people writing stuff like widgets (like me), it would be handy to have some means of locating and managing icons. I get that `menubar` only cares about app icons, but getting those is 95% of the way. (and the deprecated implementation is already there, as far as I have gleamed.)

**Question the second, unrelated:**

Where would be an appropriate place to post not so much issues, but more practical questions about how to approach certain things with the awesome api?

**Comment by psychon** [comment]
> Here you are looking in ~/.icons/icons instead of ~/.icons

Uhm... Feel free to send a patch (I don't have the time right now, sorry), but I guess the other paths that are checked do need an extra `/icons/`, right? So this has to be done a bit carefully.

> Why are you deprecating menubar.{icon_theme,index_theme} ? 

It turned out it wasn't actually used much. It was only used to look up category icons (e.g. an icon representing the "games" category). That meant something like six icon lookups for the menubar, compared to lots of icon lookups for the actual apps. Still, these six icon lookups were slow enough to cause minutes-long freezes. (Without looking too much, just searching for "menubar slow": #1496 #1726)
So, while this implementation was actually doing what the spec said, for whatever reason it turned out that most of awesome was not actually using it and still it was too slow. That's why it was deprecated.
See also #908 which is about cutting things down to only one implementation and #2090 which adds some code to read `icon_theme.cache` files (but isn't merged since nothing actually uses this implementation yet).

> Where would be an appropriate place to post not so much issues, but more practical questions about how to approach certain things with the awesome api?

Personally, I don't mind using issues for this (as long as they have some reasonable level of competence; if your issue begins with "I don't know Lua, so how do I do this:", then it is not a good issue). Besides that, I am monitoring (rss feed :-) ) the awesomeWM tag on stackoverflow and the awesomeWM subreddit on reddit. Dunno what others are doing.

**Comment by varingst** [comment]
> patch

I can see if I have time later tonight. What do you want done with `/scalable`, just added to the size table?

I remember reading #908 a while back when I was looking for icon lookup for widgets, decided to wait it out until it was resolved. #2090 looks neat, I might tinker some with that the next time I have a full evening free.

> "I don't know Lua, so how do I do this:"

I might have been on the receiving end of that. If you keep tabs on SO I can post stuff there when I have something.
