### ISSUE TITLE
The loop time error

### ISSUE THREAD

**Issue by re-mx** [awesomeWM/awesome#2179]
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

- Start awesome WM
-  cat .xsession-errors

**Actual result:**

.xsession-errors:
```
2018-02-06 09:46:03 W: awesome: a_glib_poll:432: Last main loop iteration took 0.104990 seconds! Increasing limit for this warning to that value.
```

**Expected result:**

No error

<hr>

So this is [my config](https://github.com/re-mx/mxconfig/blob/master/awesome/rc.lua), Very sorry about you, I copy most of the default configuration.
But I do not understand, what did I do wrong to cause this error message?

Thank you very much.

**Comment by Elv13** [comment]
Maybe there is nothing "wrong". What's the hardware this is running on?

Your config seems fine at first glance. The warning says that one "frame" (main loop iteration) took 104ms to render/compute. You usually want to keep this under 16ms (60fps), especially when playing games.This often happens either because the hardware is slow, a driver is slow or the user did something wrong like using `local data = io.popen("curl www.example.com")`. If `io.popen` or other blocking I/O functions are used, the whole computer performance will take a very serious hit due to Awesome single threaded nature and the X11 design itself. There is no way to differentiate between user errors and plain slow hardware. Because of that, we always print the warning when slow frames are detected.

If you really, really want to get rid of it, you can try using Awesome with `luajit` or tweaking your graphic driver settings. Otherwise you can safely ignore the warning. A single frame at 104 isn't so much of an issue. However, if you play video games and see many of those warnings (with ever growing length), it might be worth investigating what's going on.

Also, it could happen if you do something CPU/IO/SWAP intensive that fills up [some kernel buffers](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/131094). However this is less and less true as the rise of Android (among other thing) put some resources (money) into fixing these bottlenecks.

**Comment by re-mx** [comment]
It may indeed be a hardware performance issue ...

I am running awesomeWM on a single-core, low-voltage i7 CPU and 2G memory virtual machine. 
Then when I change the wallpaper to the default png wallpaper (I'm using jpeg wallpaper now), the warning disappears ...

**Comment by Elv13** [comment]
If you only get the warning once, it's probably pointless to do anything about it. Maybe it would be worthwhile to show the warning only when ~5 loop iteration burst the threshold, instead of a single isolated one. But then again, doing nothing and leaving this as-is may prevent adding useless complexity to Awesome codebase for a corner case only 1% of the user ever hit. After all, it's just a warning in stderr, not an annoying popup.

**Comment by re-mx** [comment]
Well...

Every time I restart awesome, I receive a warning.

You mean I do not care about it?

**Comment by Elv13** [comment]
Right, the warning is "true" in the sense it warns of the potential latency caused by long event loop iteration. However you clearly get it because it takes time to decode your wallpaper. A single long iteration is not a problem. It is only a problem when many iterations are that long. However, Awesome does not have the necessary code to profile such issue. It warns as soon as a single iteration break the threshold and of subsequent iterations taking longer than the previous worst one.

Ignore the warning.

**Comment by re-mx** [comment]
Thanks
