### ISSUE TITLE
Must restart for new timezone to take effect

### ISSUE THREAD

**Issue by garrison** [awesomeWM/awesome#2218]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

I have a clock made using `wibox.widget.textclock("%a %b %e, %l:%M %P")`.  I change the timezone on my system, using `sudo dpkg-reconfigure tzdata` (or whatever mechanism the distribution at hand uses).

**Actual result:**

The clock does not update its timezone without restarting awesomewm.

**Expected result:**

The clock should update its timezone immediately or soon thereafter.

I am not certain, but I suspect this may be a regression due to #1743.  The local timezone is being determined outside the callback, but it should be determined within it.

**Comment by psychon** [comment]
Since I do not want to mess with my system's timezone for testing: Do you want to test a fix for this? Do you perhaps even want to propose a PR to fix this yourself? Your analysis seems correct to me.

If not, could you at least test the following command? It prints one line per second, the first entry should not follow timezone changes while the second one does: `lua -e 'local glib = require("lgi").GLib local tz = glib.TimeZone.new_local() while true do print(glib.DateTime.new_now(tz):format("%a %b %d, %H:%M"), glib.DateTime.new_now(glib.TimeZone.new_local()):format("%a %b %d, %H:%M")) glib.usleep(1000*1000) end '`

A fix should be as simple as
```diff
diff --git a/lib/wibox/widget/textclock.lua b/lib/wibox/widget/textclock.lua
index f7c8bf78..d4c5765e 100644
--- a/lib/wibox/widget/textclock.lua
+++ b/lib/wibox/widget/textclock.lua
@@ -36,7 +36,7 @@ end
 
 function textclock:set_timezone(tzid)
     self._private.tzid = tzid
-    self._private.timezone = tzid and TimeZone.new(tzid) or TimeZone.new_local()
+    self._private.timezone = tzid and TimeZone.new(tzid)
     self:force_update()
 end
 
@@ -84,10 +84,10 @@ local function new(format, refresh, tzid)
     w._private.format = format or " %a %b %d, %H:%M "
     w._private.refresh = refresh or 60
     w._private.tzid = tzid
-    w._private.timezone = tzid and TimeZone.new(tzid) or TimeZone.new_local()
+    w._private.timezone = tzid and TimeZone.new(tzid)
 
     function w._private.textclock_update_cb()
-        local str = DateTime.new_now(w._private.timezone):format(w._private.format)
+        local str = DateTime.new_now(w._private.timezone or TimeZone.new_local()):format(w._private.format)
         if str == nil then
             require("gears.debug").print_warning("textclock: "
                     .. "g_date_time_format() failed for format "
```

**Comment by garrison** [comment]
I "backported" this patch to awesome v4.2, and it restored the correct timezone behavior.

**Comment by actionless** [comment]
i don't think 4.2 branch will be receiving any fixes, will be good if you'll prepare a PR to the current master branch
