### ISSUE TITLE
Non-focusable windows get focused in spite of their WM_HINTS

### ISSUE THREAD

**Issue by larkery** [awesomeWM/awesome#2222]
I use yad (https://sourceforge.net/projects/yad-dialog/) to make floating windows with buttons that send text to the focused window when I click them (using xdotool type). This depends on yad being unfocusable, as otherwise clicking the button focuses it, which then means that the text gets sent to yad rather than to the window that used to be focused.

In other window managers (xmonad, i3) I find that running yad with `--no-focus --on-top` works as intended (the window cannot ever take focus, even when clicking on it).

In awesome (which is otherwise awesome) yad is focusable even when using `--no-focus`. The mechanism this is working by is `WM_HINTS`.

This happens using the default config.

Output of `awesome --version`:
```
awesome 4.2 (Human after all)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```
**How to reproduce the issue:**

Add rule `{ rule_any = { class = {"Yad"} } , properties = {floating = true} }`

Run `yad --no-focus --on-top --mouse`

Click on and off the dialog

**Actual result:**

Dialog appears focused. When it's not focused, clicking on the dialog causes it to become focused.

**Expected result:**

Dialog shouldn't ever be focusable, because:

```
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
```

**Comment by psychon** [comment]
Note that in actual X11-terms, the window is not actually focused (because, well, it does not want to be). We just pretend to Lua that it is focused since too much stuff assumes that assigning to `client.focus` cannot fail.

Thus, you have to work around this in your config. Since you do not want the dialog to get focus on click, you have to touch this part of the default config:
```lua
clientbuttons = gears.table.join(
    awful.button({ }, 1, function (c) client.focus = c; c:raise() end),
    awful.button({ modkey }, 1, awful.mouse.client.move),
    awful.button({ modkey }, 3, awful.mouse.client.resize))
```
Replacing `function (c) client.focus = c; c:raise() end),` with `function (c) if c.focusable then client.focus = c; c:raise() end end),` should give you the behaviour that you want.

**Comment by larkery** [comment]
This has worked, thank you very much!
