### ISSUE TITLE
How to set alias for awesome's run command?

### ISSUE THREAD

**Issue by ayatana** [awesomeWM/awesome#2245]
I want to use ranger as my file manager. But ranger cannot run on it's own. It has to run in a terminal. Therefore to start ranger, I have to press Meta+R and then type `xfce4-terminal -e ranger`. I was wondering where can I set alias for the something like `alias ranger='xfce4-terminal -e ranger'` that will work with awesome's run?

**Comment by Elv13** [comment]
The prompt uses `awful.spawn` and not `awful.spawn.with_shell`. So there is no shell. Using `alias` is a shell feature, so it wont work. Your alternative are:

* Edit the prompt in rc.lua so it uses a shell (https://awesomewm.org/apidoc/libraries/awful.prompt.html#exe_callback)
* Put `#!/bin/bash \n xfce4-terminal -e ranger` in a file (replace `\n` with a new line) placed somewhere in your `$PATH`.

**Comment by leolca** [comment]
@Elv13 could you provide an example on how to use a shell in `exe_callback` inside `rc.lua`?

I'm trying to use a script which will persists a variable, therefore I need to execute it with `source`. I've tried an alias but it also did not work. 

>     * Edit the prompt in rc.lua so it uses a shell (https://awesomewm.org/apidoc/libraries/awful.prompt.html#exe_callback)

**Comment by Aire-One** [comment]
Hello @leolca, sorry for the late reply.

The `exe_callback` is a plain function where you define what should actually happen when the prompt is executed (AKA when the user press enter).

You can here use `awful.spawn.with_shell` utility function here to run the command with your shell.

Note that this issue is old, and the prompt widget can use a shell with the `with_shell` property since https://github.com/awesomeWM/awesome/commit/a559f55c6a5d4f8eb4f28fd35b14d8dce9bb54e9
