### ISSUE TITLE
awesome switch screen will move all programs onto a single screen tag, rather than keep it as it was

### ISSUE THREAD

**Issue by chengweiv5** [awesomeWM/awesome#2247]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

0. there are several programs running on **different tags**
1. setup xrandr.lua, refer to https://awesomewm.org/recipes/xrandr/
or
just use xrandr command line to switch screen, e.g.

```
# xrandr --output eDP-1 --off --output DP-1 --auto
```

**Actual result:**

screen switched, but all programs are running on **the same** tag now

**Expected result:**

screen switched, but all programs are still running on the tag which it was on the previous screen.

**Comment by Elv13** [comment]
Ref https://github.com/awesomeWM/awesome/issues/1344

The issue can be mitigated using the tag `request::screen` (https://elv13.github.io/classes/tag.html#request::screen) signal or by using virtual screens. 

This pull request also helps https://github.com/awesomeWM/awesome/pull/2223

Otherwise it isn't really a bug. It's more like a generally inconvenient default behavior. From Awesome point of view, one screen was destroyed, then one was created. It allows to move these tags to the new screen, but does not assume it's always what the user wants.

Anyhow, there is ~5 open issues and 1 PR that cover each aspects of this issue, so I will close it as a duplicate.

**Comment by chengweiv5** [comment]
Thanks, I'll give a try.

**Comment by chengweiv5** [comment]
[The answer](https://www.reddit.com/r/awesomewm/comments/5r9mgu/client_layout_not_preserved_when_switching/) on reddit resolved my problem, just delete those screen geometry compares since my external monitor has different geometry with my laptop.
