### ISSUE TITLE
Move systray icon along with window

### ISSUE THREAD

**Issue by chengweiv5** [awesomeWM/awesome#2248]
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

0. start a program which has an icon in systray, like google-chrome browser
1. the systray icon on the screen0, and move the single google-chrome window to screen1 by key-binding **modkey + o**

**Actual result:**

google-chrome window moved to screen1, but its systray icon still in screen0, this is a little confuse.

**Expected result:**

google-chrome window moved to screen1, and its systray icon moved to screen1 too.

If this is mission impossible, please let me know, thanks, I did read something in awesome FAQ below

> Can I have a client or the system tray on multiple screens at once?
No. This is an X11 limitation and there is no sane way to work around it.

**Comment by Elv13** [comment]
I don't think it's *impossible*, but it is honestly probably not going to happen. First of all: X11 systray protocol wasn't designed for it, any workaround is a hack and we don't merge hacks. But there is also the fact that there is many corner cases that cannot be handled at all.

1) If Chome has multiple windows, then it is not possible to have the systray on all the screens
2) If the user has 2 systray widgets but 3 screens, then where do you place the icon if it should be on the "missing" one?

Plus there is the fact that the whole X11/XDG systray protocol is a dead mess. Unity and KDE had a newer specification, but Gnome refused to implement it and now Unity is dead. So there is 3 competing specs and only the most broken one is considered standard (due to being old).

I think the current situation is the sanest implementation we came come up with without turning Awesome-x11 into a compositing manager (double the codebase size: wont happen). It's not that the idea is bad in itself, it's just that it cannot be implemented with a better result than the current one.

**Comment by chengweiv5** [comment]
Thanks, I found a hack to move systray around the screen, if I change the `primary` screen, then systray will always moved to the `primary` screen.

So if I want to use notebook, then I have to set it as primary screen, e.g. use xrandr, and the systray is now showing on notebook.

I also found a awesome [recipe](https://awesomewm.org/recipes/xrandr/) is helpful.
