### ISSUE TITLE
Awesome uses high CPU when key held down

### ISSUE THREAD

**Issue by gbell12** [awesomeWM/awesome#230]
I'm using the ['standard'] (http://awesome.naquadah.org/wiki/Conky_HUD) way of getting Conky to work with awesome.  Thing that's weird is that when I hold down the key to activate it, Conky zooms up in its CPU usage.

That makes sense since a function is being called every time they key repeats, BUT, this didn't happen on 3.4.15.  Just showed up when I switched to 3.5.6.

Problem?  Screws up my 'top' display in Conky if nothing else.
![screenshot from 2015-05-16 07 49 43](https://cloud.githubusercontent.com/assets/3937658/7662556/2e1ce47a-fba1-11e4-9e7f-549184b42a7d.png)

**Comment by ff2000** [comment]
gbell12 wrote:
> I'm using the ['standard'] (http://awesome.naquadah.org/wiki/Conky_HUD) way of getting Conky to work with awesome.  Thing that's weird is that when I hold down the key to activate it, Conky zooms up in its CPU usage.
> 
> That makes sense since a function is being called every time they key repeats, BUT, this didn't happen on 3.4.15.  Just showed up when I switched to 3.5.6.
> 
> Problem?  Screws up my 'top' display in Conky if nothing else.
> ![screenshot from 2015-05-16 07 49 43](https://cloud.githubusercontent.com/assets/3937658/7662556/2e1ce47a-fba1-11e4-9e7f-549184b42a7d.png)

Just a slightly OT question:
I get "403 Forbidden" when trying to open that link. I already saw that several times with cloud.githubusercontent.
Is that just an issue with how you configured your cloud, or do I have to change something in my github settings?

**Comment by psychon** [comment]
I will assume you mean the "press and hold" system from that wiki page.

Ok, I installed conky and got that ugly code from the wiki. I get 3% CPU usage by the X11 server and about 2% for awesome (although I have to admit that I have only conky and urxvt open. I guess with many open clients the code may slow down more).

I can't really see what we could do about this. Yes, it might be possible to handle key repeat specially so that Lua can tell them apart from normal key repeats, but I'd be lazy and just optimize the Lua code:
- Instead of this slow `get_conky()` function which iterates over all clients, add `callback = function(c) conky_instance = c end` to the rules (although this means one now has to check `conky_instance.valid` before using it).
- To avoid the restacking (and flickering! How can anyone stand this?) due to conky's `.ontop` property being toggled repeatedly, I would use a timer which hides conky e.g. 0.5 seconds after the key release. This might look nicer (does it?), but the code could especially avoid this repeated toggling.

And no, I do not know why I only see 2% CPU usage while you see a lot more. I don't think anything much changed in awesome which could explain this.

I'm closing this for now since I don't really know what to do about it. Feel free to reopen if you think otherwise (or want me to make that Lua code from the wiki faster).

**Comment by blueyed** [comment]
@psychon 
> or want me to make that Lua code from the wiki faster

Would be appreciated, of course.  I am not using conky myself, but it seems to be popular.

**Comment by psychon** [comment]
First attempt (doesn't really make a difference, so finding conky wasn't the problem):
```lua
do
	local conky = nil

	function get_conky(default)
		if conky and conky.valid then
			return conky
		end
		conky = nil
		for c in awful.client.iterate(function(c) return c.class == "Conky" end) do
			conky = c
			return conky
		end

		return default
	end

	function raise_conky()
		get_conky({}).ontop = true
	end

	function lower_conky()
		get_conky({}).ontop = false
	end

	function toggle_conky()
		local conky = get_conky({})
		conky.ontop = not conky.ontop
	end
end
```
Problem is solved if we add and use this function (the timeout could also be set to 0.01 for people who do not want this behavior; come on, 10ms you can tolerate!):
```lua
	local t = gears.timer({ timeout = 0.5 })
	t:connect_signal("timeout", function()
		t:stop()
		lower_conky()
	end)
	function lower_conky_delayed()
		t:again()
	end
```
Anyone wants to add this to the wiki?
