### ISSUE TITLE
Clicking in clients with `focusable = false` still sets the focus

### ISSUE THREAD

**Issue by p-himik** [awesomeWM/awesome#2328]
Output of `awesome --version`:
```
awesome v4.2-289-g98e5922 (Human after all)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
Add a rule that sets `focusable` client property to `false`.
Restart Awesome, open a client that should trigger the rule, try clicking inside it.

**Actual result:**
The client is focused.

**Expected result:**
I would expect that with `focusable = false` the client cannot be focused at all since the documentation for `focusable` says: "True if the client can receive the input focus."

If being able to focus a client with a mouse click regardless of the value of `focusable`, is there any way to prevent clicks from focusing a particular client?

**Comment by psychon** [comment]
> Actual result:
> The client is focused.

Is it really focused (as in: when you type, those keyboard events are sent to the client?) or does it merely look focus, as in the color of the titlebar changes?
Because the former would actually be a bug, while the later is something we need in awesome. Otherwise, e.g. cycling through clients with `Mod4+j` gets stuck next to unfocusable clients.

> is there any way to prevent clicks from focusing a particular client?

Just don't focus the client in your rc.lua. In `clientbuttons, there are three cases that all first to `client.focus = c`. You can replace this with `if c.focusable then client.focus = c` (should we add that change to the default config?).

**Comment by psychon** [comment]
@Elv13 Note that (I think) your commit is not related to this issue, because this clicks the clients itself, not its entry in the tasklist.

**Comment by p-himik** [comment]
> Is it really focused [...] or does it merely look focus, as in the color of the titlebar changes?

It's both. I don't have titlebars, but the client's border changes according to my theme and I'm able to type in it.

> Just don't focus the client in your rc.lua

Huh, for some reason I was sure that LMB handling was in Awesome's code, but I couldn't find anything. Thanks, that works!

By the way, just in case - I use it in IntelliJ IDEA 2018.2. They've done something to the search popup again, and it's not a popup but a dialog that _must not_ be focused in order to work.
