### ISSUE TITLE
Missing mkdir when something deleted doc/images/ in the build directory

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#2342]
Another little regression

Step to reproduce:

```sh
git clone awesome
cd awesome
mkdir build && cd build
cmake ..

# The SVG are in the BUILD_DIRECTORY

make

# The doc is generated

rm -rf doc

make

# A lot of Generating build/doc/images/AUTOGEN_awful_placement_no_offscreen.svg...
# messages, but no SVG is in the BUILD_DIRECTORY
```

**Comment by psychon** [comment]
The problem is that `build/images/` is not `mkdir`'d again (it only happens in `tests/examples/CMakeLists.txt`, so only during "configure"). So... either there needs to be a target that `mkdir`s this directory and all the tests have to be changed to depend on this, or the tests themselves have to be thaught to `mkdir` this target. Dunno, both options are somewhat ugly.

The problem is so silent due to missing error checking in the example tests. The following makes the tests (that use this one template) fail instead:
```diff
diff --git a/tests/examples/awful/template.lua b/tests/examples/awful/template.lua
index 9f84404f..51b277d7 100644
--- a/tests/examples/awful/template.lua
+++ b/tests/examples/awful/template.lua
@@ -230,5 +231,6 @@ for _, h in ipairs(mouse.old_histories) do
 end
 
 img:finish()
+assert(img.status == "SUCCESS", img.status)
 
 -- vim: filetype=lua:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:textwidth=80
```

> Another little regression

Nope, no regression. This problem exists since commit 02f894ce0cb14f05b78ee76dacdf1ecab7ecc09a. Before that, tests only ever run during `cmake`, so the `mkdir` was done by CMake. This commit ensures that the example tests are re-run during `make` if one of their dependencies changed.
