### ISSUE TITLE
Occasional XCB connection errors on receiving Discord notification

### ISSUE THREAD

**Issue by zetaPRIME** [awesomeWM/awesome#2361]
Output of `awesome --version`:

```awesome v4.2-407-g17018118-dirty (Human after all)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
Running on Arch Linux with AUR package `awesome-luajit-git`; launched via LightDM and used concurrently with Compton.

**How to reproduce the issue:**

Recieve a DM, highlight or other notification from Discord, using Naughty as your notifier

**Actual result:**

Occasionally, seemingly at complete random, the screen goes black, followed by the Discord notification sound playing as the user is dumped back to the TTY before LightDM starts back up. No error indicated in `~/.xsession-errors` or `~/.xsession-errors.old`, except that the X server has suddenly gone missing. This only occurs with notifications from Discord, with no seeming pattern as to what about the notification causes the issue.

**Expected result:**

Notification displaying as usual.

**Comment by actionless** [comment]
sometimes i have the same crashes because of rocketchat notifications

is discord also using electron?

**Comment by zetaPRIME** [comment]
yep! one of two electron apps I use (other being Atom); think there's some relation?

**Comment by psychon** [comment]
How about `/var/log/Xorg.0.log` and `Xorg.0.log.old`? Anything interesting in there? Anything in the kernel log? Anything in `sudo journalctl --since="5 minutes ago"` or `/var/log/messages` or something similar?

**Comment by actionless** [comment]
i didn't found anything except for the message in awesome stderr what connection to X server was lost (however X server is still running after that), i'll save that trace next time i'll encounter it

**Comment by psychon** [comment]
How did you determine that Xorg is still running even though awesome claims it lost its connection? Could it be that Xorg was just restarted?

**Comment by actionless** [comment]
because all the applications are also remained running

i'm using this startup wrapper to avoid losing running apps if awesome crashes:
https://github.com/actionless/awesome_config/blob/devel/packaging/awesome_no_argb

**Comment by psychon** [comment]
> except for the message in awesome stderr what connection to X server was lost 

What was the exact error message? The message should be something like `X server connection broke (error 42)`. The following error codes are possible:
- The other end closed the socket  / writing to the socket failed / reading from the socket failed / `select` or `poll` failed (error 1)
- Something tried to use an X11 extension that the server does not support (error 2)
- Out of memory (`malloc`, `calloc` or `realloc` returned `NULL` (which they never do in practice)) (error 3)
- A request exceeding the maximum request length was sent (error 4)
- The value of the `$DISPLAY` variable is malformed (error 5, can only happen when initially connecting to the X11 server)
- A screen was specified which does not exist on the server (error 6, can only happen when initially connecting to the X11 server)
- Some FD passing failed (e.g. the server tried to send more FDs than the kernel wants to store at any single time and thus some FDs were dropped; or the server sent too many FDs) (error 7)

My "best guess" would be error 7, but then my follow-up question would be: Which piece of code is trying to do FD passing?!? Are you both on archlinux?
If one of you is adventurous and has debugging symbols for libxcb: You could attach gdb to awesome (from some TTY!), set a breakpoint on `_xcb_conn_shutdown` and get a backtrace for when this bug happens again (which would then manifest itself as a freeze instead of awesome exiting).

**Comment by psychon** [comment]
@actionless Could you open a new issue for that, under the assumption that @zetaPRIME is seeing another bug?

**Comment by actionless** [comment]
i am 70-80% sure it's related :-)

btw if you want i can also upload test code of example electron app

will test the patch now

**Comment by actionless** [comment]
i was able to reproduce the issue once per each 200-300 testruns, now with a patch it already running more than 5000 of testruns and looks good so far
