### ISSUE TITLE
awesome and retroarch

### ISSUE THREAD

**Issue by cuu** [awesomeWM/awesome#2373]
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**
run retroarch -L xxxx.so xxxx.rom
in ~/.config/retroarch/retroarch.cfg 
set 
`video_windowed_fullscreen = "false"` 
`video_fullscreen = "true"`

**Actual result:**
can not see naughty's window anymore

**Expected result:**
still can see the naughty's window ,for informations

it's funny I am facing a problem is I want naughty on when I  enter into a fullscreen window
of  retroarch
retroarch can cover naughty  in fullscreen's mode

the only thing I find out is if I set `video_windowed_fullscreen = "true"` in retroarch.cfg   then I can see naughty  as usual

I want naughty on even `video_windowed_fullscreen = "false"` 

hopely there is an option force a window on absolutely TOP of others ,no matter what

here is the xprop's results of `video_windowed_fullscreen = "true"` and `video_windowed_fullscreen = "false"` 

```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FULLSCREEN
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 20, 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
WM_NAME(STRING) = "RetroArch mGBA 0.7-WIP 9dd7301 || Frames: 512"
WM_CLASS(STRING) = "retroarch", "retroarch"
```

```
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_NAME(STRING) = "RetroArch mGBA 0.7-WIP 9dd7301 || Frames: 3328"
WM_CLASS(STRING) = "retroarch", "retroarch"

**Comment by psychon** [comment]
Did you try notifications with `ontop = true`? `naughty.notify{ text = "foo", ontop = true }`

**Comment by cuu** [comment]
I tried
but without  `video_windowed_fullscreen = "true"`  
naughty still not not shown

**Comment by cuu** [comment]
I also comment in that issue
then I found out it was closed and is and opposite demand to me

so I opened this issue and see if there is a lucky 
:)

**Comment by cuu** [comment]
and I see
naughty is ontop=true by default 
right?

**Comment by psychon** [comment]
Ah, sorry, I missed that part.

Okay, so I took a look at retroarch's source code. They (sometimes) create an override-redirect window. Such a window is not controlled by the WM. In fact, such a window is completely invisible to the WM. You have to get retroarch not to create such a window so that awesome can stack other windows (e.g. naughty notifications) ontop of it.
How to do that, I do not know. You can best ask the reotrarch people that.

Searching for `XCreateWindow` through their source code, I see that:
- the code in `gfx/drivers/xshm_gfx.c` and `gfx/drivers/xvideo.c` always creates "normal" windows. No idea how to make retroarch use the xshm or xvideo backend.
- the code in `gfx/driver_context/xegl_ctx.c` and `gfx/drivers_context/x_ctx.c` does... things. You want:
  - `windowed_fullscreen` to be enabled (`video_info->windowed_fullscreen`)
  - you don't want xfwm
  - You want your WM to support `_NET_WM_STATE_FULLSCREEN` (awesome does this)

I googled a bit for retroarch logs, and apparently running it with `--verbose` generates that output, but from the code I don't think these logs would actually be helpful here.

**Comment by psychon** [comment]
Wait... I re-read your original comment and you already know what I wrote:

> in ~/.config/retroarch/retroarch.cfg
> set
> video_windowed_fullscreen = "false"
> video_fullscreen = "true"

Why are you applying the above setting? This is precisely what causes the problem here.

**Comment by cuu** [comment]
ok 
I did find out that if I set 
`video_windowed_fullscreen = "true"` 
then the window of retroarch can be controlled by WM(awesome)

I just dont know why it will be un-controllable when I set to "false" , I want to control it 
So I opened this issue

I thought, WM(awesome) can control every window 

**Thanks very very much for your researching**

I am planning to use Awesome as the default WM for our product [GameShell ](https://www.clockworkpi.com/) in the next version of OS image

in the old version of our OS image ,I just set `video_windowed_fullscreen = "false"` (I dont know about this issue at that time, And I used twm as the default WM)

So now I just want to make sure everything can be controlled
