### ISSUE TITLE
ubuntu 16.04 awesome version from universe repository is extremely out of date

### ISSUE THREAD

**Issue by JohnVonNeumann** [awesomeWM/awesome#2390]
Output of `awesome --version`:

```lw@tartarus:~$ awesome --version
awesome v3.5.6 (For Those About To Rock)
 • Build: Sep  1 2015 11:28:53 for x86_64 by gcc version 5.2.1 (buildd@lgw01-18)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
```

**How to reproduce the issue:**
For Ubuntu 16.04
```
sudo apt install awesome 
```
The version will be v3.5.6
**Actual result:**

The version is v3.5.6

**Expected result:**

I would expect v4.0+ seeing as it was released December 6th, 2016

**Comment by Elv13** [comment]
Sorry, but the version of a software a distributions ships is not in our control. Ubuntu 16.04 is from April 2016 and thus 3.5.6 was a decent choice when it was released. It is an LTS release and the whole point of them is only applying bug fix releases. Awesome 3.x went to 3.5.9 so that's the highest they could (but wont) theoretically go. But the wont because packages from universe and not officially supported by Ubuntu unless there is major issues. Awesome 4.x configuration files are not compatible with Awesome 3.5.x files, so a "trivial" package update cannot be pushed into Ubuntu.

Your choices are either to update to the more recent Ubuntu 18.04 or to install a recent version of Awesome from a PPA or by creating the package yourself. We offer a `make package` option when compiling to create a .deb. You can use `apt build-dep awesome` to setup the environment.
