### ISSUE TITLE
How to change the window name ?

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#2399]
Hello,

After having launched a command, I would like to change its window name, the one that appears in the awesome task list.

I can achieve that with the bash command : 
```
xprop -name "old name" -set WM_NAME "new name"
```

How can I do that from within awesome ?

Regards

**Comment by psychon** [comment]
`c.name` is read-only, because it is supposed to be set by the client only.
An alternative would be to patch all places that fetch the window title so that they use your preferred window title instead, but that would be quite cumbersome.

Where exactly (and why) do you want to change the window title? E.g., is just changing the title as it appears in titlebars okay? tasklist?

**Comment by actionless** [comment]
after all you could just `awful.spawn` `xprop` command

**Comment by deb75** [comment]
> after all you could just `awful.spawn` `xprop` command

Right, that is what I will do. But how come you cannot do with `awesome` libraries what you can do with `xprop`  ?

Regards

**Comment by psychon** [comment]
Per ICCCM (and I guess also EWMH), the WM is not supposed to change the `WM_NAME` property of a window. Only the client creating the window should do so.
