### ISSUE TITLE
Can I use animated wallpaper?

### ISSUE THREAD

**Issue by zervankoru** [awesomeWM/awesome#2425]
I want to set animated wallpaper, can I do that?

**Comment by psychon** [comment]
Yes, but it will be awfully slow and memory-intensive.

Where do you get the animation from? A GIF? A "real" movie?

If I remember correctly, mplayer can play a movie on the root window.

**Comment by psychon** [comment]
Here is some quick hack to get an animated GIF playing:
```lua
do
    -- For set_source_pixbuf on a cairo context
    local _ = require("lgi").Gdk
end

do
    local pixbuf = require("lgi").GdkPixbuf
    local img, err = pixbuf.PixbufAnimation.new_from_file("/tmp/test.gif")
    if not img then
        print(err)
    else
        local iter = img:get_iter(nil)

        local function set_wp()
            local geom, cr = gears.wallpaper.prepare_context(screen[1])
            iter:advance(nil)
            cr:set_source_pixbuf(iter:get_pixbuf(), 0, 0)
            cr.operator = "SOURCE"
            cr:paint()
            local delay = iter:get_delay_time()
            if delay ~= -1 then
                gears.timer.start_new(delay / 1000, set_wp)
            end
        end
        set_wp()
    end
end
```

**Comment by zervankoru** [comment]
Why it will be slow? Wallpaper Engine on Windows 10 works fast. About GIF or MP4 - i am not sure, but i think, video wallpaper is faster than gif, isn't it? Why beautiful.wallpaper doen't support gif by default?

**Comment by psychon** [comment]
> Why it will be slow?

I cannot guarantee it will be slow, but it will upload each frame to the X11 server via core X11 requests (i.e. no shared memory, no caching, nothing fancy). There are definitely better ways to play a video.

Video players use lots of fancy magic to make it go fast.

> Why beautiful.wallpaper doen't support gif by default?

Because you are the first one to have asked for it in the six years that `gears.wallpaper` exists. Why would it support gif by default?

**Comment by zervankoru** [comment]
> Why would it support gif by default?
I thought GIF is something ordinary and every image library can deal with that.

**Comment by zervankoru** [comment]
> If I remember correctly, mplayer can play a movie on the root window.

Thanks! `mplayer --rootwin` rules.

**Comment by Elv13** [comment]
> I thought GIF is something ordinary and every image library can deal with that.

Dealing with it yes, but each software that deal with Gif have to implement an interface to support its animation features. Sometime its done deeper in the toolkit such as GTK and Qt. But we don't use those. It wont automatically move because your image library supports it ;).

As a matter of fact, @psychon did it https://github.com/awesomeWM/awesome/issues/1903 . But this is for widget boxes (wibox) only. The wallpaper is something done using a lower level X11 concept that was never meant to do animation.

**Comment by actionless** [comment]
mpv/mplayer are the best way to go (and they also can open gif)

**Comment by Brayden-L** [comment]
> Here is some quick hack to get an animated GIF playing:
> 
> ```lua
> do
>     -- For set_source_pixbuf on a cairo context
>     local _ = require("lgi").Gdk
> end
> 
> do
>     local pixbuf = require("lgi").GdkPixbuf
>     local img, err = pixbuf.PixbufAnimation.new_from_file("/tmp/test.gif")
>     if not img then
>         print(err)
>     else
>         local iter = img:get_iter(nil)
> 
>         local function set_wp()
>             local geom, cr = gears.wallpaper.prepare_context(screen[1])
>             iter:advance(nil)
>             cr:set_source_pixbuf(iter:get_pixbuf(), 0, 0)
>             cr.operator = "SOURCE"
>             cr:paint()
>             local delay = iter:get_delay_time()
>             if delay ~= -1 then
>                 gears.timer.start_new(delay / 1000, set_wp)
>             end
>         end
>         set_wp()
>     end
> end
> ```

This works brilliantly for gifs. For those still going through this thread, just slap this at the bottom of your rc.lua and change the path to the gif

**Comment by Elv13** [comment]
Well, the git-master version of AwesomeWM has a new wallpaper API: [awful.wallpaper](https://awesomewm.org/apidoc/popups_and_bars/awful.wallpaper.html) that doesn't require this much effort to render animations. It exposes the wallpaper as a non-interactive wibox. HOWEVER: redrawing the wallpaper like that is actually very slow and make your whole computer slower because in both version of this hack, it blocks the WM. The best way to render animation is still the proposed mpv/mplayer trick. 

Changing the "real" X11 root wallpaper often using the WM thread is like using `popen`, it works, but the people doing that end up reporting bugs saying "your WM is slow".

**Comment by actionless** [comment]
btw mpv i accidentially figured out what mpv could also open GIF animations - so by using mpv on desktop it would be the most resource-efficing ways (although i need to mention what myself can't take it for longer than several seconds if wallpaper is visible 😹 - as it really annoys some of attention/reaction parts of brain)
