### ISSUE TITLE
Lags when typing in the menu bar.

### ISSUE THREAD

**Issue by ChoppinBlockParty** [awesomeWM/awesome#2427]
awesome v4.2-473-g7020a97 (Human after all)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.0

Opening menu bar and typing produce huge lags (like 1-3s after each key stroke). I have used awesome 3.5.2 the were no delays everything was instantaneous.

**Comment by Elv13** [comment]
What's your hardware? Do you have an SSD, a laptop hard drive, flash memory or a desktop hard drive?

**Comment by ChoppinBlockParty** [comment]
I have awesome 4 on the same laptop I had awesome 3.5 installed, it has SSD.

**Comment by Elv13** [comment]
> I have awesome 4 on the same laptop I had awesome 3.5 installed

I am not arguing it isn't a bug. v3.5 and v4.x are a lot more different than they look. Many code paths have been optimized for some use case and apparently in your case that caused a regression. For most people it is generally faster, but not for you, we need to find why. Hardware is a good place to start, that's all.

What was the Lua version used by your v3.5 install? If --version doesn't say it, you can use `ldd` on the awesome binary.

**Comment by ChoppinBlockParty** [comment]
@Elv13 I totally agree that the hardware type is a good start to investigate the issue. With my last comment I only mentioned again that it is the same laptop I used awesome 3.5 at. 

awesome v3.5.6 (For Those About To Rock)
 • Build: Sep  1 2015 11:28:53 for x86_64 by gcc version 5.2.1 (buildd@lgw01-18)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

**Comment by Elv13** [comment]
Some possibilities:

 * Awesome 4.x finds wayyy mode .desktop (maybe there is a symlink loop?) and has hard time to filter them
 * Somehow it's the different Lua versions, but I don't think so
 * Maybe it hits the disk for icons everytime to write something and before it just gave up earlier
 * It might have something to do with your "too many open file" issue.

Assuming you have 3.5.6 because you have Ubuntu 16.04, have you tried in 18.04? Maybe a dependency is the problem and it's since been fixed?

You can try to play with Xephyr and `strace` to see if the number of stat **after each keypress** is dubious/repetitive. Many `stat`/`open` are expected when first showing the menu, but only a few when using it. Looking at the awesome logs might also give a clue.

**Comment by ChoppinBlockParty** [comment]
Close, please.
