### ISSUE TITLE
Hotkey popup blocks input once after hiding through click

### ISSUE THREAD

**Issue by PeterNerlich** [awesomeWM/awesome#2434]
Output of `awesome --version`:

    awesome v4.2 (Human after all)
     • Compiled against Lua 5.3.4 (running with Lua 5.3)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.5
     • LGI version: 0.9.2

**How to reproduce the issue:**

Load any awesome configuration using the default hotkeys popup, show it with the assigned keybinding and click on the popup to hide it.

**Actual result:**

Input fields, editors etc. do not immediately receive focus, only upon the first keypress after hiding the popup. This keypresses is not propagated through to the client.

**Expected result:**

Hiding the popup through clicking should show the same behaviour as hiding it by a keypress does.

**Comment by psychon** [comment]
From a quick look in the code, this is what happens when the popup is hidden by a keypress (`lib/awful/hotkeys_popup/widget.lua` around line 530):
```
awful.keygrabber.stop()
help_wibox:hide()
```
This is the code for hiding it on button presses (dunno why it is not hidden when the middle button is pressed; perhaps this should just connect to `button::press` on the wibox instead?)
(Line 452)
```
mywibox:buttons(gtable.join(
    awful.button({ }, 1, function () mywibox.visible = false end),
    awful.button({ }, 3, function () mywibox.visible = false end)
))
```
So, a mouse button obviously just hides the wibox, but does not stop the keygrabber.
