### ISSUE TITLE
Port Awesome

### ISSUE THREAD

**Issue by jk121960** [awesomeWM/awesome#2453]
Hi and thanks, I love Awesome I have been using it for several years, I might have to migrate to IMAC for work purposes, and I would loathe leaving Awesome behind or using one of the "half attempts" at tiling I have seen, has anyone attempted a port to IMAC. Thanks for any help

**Comment by jk121960** [comment]
Thanks, I am sure I would be using mostly MAC based apps. Oh the pain!, The indiginity!, LOL thanks again though

**Comment by Elv13** [comment]
@jk121960 If you want Awesome on macOS, you will have to port it yourself. If you open this issue as-in "please port Awesome so I can use it", then it wont happen: ever. We have an extensive backlog with years worth of stuff including getting to wayland and fix all the bug and all the features requests. If you want to start a port and get things running, this is welcome and given we will soon already support 2 backends because of wayland, a third one that passes the tests is very much possible.

Also, is it macOS (also known as Mac OS X), not MAC. MAC (all capital letters) is a network thing.

**Comment by jk121960** [comment]
Thanks, I would have to learn a lot more about MAC but it is interesting and apparently may be necessary. It's MAC OS precisely, it would be an iMac workstation. If my lingo is a bit off, it's because this is uncharted territory, I have always been with Linux, but I am going to work for a large corporation and they are always into standardization. And yup, I was aware of the whole Wayland business, that in general has been a long and circuitous path. But hey thanks for the responses, I couldn't have asked for more, that was quick. :)

**Comment by actionless** [comment]
if you want awesome on your imac just install linux or bsd there

**Comment by jk121960** [comment]
Thanks but as indicated above it is not a choice otherwise I would just stay Linux, thanks
