### ISSUE TITLE
Systray icons in Lxpanel not showing

### ISSUE THREAD

**Issue by Maldus512** [awesomeWM/awesome#2457]
Output of `awesome --version`:
awesome v4.2 (Human after all)
     • Compiled against Lua 5.3.4 (running with Lua 5.3)
     • D-Bus support: ✔
     • execinfo support: ✔
     • xcb-randr version: 1.5
     • LGI version: 0.9.2

**How to reproduce the issue:**
- Run awesome and lxpanel; lxpanel should have the systray added in its applets
- Run a system daemon (nm-applet).

**Actual result:**
Systray icons either don't show or flicker in and out of view. They are actually present and clickable (in the image, it should appear in the bottom right corner of the option menu that popped up).

**Expected result:**
Systray icons correctly showing.

![2018-11-01-094438_1920x1080_scr
ot](https://user-images.githubusercontent.com/14563868/47841825-2be74600-ddbb-11e8-9df0-6850592928f7.png)

**Comment by psychon** [comment]
Do I understand this correctly that `lxpanel` has its own systray area and this is not awesome's systray area?
Did you remove the systray widget from your `rc.lua`?

**Comment by Maldus512** [comment]
Yes, you are correct. I removed the wibar entirely.
I am transitioning from an openbox desktop and I'm trying to maintain all the configuration that is possible/reasonable to keep.

**Comment by actionless** [comment]
1) double-check what there is nothing in your config calling `systray` function

2) check if the same behavior is preserved when running awesome with `--no-argb` flag

**Comment by Maldus512** [comment]
Confirmed. Just to be sure, those are my rc.lua and .xinitrc files. I launch awesome from my login shell with startx.

[awesomerc.zip](https://github.com/awesomeWM/awesome/files/2539186/awesomerc.zip)
[rc.zip](https://github.com/awesomeWM/awesome/files/2539185/rc.zip)

**Comment by Maldus512** [comment]
It might be; I have gtk 3.24 . The same lxpanel works without issues on Openbox however. Is there anything I can do to provide more information on the matter?

**Comment by actionless** [comment]
1) is the problem happens only with GTK+ 3 apps?

2) can you reproduce it after downgrading gtk as described in the linked ticket?

**Comment by Maldus512** [comment]
1. The only apps I've tested it with are nm-applet, ibus-anthy and a custom python (WxWidgets) program. The latter doesn't rely on GTK, so it apparently not.

2. I'm afraid not, I'm on Arch Linux and downgrading packages isn't easy. If that's the issue I'll just wait the next gtk release. I kinda doubt that's the case though; the quoted issue refers to the wibar systray icons, and they work for me, while the same lxpanel has no problems on openbox.

**Comment by psychon** [comment]
Sigh. This is another case of an application fighting against the window manager. However, this time there is not actually any fight going on! You might want to look at `top` and see that `lxpanel` has high CPU usage.
What happens is this:
- lxpanel requests a position from the window manager
- awesome assigns a slightly different window position (depending on how you count, actually it assigns exactly the requested position...)
- lxpanel reacts by requesting some other position again
- awesome keeps doing as asked
- lxpanel keeps asking

And for some reason, each "round", lxpanel hides and shows the tray icons again. This is the flickering that you see.

Via `xtrace`, I can see that an endless stream of "stuff" happens. Each round has this stuff:
- generated ConfigureNotify is received (this is awesome saying "no!")
- some drawing stuff happens
- lxpanel changes the background of systray icons a bit (ParentRelative, then None)
- lxpanel hides (=unmaps) various windows
- Some more background changes
- Some more drawing
- windows are made visible (=mapped)
- lxpanel tries to position its main window (in my case it does x=0, y=742)
- more drawing
- generated ConfigureNotify is received (with x=1, y=743, border-width=1)

I took a quick look at lxpanel's source code... and I don't really understand this. There seems a couple of `size_allocate` implementations that call into `gtk_window_move` or `gdk_window_move_resize`. I don't think that this should be done in `size_allocate` implementations.

(Uhhh, some of this code actually forces the systray icons to do a repaint (`gdk_window_clear`)...)

If you want some patch for lxpanel to test, try this one. It gets rid of one of the most blatant cases of not following ICCCM...
```diff
diff --git a/src/panel.c b/src/panel.c
index 38f5a49..fa59593 100644
--- a/src/panel.c
+++ b/src/panel.c
@@ -324,6 +324,7 @@ static void lxpanel_size_allocate(GtkWidget *widget, GtkAllocation *a)
     p->ax = rect.x;
     p->ay = rect.y;
 
+    if (0)
     if (rect.width != p->aw || rect.height != p->ah || x != p->ax || y != p->ay)
     {
         p->aw = rect.width;
```
I will close this under the assumption that the bug is in lxpanel.

**Comment by Maldus512** [comment]
> wxgtk
My bad, I was convinced they were two separated things

>   I'm afraid not, I'm on Arch Linux and downgrading packages isn't easy.
I stand by my words. I had already tried by manually downloading gtk3-3.22 and using `pacman -U`,  which results in 
``` 
error: failed to prepare transaction (could not satisfy dependencies)
:: installing gtk3 (3.22.20-1) breaks dependency 'gtk3-print-backends' required by gnome-settings-daemon
```

I did not know about the downgrade tool, but when trying to downgrade gtk3 the output is always the same. Additionally, if I try to downgrade `gt3-print-backends` it conflicts with gtk3, prompting me to remove it; obviously I can't remove gtk3 because ~30 other packages depend on it.

**Comment by psychon** [comment]
Oh, one more quick idea: Set the border width of lxpanel to 0 (in awesome). That might make things works since the `if` that I found above does not trigger any more.

**Comment by actionless** [comment]
you can downgrade two packages at once as `pacman -U ./path/to/pkg1 ./path/to/pkg2` to avoid the conflict but rather first try one of psychon's ideas

**Comment by Maldus512** [comment]
> Oh, one more quick idea: Set the border width of lxpanel to 0 (in awesome). That might make things works since the if that I found above does not trigger any more.

This seems to have worked! Also, it fixed the desktop pager having problems as well (I was going to open an issue about it after the systray).

> If you want some patch for lxpanel to test, try this one. It gets rid of one of the most blatant cases of not following ICCCM...

Where did you find the source code for Lxpanel? On Github I only found a Raspberry Pi version... Maybe I should open an issue there too

**Comment by Maldus512** [comment]
https://sourceforge.net/p/lxde/bugs/915/
