### ISSUE TITLE
Hotkeys not work on RU layout

### ISSUE THREAD

**Issue by Ladone** [awesomeWM/awesome#2495]
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**When I change keyboard layout on Russian, my hotkeys not working.** How I can fix this?

**Comment by psychon** [comment]
Possible duplicates: #1389, #1774, #2487

**Comment by Ladone** [comment]
I read this, and I'm have question. I need each hotkey remap?

**Comment by actionless** [comment]
also, how exactly are you defining your layout, ie what is your xkb config section or which args do you pass to setxkbmap?

**Comment by Ladone** [comment]
I change keyboard layout to russian layout, and use default hotkeys in program ctrl+s, ctrl+c, ctrl+v, e.t.c... And this hotkeys not working until I'm not change keyboard layout to engliesh layout

**Comment by Elv13** [comment]
You can use keycodes. This will allow to have the same keybindings for both US and RU layouts. Otherwise, yeah, I mean, if you remap "z" to be in the topleft instead of bottomright, you assume Awesome keybindings for "z" will also be in the topleft. If you set a keybinding on a key that doesn't exist in your current mapping, I am not sure it is a bug if it doesn't work.

Layout independent keybindings are supported, so I guess we can close this?

**Comment by actionless** [comment]
but for me hotkeys are working normally so that's why i was wondering how he was setting the layouts
