### ISSUE TITLE
[Feature Request] naughty icon from http or new remote_icon property. 

### ISSUE THREAD

**Issue by demonbob** [awesomeWM/awesome#2599]
Output of `awesome --version`:
```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

I spent last night building a widget for playerctrl, and the track artwork comes across as an http url, it would be nice if the icon property of naughty notify supported http|https urls. Otherwise a new property of remote_icon could be added for the support.

**Comment by psychon** [comment]
Assuming you have `gvfs-backends` installed, this is how you can download something from the internet and write it to a file. Error handling and making this asynchronous so that it does not block the whole WM is left as an exercise for the reader.
```lua
local gio = require("lgi").Gio
local input = gio.File.new_for_uri("http://gnome.org"):read()
local output = io.open("/tmp/icon.png", "w")
local size = 42
while size ~= 0 do
    local data = s:read_bytes(1024)
    out:write(data:get_data())
    size = data:get_size()
end
out:close()
```
If you do not have `gvfs-backends` installed, I don't think Gio can download stuff over HTTP.

Does this help you enough to implement what you want yourself?

**Comment by Sorky** [comment]
This is something I did for getting an icon - Would be interesting to have it critiqued...
```
	local function get_icon()
		awful.spawn.easy_async_with_shell( "wget -q -c " .. icon .. " -P " .. icon_path .. icon,
			function( stdout, stderr, exitreason, exitcode )
				if gears.filesystem.file_readable( icon_path .. icon ) then
					refresh()
				end
			end )
	end
```

**Comment by Sorky** [comment]
> [Feature Request] naughty **icon from http** or new remote_icon property

Forgive me for asking, but how is my previous comment off-topic? It's a function to get an icon from the web

**Comment by Elv13** [comment]
Kind of handled by https://github.com/awesomeWM/awesome/pull/2541 since it provides both the possibility to use a custom icon widget and also exposes the ability to replace the icons for existing notification without messing with the DBus notification update capability.

Note that this pull request is for Awesome v4.4 and will not be part of the next Awesome release (v4.3)

**Comment by psychon** [comment]
Here is some even better code. It it asynchronous, has error handling, most likely it will not crash your window manager, and it does not create a temporary file. The downside is that it requires a git version of awesome (something that already has `awesome.pixbuf_to_surface` ).
```lua
local protected_call = require("gears.protected_call")
local lgi = require("lgi")
local GLib = lgi.GLib
local Gio = lgi.Gio
local cairo = lgi.cairo
local GdkPixbuf = lgi.GdkPixbuf

local function do_async_load_image(uri, callback)
    local input, err = Gio.File.new_for_uri(uri):async_read()
    if err then
        callback(nil, tostring(err))
        return
    end
    local pixbuf, err = GdkPixbuf.Pixbuf.async_new_from_stream(input)
    if err then
        callback(nil, tostring(err))
        return
    end

    local surface = cairo.Surface(awesome.pixbuf_to_surface(pixbuf._native), true)
    callback(surface)
end
local function async_load_image(uri, callback)
    Gio.Async.start(protected_call.call)(do_async_load_image, uri, callback)
end

-- All of the above is intended to be just copied 1:1 to your config. The below
-- is to be replaced with your own code. Note that this requires at least
-- awesome v4.2-236-gc5badcbe3, because this uses awesome.pixbuf_to_surface.

local function my_callback(surface, err)
    if err then
        print("Error occurred:", err)
    end
    if surface then
        surface:write_to_png("/tmp/out.png")
        print("Got surface")
    end
end

async_load_image("http://www.gnome.org", my_callback)
async_load_image("https://awesomewm.org/images/awesome-logo.svg", my_callback)
```
(And yes, I know that this will not work with Lua 5.1. Replace `Gio.Async.start(protected_call.call)(do_async_load_image, uri, callback)` with `Gio.Async.start(do_async_load_image)(uri, callback)`. Any Lua errors in this piece of crash will be fatal and AwesomeWM will exit.)

**Comment by actionless** [comment]
1) i think it's using only gdk-pixbuf2, not gtk

2) why should gtk talk to WM unless you created a window itself?

**Comment by Elv13** [comment]
> i think it's using only gdk-pixbuf2, not gtk

For this example, you are correct. I was referring to the more advanced icon APIs that are there. Those partially fulfill @demonbob needs but pull GTK.

> why should gtk talk to WM unless you created a window itself?

Because they never stated it would never do it (for example, in its internal initialization). GTK can deadlock Awesome and the fact that it doesn't in this case is an implementation detail.

**Comment by actionless** [comment]
i don't think i am getting the second point

**Comment by Elv13** [comment]
If you did enough C and C++ code you would learn the hard way that depending on undefined behavior is shooting one own foot.

We don't distribute Awesome, the distro do that. If they upgrade to a GTK version that crashes Awesome (yet again), then all AwesomeWM users on that distro will be affected (and a large amount lost forever). It's one thing when it happens because GTK dev only test on the latest Git version of Gnome shell. It's another thing when it happens because we abused our luck with that is, and what is not, safe to use in the GTK API.

**Comment by actionless** [comment]
despite from being documented or not i can't understand how it can do such stuff without running its main loop

and what exactly are you trying to find in their docs?

**Comment by psychon** [comment]
> i think it's using only gdk-pixbuf2, not gtk

Well, no and no. It is not using Gtk, but Gdk (which is part of the same git repository as Gtk, so they are close). The C function being called is `gdk_cairo_set_source_pixbuf`. There are lots of other functions in Gdk which "morally belong into cairo" and hence LGI makes them available there (when Gdk is loaded).

> without running its main loop

Isn't "the main loop" here just `GMainLoop`? That's part of GLib and used by awesome (yes, we are not running `gtk_main()`, but that's also eventually a GLib main loop).

**Comment by actionless** [comment]
by "its" i means "gtk's", sorry for the confusion

however i think we should rather discuss if there actual benefits of using it; if so -- i think it should be doable to ask gtk devs for some explanation on that or even clarifying of the doc

**Comment by Elv13** [comment]
This is now possible by using a custom widget for the icon. The (just merged) new notification API allows this.
