### ISSUE TITLE
beautiful.tasklist_disable_icon is broken

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#2761]
This is due to the switch to `awful.widget.clienticon`. Given the widget itself doesn't know it is used in a tasklist, it's a bit tricky. One solution is to wrap the template in a function, but that's a bit ugly and quite inefficient.

**Comment by psychon** [comment]
Uhm. I think the margin around client icons is also broken. There is this code in `awful.widget.common`:
```
         if cache.ib and icon then
             cache.ib:set_image(icon)
         elseif cache.ibm then
             cache.ibm:set_margins(0)                                                                                     
         end
```
So, since the tasklist does not have an iconbox (`cache.ib == nil`), the margins will be set to zero, rendering the `icon_margin_role` widget useless.

**Comment by Perlovka** [comment]
`One solution is to wrap the template in a function, but that's a bit ugly and quite inefficient.`

Actually it is not so ugly, because if icon is disabled the widget itself remains as empty rectangle, which looks really ugly. IMO it is better to completely remove the widget from template if beautiful.tasklist_disable_icon = true

Here is my current config, works pretty well (not using _clienticon_, because it doesn't support padding):
```lua
    local tasklist_template = {
        {
            {
                {
                    id     = "text_role",
                    widget = wibox.widget.textbox,
                },
                id     = "text_margin_role",
                left   = 5,
                right  = 5,
                bottom = 2,
                widget = wibox.container.margin                 
            },                                                  
            fill_space = true,                                  
            layout     = wibox.layout.fixed.horizontal          
        },                                                      
        id     = "background_role",                                                                                            
        widget = wibox.container.background                      
    }

    if not beautiful.tasklist_disable_icon then
        table.insert(tasklist_template[1], 1,
            {
                {
                    id     = "icon_role",
                    widget = wibox.widget.imagebox,
                },
                id     = "icon_margin_role",
                top    = 5,
                left   = 5,
                widget = wibox.container.margin
            }
        )
    end
```
Enabled:
![2022-09-28_00:22:29](https://user-images.githubusercontent.com/1221112/192638149-292746b9-052b-42fa-8b13-1c1b17bd6f65.png)
Disabled:
![2022-09-28_00:25:26](https://user-images.githubusercontent.com/1221112/192638644-3098cf95-51d2-48e5-b86a-659ea15cfacf.png)

**Comment by actionless** [comment]
@Perlovka i think instead of blindly inserting it as first item in top-level array, i'd suggest to first query widget by id     = "background_role"

and IMO it would be already good enough for a PR, at least as a workaround to keep backward-compatibility with existing documentation

**Comment by Elv13** [comment]
This was fixed a while back
