### ISSUE TITLE
Haiku port? When?

### ISSUE THREAD

**Issue by letarg0** [awesomeWM/awesome#2769]
Is possible port awesome to Haiku os?

**Comment by Elv13** [comment]
Technically, Awesome is well layered and this could be done. In practice it would take months if not years. Merging another backend would also require extensive automated tests because, let's face it, this is a very, very small niche. The maintenance cost would be nearly unacceptable given the userbase size. Also, I think it would require deep changes to Haiku itself. They are not using X11 and, as far as I know, the display server is integrated much deeper and much tighter into their OS.
