### ISSUE TITLE
xrandr script should use table.unpack

### ISSUE THREAD

**Issue by robstoll** [awesomeWM/awesome#2802]
I am referring to this site: 
https://awesomewm.org/recipes/xrandr/

The promoted script at https://awesomewm.org/recipes/xrandr.lua uses `unpack` instead of `table.unpack`
IMO either fix the script or at least leave a notice on this site that one has to use `table.unpack` if one uses Lua 5.1 or higher.
otherwise it works fine :slightly_smiling_face: :+1:

**Comment by Veratil** [comment]
It should have `local unpack = unpack or table.unpack` at the top.
`unpack` = 5.1
`table.unpack` = 5.2+ (in the case Lua is not compiled with LUA_COMPAT_UNPACK or LUA_COMPAT_ALL)

**Comment by psychon** [comment]
Thanks for opening this issue. I opened https://github.com/awesomeWM/awesome-www/pull/145 with some changes to fix this use of `unpack`, but also to fix some other things that changed in the last few years.

Since that PR is in another repo, it will not automatically close this issue when/if it is merged. Thus, I will just close this right now.
