### ISSUE TITLE
Show warnings on obsolete functions?

### ISSUE THREAD

**Issue by sooqua** [awesomeWM/awesome#2852]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
Google "awesome wm check obsolete", "awesome wm loglevel", "awesome wm verbose" etc.

**Actual result:**
Can't find the answer.

**Expected result:**
Being able to check config for obsolete functions` usage with exact line numbers.

**Comment by Elv13** [comment]
Well, there is 2 things to this. First, the good news: you don't have to do anything. If a component is **deprecated**, it will warn you on stderr. Now, as far as **obsolete** components are concerned, things get messy. You need to recompile awesome with `OVERRIDE_VERSION` set to v9999 or something. This will trigger the deprecation messages for everything.

This kind of sucks. It would indeed be useful to have a runtime option for this. I plan to introduce "apilevels" before v5.0 and I will certainly make sure it can be done at runtime. Right now, nothing gets deprecated while it is still supported. Everything that was in a release is supported. A lot of code is obsoleted because I am trying to move the API toward a more unified style. I also want to tighten the integration between the various built-in components, which cause a lot of "future" deprecation.

**Comment by sooqua** [comment]
Great, thanks!
