### ISSUE TITLE
awful.spawn does not move chromium-browser to specified tag

### ISSUE THREAD

**Issue by Unlimiter** [awesomeWM/awesome#2859]
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

`aweful.spawn('chromium-browser', {tag = '3'})`

**Actual result:**

Chromium spawns in active tag.

**Expected result:**

Chromium spawning in specified tag.

**Additional information:**

I've tried the `aweful.spawn` function with a lot of programs, and all of them spawned in the tags I wanted, but Chromium does not.

**Comment by Elv13** [comment]
`awful.spawn` depends on the fact a protocol called "startup notifications" is implemented correctly by the client. Chrome has its own buggy implementation and it doesn't set the XProperty we need to make this work. See `startup_id` and the `awful.spawn` documentation for some workarounds.

**Comment by Unlimiter** [comment]
@Elv13 I didn't find any workaround.

**Comment by Aire-One** [comment]
@Unlimiter you will probably find some tips on your issue on this reddit thread: https://www.reddit.com/r/awesomewm/comments/bztj1c/spotify_and_raise_or_spawn/ (Spotify uses a custom chromium implementation... Same code same bug).

Also, if you're just trying to move the Chromium client to a specific tag using rules, I suggest you to take a look at [my patch](https://github.com/awesomeWM/awesome/pull/2484) which fixed this bug. You should just past the code I wrote at the end of your rc.lua to make it work. (However, I did not ran it since some times and awesome api evolved, so it may be broken now :man_shrugging:).
