### ISSUE TITLE
Client Icons not returning value

### ISSUE THREAD

**Issue by pyrocix** [awesomeWM/awesome#2903]
Output of `awesome --version`:
awesome v4.3-491-g3340a7dc-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
Updating Awesome v4.3 (Too long) to awesome v4.3-491-g3340a7dc-dirty
I used this block of code to add an image to an imagebox to generate an icon of each clients inside the task list:

    if icon then
      ib.image = icon
    else
      ibm:set_margins(0)
    end

But after switching to git version of awesome v4.3-491-g3340a7dc-dirty, it does not work anymore. I tried fixing this using the documentation but I have no luck. Switching back to the stable version fixes the problem  but I want to stay maintain my setup for the incoming new versions of awesome. 

**Actual result:**

![actual](https://user-images.githubusercontent.com/56428807/66635046-f7257500-ec40-11e9-9651-b2a1c860dafd.png)

**Expected result:**

![expected](https://user-images.githubusercontent.com/56428807/66635017-ea088600-ec40-11e9-8fc4-c7e947db2118.png)

**Comment by psychon** [comment]
> I used this block of code

What exactly did you do with this block of code? I have some trouble understanding this, sorry. Could you provide step by step instructions on how to reproduce your issue?

**Comment by Aire-One** [comment]
I can confirm this bug.

I just stared Xephyr with my work-in-progress-custom-taglist-widget (it uses the "main" client icon as tag icon) and I had the same issue. I didn't work on this widget since a long time, so I can't say where this regression is from.

Using `gears.debug.dump` show that `client.icon` is now an "userdata". IIRC, it used to be a cairo surface before. Also, `wibox.widget.imagebox:set_image()` doesn't handle this and return `false` so obviously it failed.

---

 As a side note:

Working with `client.icon` has been a bad idea since the beginning tho. [As the documentation states](https://awesomewm.org/apidoc/core_components/client.html#icon), you (and I) shouldn't work with it.

Instead, there is the `awful.widget.clienticon` widget. Another way to work with `client.icon` is to duplicate it. I tried the code from the doc and I can attest it's working.

**Comment by psychon** [comment]
`client.icon` is a userdata since 2012: https://github.com/awesomeWM/awesome/commit/4f30dfd198cacd08df062813e705ebb687b3d9a4#diff-684a6a5de8c31bdfe035ebf48469fab4R286

It is a raw `cairo_surface_t*`. You have to explicitly ask LGI to add a Lua wrapper around that. This is the only thing that `gears.surface(c.icon)` does. As far as I know, the C code cannot (easily; in a non-hackish way) directly return a LGI wrapper object.

**Comment by psychon** [comment]
> Also, wibox.widget.imagebox:set_image() doesn't handle this and return false so obviously it failed.

Ahhh! This comes from 3295e9f33d330678384c84031c6779693e742453 / #2779. CC @worron 

Previously, `wibox.widget.wibox.set_image` always called `gears.surface.load` on its argument (this is just an alias for `gears.surface()` thanks to some metatable magic):
https://github.com/awesomeWM/awesome/blob/99e81c097affb570d144a1f9e0ea64872e242540/lib/wibox/widget/imagebox.lua#L85-L94
#2779 adds SVG support. Now this function can be called with a cairo image surface or an RSvg handle object:
https://github.com/awesomeWM/awesome/blob/master/lib/wibox/widget/imagebox.lua#L133-L158
However, it can no longer be called with raw pointers.

Can someone please test https://github.com/awesomeWM/awesome/pull/2905? I did no testing at all on it.

**Comment by Aire-One** [comment]
> `client.icon` is a userdata since 2012: [4f30dfd#diff-684a6a5de8c31bdfe035ebf48469fab4R286](https://github.com/awesomeWM/awesome/commit/4f30dfd198cacd08df062813e705ebb687b3d9a4#diff-684a6a5de8c31bdfe035ebf48469fab4R286)

Whoosh! Hm ok. Thanks for pointing this out.

**Comment by psychon** [comment]
Oh and: Every time you do `c.icon`, the C code creates a new reference to the cairo surface and effectively leaks it. The idea is that this reference is now owned by Lua and is also dropped by Lua when it no longer needs it. This is the main reason why the docs recommend not playing with `c.icon` directly.

Basically: Never do `c.icon`, always do `gears.surface(c.icon)`.

**Comment by Aire-One** [comment]
> Can someone please test #2905? I did no testing at all on it.

It does! Thanks for this quick fix.

**Comment by Aire-One** [comment]
> Oh and: Every time you do `c.icon`, the C code creates a new reference to the cairo surface and effectively leaks it. The idea is that this reference is now owned by Lua and is also dropped by Lua when it no longer needs it. This is the main reason why the docs recommend not playing with `c.icon` directly.
> 
> Basically: Never do `c.icon`, always do `gears.surface(c.icon)`.

Would it be possible to do some metatable magics here to mitigate this behavior?

I mean, I don't know how awesome use client icon in its internal but is it reasonable to expose it to the user if we can't play with it without some hacks?

**Comment by psychon** [comment]
Thanks for testing.

What do you mean with "expose it to the user"? If we just removed the icon from the documentation, would that count as not exposing it? Somehow the code in `awful` has to get to the icon, so there must be some property for it.

(Also, no it would not be possible, because that would be a breaking change and we try to avoid them.)

Oh and by the way: Thanks everyone for testing master and finding bugs.
