### ISSUE TITLE
Deleting a tag does not always refresh the taglist

### ISSUE THREAD

**Issue by jcrd** [awesomeWM/awesome#2914]
Output of `awesome --version`:
```
awesome v4.3-505-g0297bfff9-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
Add keybinding to delete tags, e.g. in the default config I made `mod+#` delete the tag by index rather than view it.
Delete tag 9. It will still be displayed in the taglist. Open a client and tag 9 will disappear.
This only occurs if the last tag is deleted.

**Actual result:**
Tag 9 is displayed in the taglist after being deleted.

**Expected result:**
Tag 9 is removed from the taglist when deleted.

**Comment by psychon** [comment]
How exactly are you deleting tags? Which code does your `mod+#` execute?

**Comment by jcrd** [comment]
The relevant keybinding code is:
```lua
for i = 1, 9 do
    table.insert(globalkeys, awful.key({ modkey }, "#" .. i + 9,
        function ()
            local screen = awful.screen.focused()
            local tag = screen.tags[i]
            if tag then
                tag:delete()
            end
        end))
end
```
Essentially, the default config with `tag:view_only()` changed to `tag:delete()`.

**Comment by psychon** [comment]
Ah, sorry, I totally forgot about `tag:delete()`. I thought there must be more magic involved.

The relevant ode in `awful.tag.object.delete` is this:
https://github.com/awesomeWM/awesome/blob/0297bfff9ad88535fd9302fdb7d9b11459d6b1b4/lib/awful/tag.lua#L404-L406
This directly changes the tag's `screen` property, bypassing `awful.tag.setproperty`. Thus, no `property::screen` signal is emitted.

Next, it changes the `activated` property. This ends up here:
https://github.com/awesomeWM/awesome/blob/0297bfff9ad88535fd9302fdb7d9b11459d6b1b4/lib/awful/widget/taglist.lua#L533-L542
However, since the screen is already `nil`, this code does now know which screen's taglist to update and does not cause an update either.

`git blame` finds (after following some minor changes) commit 1e4c14d306 as the source of this code. Previously, this did `tag.screen = nil` and then it changes the property directly, causing no signal to be emitted (well, okay, some commits before, someone *cough* broke/removed the `screen` property...).

I would guess that the following patch fixes this, but have not tested this:
```diff
diff --git a/lib/awful/tag.lua b/lib/awful/tag.lua
index 8874d69c7..df956b091 100644
--- a/lib/awful/tag.lua
+++ b/lib/awful/tag.lua
@@ -388,7 +388,7 @@ function tag.object.delete(self, fallback_tag, force)
     end
 
     -- delete the tag
-    self.data.awful_tag_properties.screen = nil
+    self.screen = nil
     self.activated = false
 
     -- Update all indexes
```
Can someone test and turn this into a pull request?

**Comment by jcrd** [comment]
Thanks for investigating this. Your fix worked so I've submitted it as pull request #2916.
