### ISSUE TITLE
awful.menu bg and border transparency not the same

### ISSUE THREAD

**Issue by xcbdz** [awesomeWM/awesome#2976]
Output of `awesome --version`:

awesome v4.3-685-gd9998dedd (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Change awful.menu's `bg_normal `and `border_color` with the same background color and transparency:

```lua
  beautiful.menu_bg_normal = '#00000066'
  beautiful.menu_border_color = '#00000066'
```

**Actual result:**

The implementation of transparency is not the same on menu_bg and menu_border_color

![20200126_140619](https://user-images.githubusercontent.com/56459896/73131450-1d332180-4046-11ea-81fe-a0fcbb576639.png)

**Expected result:**

Same transparency for both `menu_bg_normal` and `menu_border_color`

**Note:**
Having a color without any transparency works well. the only problem is if the color has transparency.

**Comment by psychon** [comment]
I took a look with Gimp's color picker:
- You wallpaper is about `#635432`
- The window border is about `#39321d`
- The window background is about `#271f13`

Assuming they all have the same actual wallpaper color (dunno how uniform this part of your wallpaper actually is), the border is... well... 57% of the background in the red component, 59% in blue and 60% in blue. The background achieves 39%, 36%, and 38%.

An alpha channel of `0x66` is 40%, so 60% should stay visible. That's about the number for the border. For the background... well, 60%*60% is 36%. That about fits the numbers above.

Which composition manage do you use? I guess it draws the window border beneath the window. At least this would be the simplest implementation to handle shaped windows correctly. Did you try using `'#00000000` as `menu_bg_normal`?

Anyway, I do not think that there is anything we can do here. I would not even say that this is a bug in your compositing manager since all of this is just so unspecified. The X11 protocol just does not support an alpha channel.

**Comment by xcbdz** [comment]
> Which composition manage do you use?

I'm using picom right now, but I can reproduce it in compton and tryone144's dual_kawase version. Also tried killing picom and the result is the menu is transparent because of `0x66` alpha but the border doesn't have the transparency.

> I guess it draws the window border beneath the window.

I guess so. I think that the border is a wibox draw beneath the menu that's why the menu_bg is darker than the border_color. Or maybe it's just my imagination.

> Did you try using #00000000 as menu_bg_normal?

Yes, the border disappeared. The border also disappeared by
```lua
 beautiful.menu_border_width = 0
```

Anyway, thanks for clarifying!

**Comment by psychon** [comment]
> but the border doesn't have the transparency.

That's basically what I mean with "X11 does not really have transparency"

>  I think that the border is a wibox draw beneath the menu 

Window borders are an X11 feature. Every window has properties "border width" and "border color". So all that AwesomeWM does here is to set these properties to the values you provide.

> Yes, the border disappeared.

Uhm... My suggestion was `menu_bg_normal`, not `menu_border_color`. Did the border really disappear just because you set the background color (not the border color!) to something else? If so, that would be a new bug and also quite a weird bug.

**Comment by psychon** [comment]
> I'm using picom right now, 

Heh, this is the first time that I hear about that name. @yshui congrats on having a good (and google-able) compton successor.

@yshui Could you shed some light on what is going on here? You surely have more knowledge about this stuff than I do. I'd say that AwesomeWM does not do anything special here: Window with depth=32, this issue does not seem to be related to "weird visual" and... dunno, nothing special going on here (plus I think you already know what AwesomeWM is doing).

**Comment by xcbdz** [comment]
> Uhm... My suggestion was menu_bg_normal, not menu_border_color

Oops, my bad. After setting `menu_bg_normal` to `#00000000` the background is now transparent showing the wallpaper.

**Comment by psychon** [comment]
What happened? Did you find a solution?

**Comment by xcbdz** [comment]
@psychon Sadly, no, I just guess the right amount of transparency for the border to match the menu. And also, I noticed that if I apply lighter color for the border like #F2f2f299, the alpha is not applying. I think it's from the same bug.

**Comment by yshui** [comment]
we can figure out how this is rendered if @xcbdz runs apitrace on picom. right now i don't have an idea why this is happening.

@xcbdz btw do you have shadow enabled in picom?

**Comment by actionless** [comment]
@xcbdz or mb you have `frame-opacity` set in picom config?

**Comment by xcbdz** [comment]
> @xcbdz or mb you have `frame-opacity` set in picom config?

Nope, enabling it causes some artifacts and weird bug where the border of the menu is duplicated and shown on another part of the root background. I think this is an issue with picom, though.

![20200208_181124](https://user-images.githubusercontent.com/56459896/74083436-f2fa4e80-4a9e-11ea-9cdb-f5e7e87b617c.png)
