### ISSUE TITLE
Can't set opacity on notifications

### ISSUE THREAD

**Issue by pta2002** [awesomeWM/awesome#3057]
Output of `awesome --version`:

```
awesome v4.3-813-gf997009ff (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

Add a notification rule with opacity set

```
ruled.notification.connect_signal('request::rules', function()
    -- All notifications will match this rule.
    ruled.notification.append_rule {
        rule       = { },
        properties = {
            screen           = awful.screen.preferred,
            implicit_timeout = 5,
            opacity = 0.4
        }
    }
end)
```

Then send some notification.

Worth noting I have picom installed, so that should theoretically take care of the transparency (it does for terminals at least)

**Actual result:**

![image](https://user-images.githubusercontent.com/7443916/78416038-bfaaea80-761d-11ea-9a0b-f67f7fcfd5e8.png)

**Expected result:**
I can't really make the transparent notification but it shouldn't be too difficult to image what should be happening.

**Comment by colinramsay** [comment]
I think I'm having this issue, but when setting `beautiful.notification_opacity`.

**Comment by actionless** [comment]
try adding `  naughty.config.defaults.bg = "#00000000"  -- fix for doubled bg with opacity` somewhere

**Comment by actionless** [comment]
@Aire-One the fix might be a bit untrivial considering widget_templates, so i'm not sure about the decision to put it as release blocker

**Comment by Aire-One** [comment]
> @Aire-One the fix might be a bit untrivial considering widget_templates, so i'm not sure about the decision to put it as release blocker

I just thought this is a bug we want to resolve for the release :shrug:

**Comment by actionless** [comment]
ok, then we need to basically decide:
1) if we want color/opacity be defined by widget_template's `background` container
2) or by notification's wibox

right now it's defined in both, that's why setting one of them to be transparent works it around

**Comment by Aire-One** [comment]
Hm, my interpretation was that they have defined this rule from first post, then call a basic notification for testing with something like `naughty.notification { title = "Hi", timeout = 0 }`.

Actually, I just gave it a try, and it worked (including the theme var `notification_opacity`) :thinking: 

Given it's a fairly old issue, I don't hope to have updates from @pta2002 or @colinramsay, so I'll close this issue (feel free to reopen if you come by :wink:).

> ok, then we need to basically decide:
> 
>  1. if we want color/opacity be defined by widget_template's background container
>  2. or by notification's wibox
>
> right now it's defined in both, that's why setting one of them to be transparent works it around

I don't think this is the issue here. Maybe it would be better to move this topic to another issue/PR to manage this properties' declaration duplication. (My personal opinion is that it's not an issue at all, the wibox and the widget it contains are different layers, they can both have their own color/opacity)
