### ISSUE TITLE
Include font support on wibox.widget

### ISSUE THREAD

**Issue by macunha1** [awesomeWM/awesome#3105]
~This is not an issue report, therefore I just erased the template~

Hello!

I would like to have support for font configuration inside a wibox.widget, ATM I can't find a reference for Cairo ...font_face inside [the code](https://github.com/awesomeWM/awesome/blob/master/lib/wibox/init.lua) except the [textbox](https://github.com/awesomeWM/awesome/blob/master/lib/wibox/widget/textbox.lua#L333-L338) (for obvious reasons).

Further description of the use-case:
I want to include a custom font in the `wibox.widget.piechart` for [this widget/plugin](https://github.com/macunha1/awesomewm-memory-notifier).

Looking at the `piechart` code I found [this commentary](https://github.com/awesomeWM/awesome/blob/master/lib/wibox/widget/piechart.lua#L43) regarding a port from the Cairo Toy API. Maybe I should consider that?

I wrote the following snippet shortly, just as a POC (please don't kill me).

<details>
  <summary>Click here to see the content</summary>

```diff
diff --git a/lib/wibox/init.lua b/lib/wibox/init.lua
index ccbfe36a..b284c26d 100644
--- a/lib/wibox/init.lua
+++ b/lib/wibox/init.lua
@@ -65,6 +65,11 @@ function wibox:set_fg(c)
     self:emit_signal("property::fg", c)
 end
 
+function wibox:set_font(font)
+    self._drawable:set_font_face(beautiful.get_font(font))
+    self:emit_signal("property::font", font)
+end
+
 function wibox:find_widgets(x, y)
     return self._drawable:find_widgets(x, y)
 end
@@ -87,6 +92,7 @@ function wibox:to_widget()
         },
         bg                 = self.bg or beautiful.bg_normal or "#ffffff",
         fg                 = self.fg or beautiful.fg_normal or "#000000",
+        font               = self.font or beautiful.font,
         shape_border_color = self.border_color or beautiful.border_color or "#000000",
         shape_border_width = bw*2,
         shape_clip         = true,
@@ -103,7 +109,12 @@ end
 -- @method save_to_svg
 function wibox:save_to_svg(path, context)
     wibox.widget.draw_to_svg_file(
-        self:to_widget(), path, self:geometry().width, self:geometry().height, context
+        self:to_widget(),
+        path,
+        self:geometry().width,
+        self:geometry().height,
+        self.font,
+        context
     )
 end
 
@@ -324,6 +335,9 @@ local function new(args)
     ret:set_bg(args.bg or beautiful.bg_normal)
     ret:set_fg(args.fg or beautiful.fg_normal)
 
+    -- Set the default font
+    ret:set_font(args.font or beautiful.font)
+
     -- Add __tostring method to metatable.
     local mt = {}
     local orig_string = tostring(ret)
diff --git a/lib/wibox/widget/init.lua b/lib/wibox/widget/init.lua
index 683e8bc7..e2dac897 100644
--- a/lib/wibox/widget/init.lua
+++ b/lib/wibox/widget/init.lua
@@ -52,9 +52,10 @@ end
 -- @tparam number height The surface height
 -- @tparam[opt={dpi=96}] table context The context information to give to the widget.
 -- @staticfct wibox.widget.draw_to_svg_file
-function widget.draw_to_svg_file(wdg, path, width, height, context)
+function widget.draw_to_svg_file(wdg, path, width, height, font, context)
     local img = cairo.SvgSurface.create(path, width, height)
     local cr = cairo.Context(img)
+    cairo.set_font_face(cairo.select_font_face(cr, font))
     widget.draw_to_cairo_context(wdg, cr, width, height, context)
     img:finish()
 end
@@ -67,9 +68,10 @@ end
 -- @tparam[opt={dpi=96}] table context The context information to give to the widget.
 -- @return The cairo surface
 -- @staticfct wibox.widget.draw_to_image_surface
-function widget.draw_to_image_surface(wdg, width, height, format, context)
+function widget.draw_to_image_surface(wdg, width, height, format, font, context)
     local img = cairo.ImageSurface(format or cairo.Format.ARGB32, width, height)
     local cr = cairo.Context(img)
+    cairo.set_font_face(cairo.select_font_face(cr, font))
     widget.draw_to_cairo_context(wdg, cr, width, height, context)
     return img
 end
```
</details>

But I'm not sure if this works properly neither I can foresee the impact on the codebase.

Is this feasible? If so, point me in the right direction and I (hopefully) can provide some code to support this.

**Comment by psychon** [comment]
You do not want to use cairo directly for drawing text. Text is hard. The latin alphabet may work fine, but e.g. some indic languages require some font shaping stuff. This is what Pango does and this is why the textbox code has so many references to `pango`.

The `cairo_set_font_face()` function that you are calling sets the font as used by cairo. I think this value will be overwritten when using Pango to draw some text.

So, if I understand you correctly, then you'd want something like a `.font` property on a wibox and/or a drawable. To make that work, you'd then have to change the textbox code to get the font from there when drawing things.

One problem here is widget invalidation. Right now, the widget system caches the size of widgets and only redraws things when either the content or the size changed. When the font of a wibox/drawin changes, then all the textboxes would need to be invalidated.
Right now, when e.g. the DPI changes, all the caches are just thrown away.

I am not quite sure how to help you continue. Here is a quick run down on how to draw text with Pango.
One needs access to the right libraries:
https://github.com/awesomeWM/awesome/blob/814d701c81f24bcd5e55e3ee6d6d0c1e9fd53905/lib/wibox/widget/textbox.lua#L13-L16
Next, one can create a PangoContext and a PangoLayout:
https://github.com/awesomeWM/awesome/blob/814d701c81f24bcd5e55e3ee6d6d0c1e9fd53905/lib/wibox/widget/textbox.lua#L352-L353
The layout gets information about the font to use:
https://github.com/awesomeWM/awesome/blob/814d701c81f24bcd5e55e3ee6d6d0c1e9fd53905/lib/wibox/widget/textbox.lua#L334
...and also about the text to display:
https://github.com/awesomeWM/awesome/blob/814d701c81f24bcd5e55e3ee6d6d0c1e9fd53905/lib/wibox/widget/textbox.lua#L212
Then one can show the layout on a cairo context (this code actually calls `pango_cairo_show_layout`, but LGI makes this function accessible on the cairo context).
https://github.com/awesomeWM/awesome/blob/814d701c81f24bcd5e55e3ee6d6d0c1e9fd53905/lib/wibox/widget/textbox.lua#L55

One more question: Why do you want per-wibox fonts? Can't you just set the font on all the individual textboxes? Is there some problem with that?

Your question contains

> I want to include a custom font in the wibox.widget.piechart for this widget/plugin.

and the README there contains this:

> font  = theme.font, -- not supported

So I guess this is what you mean. You are right that this would require fixing `wibox.widget.piechart` to actually use Pango instead of cairo's toy API so that it uses the same font code paths. Right now, you could experiment with something like this (untested)
```lua
function memory:draw(context, cr, ...)
    local cairo = require("lgi").cairo
    cr:set_font_face(cairo.ToyFontFace.create("foo", cairo.FontSlant.NORMAL, cairo.FontWeight.NORMAL))
    self.widget:draw(context, cr, ...)
end
```
(but you cannot use `beautiful.get_font()` here since that requires a `PangoFontDescription` that cairo cannot work with)

**Comment by macunha1** [comment]
Thank you for the quick answer and for clarifying the text drawing with Cairo.

I will write some code to support the usage of custom fonts inside the wibox.widgets and hopefully come back with a PR later.

**Comment by actionless** [comment]
doesn't it make more sense to add that to `wibox.container.background` instead of embedding extra logic into wibox itself?

cc @Elv13
