### ISSUE TITLE
Unable to truly focus a client on an tag that's not selected

### ISSUE THREAD

**Issue by p-himik** [awesomeWM/awesome#3153]
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
I need to have a tag that focuses its very first client whenever the set of currently selected tags changes.
For that, I wrote this code (`t` is the tag in question):
```lua
t:connect_signal('property::selected', function (t)
    local find_client = function ()
        local clients = client.get(s, nil)
        for _, c in pairs(clients) do
            if c.sticky then
                return c
            end
            for _, v in ipairs(c:tags()) do
                if v == t then
                    return c
                end
            end
        end
    end
    local chosen_client = find_client()
    -- Cannot use `awful.layout.parameters` because it returns
    -- an empty list of clients if the tag as unselected.
    if chosen_client and chosen_client.focusable then
        chosen_client:emit_signal("request::activate", "auto_focus_centerwork_layout", {raise = false})
    end
end)
```
It works just fine - the `chosen_client` is always the correct one. And when I select the tag in question, that client is focused.
However, it doesn't seem to have focus when that tag is not selected.

Steps to reproduce:
1. Add that code to `rc.lua` for any particular tag
2. Restart Awesome
3. Open multiple windows of the same application (I used Google Chrome)
4. Focus any window but the first
5. Switch to a different tag and back - just to make sure that the code above works and that the very first window is now focused
6. Focus any window but the first again
7. Switch to a different tag
8. Run a command that should change the active window of that app in some way (I used `google-chrome http://google.com`)
9. Switch back to the tag of interest

**Actual result:**

The unfocused window has the change. It's the same window that was focused before the tag change.

**Expected result:**

The focused window has the change.

I think it's likely that it's not really an issue on the Awesome's side and that it's just how X11 works or something like that.
If that's the case, is the thing that I want to implement possible at all?

**Comment by psychon** [comment]
> and that it's just how X11 works or something like that.

Yup.

From the X11 specification, [the part for the `SetInputFocus` request](https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:SetInputFocus):

> The specified focus window must be viewable at the time of the request (or a Match error results). 

This basically means that one cannot really do what you want. (In theory, I guess one could move the window to position `-9999x-9999` and have it not visible this way, instead of having it actually unmapped. However... no thanks. If you want to make your window floating, you could try implementing that hack in Lua, though. And yes, I know that this is a messy hack.)

(Slightly unrelated: Once upon a time, the C code refused setting `client.focus` to a client that is not viewable. I do not remember why it was changed to be the way it is now.)

After re-reading the issue, I am not sure I understood you correctly. So: Can this be closed as "we cannot do anything about this, sorry"?

**Comment by p-himik** [comment]
Thanks!

> Can this be closed as "we cannot do anything about this, sorry"?

Seems like yes. One question though, out of curiosity - if an unmapped client cannot be focused, how does Awesome make it focused once it becomes visible (the step 5)? I'd appreciate a link to the particular code if it's not too hard to find.

**Comment by psychon** [comment]
Well, it does not actually focus the client (in the X11 sense). Instead, it does the same thing as when you do `client.focus = nil`. "Nothing" has the input focus. Put differently: The C code "lies" to the Lua code". ;-)

The relevant line of code is here: https://github.com/awesomeWM/awesome/blob/7a759432d3100ff6870e0b2b427e3352bf17c7cc/objects/client.c#L1651

**Comment by p-himik** [comment]
Thanks!

**Comment by p-himik** [comment]
@psychon Oh, I just realized something. Is it possible to focus a client _before_ switching a tag? If I focus the right Google Chrome window before it becomes unmapped, that should do the trick.
Of course I could just change all the places where the currently active tags are changed in my `rc.lua`. But maybe there's a signal that's triggered before `property::selected` for tags that I could use?

**Comment by psychon** [comment]
> Is it possible to focus a client before switching a tag? 

In X11? Yes. `SetInputFocus` has a `revert-to` argument [that describes what happens](https://www.x.org/releases/X11R7.6/doc/xproto/x11protocol.html#requests:SetInputFocus):

> If the focus window later becomes not viewable, the new focus window depends on the revert-to argument. If revert-to is Parent, the focus reverts to the parent (or the closest viewable ancestor) and the new revert-to value is taken to be None. If revert-to is PointerRoot or None, the focus reverts to that value. When the focus reverts, FocusIn and FocusOut events are generated, but the last-focus-change time is not affected.

(Awesome uses `Parent`, which... might be a bug, because focusing the root window seldomly does what one wants it to do)

I guess you want to trick Google Chrome into "this window had focus last", even though that is wrong. Well, sadly AwesomeWM is too smart for that. It does some stuff lazily. I.e., when you do `client.focus = c` in Lua, the focus change is not immediately sent to the X11 server, but only some time later. Due to this, I fear that you cannot do anything smart like this in Lua-land. Sorry.

**Comment by p-himik** [comment]
> In X11? Yes.

I meant in Awesome, but that information is interesting as well.

> I guess you want to trick Google Chrome into "this window had focus last", even though that is wrong.

I don't want to trick it because it would be undefined behavior, especially if we start thinking about other programs.
I want a very specific client on a tag to always have a genuine focus whenever that tag becomes selected or not.
All that to have two guarantees:
- That client is focused when I switch to the tag
- That client is the one the app treats as previously focused when I switch to a different tag

> It does some stuff lazily. I.e., when you do client.focus = c in Lua, the focus change is not immediately sent to the X11 server, but only some time later. Due to this, I fear that you cannot do anything smart like this in Lua-land. Sorry.

Ah, shame. Seems like changing focus is lazy but changing a tag is not lazy. I just tried putting the code above right before a call to `tag:view_only()`. And it didn't work. Even wrapping `tag:view_only()` in `timer.delayed_call` didn't work.

Well, at least `timer.start_new` did work. Not perfect, but I think it's still worth it.

Thank you for the discussion! I appreciate that.
