### ISSUE TITLE
tag:clients({}) doesn't remove all clients

### ISSUE THREAD

**Issue by jcrd** [awesomeWM/awesome#3167]
Output of `awesome --version`:
```
awesome devel (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.1.0-beta3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. Add to global keybindings in default config:
```lua
awful.key({ modkey }, "y", function ()
    local t = awful.screen.focused().tags
    t[2]:clients(t[1]:clients())
    t[1]:clients({})
end)
```
2. Open two clients on tag 1.
3. View tag 2.
4. Press `modkey + y`.

**Actual result:**

The client opened second is still tagged with tag 1.

**Expected result:**

Tag 1 should be empty.

**Comment by psychon** [comment]
Random guess: The code iterates over all clients of a tag here: https://github.com/awesomeWM/awesome/blob/97c3849ae7106e70a25a0ca58a81507ba0e8184d/objects/tag.c#L476
Inside the loop, it untags clients it does not find here: https://github.com/awesomeWM/awesome/blob/97c3849ae7106e70a25a0ca58a81507ba0e8184d/objects/tag.c#L494-L495

However, the `foreach` macro is implemented with an integer variable. It first searches for the first client in `tag->clients` (index 0). After that, it "goes again" looking for the next client (index 1). However, since the first client was removed, everything in `tag->clients` is shifted down by one and the second client is thus skipped.

Thus, I wrote the following (ugly!) patch (as long as something was untagged, go through the whole table again) and it seems to fix the issue. Now we just need some magic way to make this less ugly.
```diff
diff --git a/objects/tag.c b/objects/tag.c
index 1b1a13576..ec8d1010c 100644
--- a/objects/tag.c
+++ b/objects/tag.c
@@ -472,7 +472,9 @@ luaA_tag_clients(lua_State *L)
 
     if(lua_gettop(L) == 2)
     {
+        bool untagged_something;
         luaA_checktable(L, 2);
+        do { untagged_something = false;
         foreach(c, tag->clients)
         {
             /* Only untag if we aren't going to add this tag again */
@@ -492,8 +494,12 @@ luaA_tag_clients(lua_State *L)
                 break;
             }
             if(!found)
+            {
                 untag_client(*c, tag);
+                untagged_something = true;
+            }
         }
+        }while (untagged_something);
         lua_pushnil(L);
         while(lua_next(L, 2))
         {
```

**Comment by Elv13** [comment]
@jcrd Please test the PR linked above. I both fixed the bug and made a new API to simplify removing all clients. Please comment if you need some other API options to make your use case work.
