### ISSUE TITLE
Terminal windows blank (never redraw) after laptop suspend resume

### ISSUE THREAD

**Issue by hari-rangarajan** [awesomeWM/awesome#317]
Terminal windows and some other apps just show a blank window after a suspend or hibernating the PC. Java apps seem to be the most common offenders but almost all terminals(termite, gnome-terminal, mate-terminal)  I have tried show the same problem.

**Comment by psychon** [comment]
* Which awesome version?
* Do you run a composite manager (compton, compiz, xcompmgr, ...)?
* Does this only happen for apps that were visible before the suspend or also new ones of "these kind"?
* Does running awesome with the `--no-argb` command line argument make this issue go away?

I don't think that this is an issue in awesome, because a window manager only decides about the position and size of windows, it is not involved in the actual drawing of windows.

**Comment by ClintLiddick** [comment]
I have the same issue, where no text is rendered in a terminal (rxvt-unicode) or in the awesome bar itself after __some__ resumes, not always (I'm not sure if it happens for all apps, but relatedly Google Chrome freezes after resume as well). Happens for existing apps and new apps. No composition manager.

awesome v3.5.6 (For Those About To Rock)
 • Build: Jun  5 2015 06:28:50 for x86_64 by gcc version 4.9.2 (root@minjo)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

Debian Stretch/Testing
Lenovo ThinkPad X1-Carbon (3rd gen)

I will try `--no-argb` later. If you don't believe it is awesome, do you have a thought where the problem might lay?

**Comment by hari-rangarajan** [comment]
Ubuntu mate 15.04
awesome v3.5.6 (For Those About To Rock)
 • Build: Jan 14 2015 20:57:05 for x86_64 by gcc version 4.9.2 (buildd@lgw01-23)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔

No composition manager either.

It happens only with terminal windows for me. The problem seems to be on and off; will have to see if there is a clearer pattern.

I can try getting any debugs if that would help.

**Comment by ClintLiddick** [comment]
Additionally, I've noticed that opening google-chrome will cause the text to reappear.

**Comment by hari-rangarajan** [comment]
I noticed a client redraw() function in earlier versions of awesome wm. Would that force the client to redraw itself? Was the API removed for some reason?

**Comment by psychon** [comment]
`c:redraw()` used to unmap the client and map it again. For windows with double buffering, this doesn't do anything at all and most "normal" windows do their own double buffering anyway (they draw to a Pixmap and just copy from the Pixmap to the window when needed, I think (or use OpenGL and some other double buffering mechanism)). So `c:redraw()` was removed because it's not useful (I guess, I don't actually know for sure).

This sounds more like a bug in the X11 server / the video driver used. All the bugs here which do not go away with `--no-argb` should also be visible in other WMs (at least I wouldn't know a reason why not).

**Comment by hari-rangarajan** [comment]
Other window managers don't have any trouble here. It seems to be specific to Awesome WM :(.

**Comment by troglobit** [comment]
Seems to work much better with `--no-argb`, thanks! :smiley: 

Had all sorts of problems, from Emacs buffer not updating with mouse-wheel scrolling, vanishing text in GNOME apps when resuming: terminal, nautilus, etc.

**Comment by psychon** [comment]
@troglobit Which video driver? Intel? Nvidia binary blob? Neaveau?....

**Comment by troglobit** [comment]
@psychon Intel on Ubuntu 16.04, cheers

**Comment by psychon** [comment]
Anything fixed by `--no-argb` is a video driver bug. Thus closing.
