### ISSUE TITLE
tasklist_disable_icon not working in the git version

### ISSUE THREAD

**Issue by goduck777** [awesomeWM/awesome#3178]
Output of `awesome --version`:

```
awesome v4.3-875-g46a9a7b9-dirty (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.0
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

Set theme.tasklist_disable_icon=true in theme.lua.

**Actual result:**

The icon still shows up in the tasklist.

**Expected result:**

This option is not working in the latest git version. I found that I need to set a widget_template in defining my tasklist to do it, but it is more difficult than before. Is it the plan to deprecate this option?

**Comment by Elv13** [comment]
You can mitigate that using a custom `widget_template` in your tasklist.

But yeah, this regressed when we switched to resizable icons. I guess the fix is blocked on https://github.com/awesomeWM/awesome/pull/2244 . I should *really really* go back and finish that monster. tl;dr, it's hard to have `if` in declarative. We have stuff like `onlyonscreen` containers and similar for specific case, but no generic framework to create more.

**Comment by goduck777** [comment]
How about changing the default template like this
```
local tasklist_disable_icon = args.tasklist_disable_icon or theme.tasklist_disable_icon or false
if tasklist_disable_icon then
        table.remove(default_template[1][1],1)
end
```

**Comment by Elv13** [comment]
> How about changing the default template like this

This is very fragile. I would rather have a robust framework than doing this. I will give a shot to resurrect the old conditional container PR. Anyway, this bug is trivial to mitigate, so it's not urgent.
