### ISSUE TITLE
Why awesome uses lowercase with dots for xproperties names?

### ISSUE THREAD

**Issue by unai-ndz** [awesomeWM/awesome#3228]
Awesomewm is the only program I know to name xproperties in lower case, using dots as separators like `awful.client.property.floating = 1`.
Looking at the specs [1](https://www.x.org/releases/current/doc/xproto/x11protocol.html#Predefined_Atoms), [2](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#naming_conventions) and [3](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/XLFD/xlfd.html#fontname_syntax) what I interpret is that you can pretty much name them however you like as long as they do not contain a few reserved characters and they are unique enough. Even then all the examples use the typical uppercase separated by underscores.

All this came from `picom` using a stricter pattern to match xproperties names for the rules, just underscores and even warns if it's lowercase. Making a patch for allowing awesome naming is not hard but I'm curious about why awesome uses this naming.

**Comment by psychon** [comment]
> but I'm curious about why awesome uses this naming.

Historic accident, I guess? There was a general mechanism for "client objects can get extra properties" since basically always. Due to this being lua, properties had names like `floating`. The xproperty mechanism was added so that "a client's floating state should survive a restart" can be implemented. Thus, the name `floating` still made sense. To avoid name conflicts, the prefix `awful.client.property.` was added. The idea for the prefix is not "this could conflict with other X11 properties", but rather with "other Lua code could also define xproperties and they could clash". I do not think there was any consideration of "other X11 clients might want to interact with these properties".

</random-guess>

**Comment by actionless** [comment]
you could set xproperties directly without awesome's prefix:

https://github.com/actionless/awesome_config/commit/23346d3b369d9b34fd65340109f91f0c5547eb2a

**Comment by unai-ndz** [comment]
> I do not think there was any consideration of "other X11 clients might want to interact with these properties".

Then i think we should reevaluate this. Some properties are useful for other clients. And a [search](https://github.com/search?l=&p=5&q=floating+extension%3A.conf+filename%3Apicom.conf&ref=advsearch&type=Code) shows that a few window managers set properties like `_IS_FLOATING`, `I3_FLOATING_WINDOW`, `_XMONAD_TAGS`, etc. I don't know about my interpretation of the spec but if everyone else is setting them like that I think awesome should do too. After a quick look changing this seems easy enough, besides having to set both old and new properties to avoid breaking changes.

I'm gonna go with actionless approach for now but if there is agreement I could make  a PR.

**Comment by actionless** [comment]
either show a spec which says that what awesome currently does -- have incorrect characters, or close the issue please

**Comment by unai-ndz** [comment]
Fair enough
