### ISSUE TITLE
Chromium freezes at fullscreen or at opening the second window

### ISSUE THREAD

**Issue by pemakhov** [awesomeWM/awesome#3247]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Toggle fullscreen or open a new window in chromium. Also make fullscreen youtube video.

**Actual result:**

The image in the browser is frozen. If I scroll a webpage or change a tab, nothing happens. If I toggle fullscreen or switch layout, the image updates but remains dead. Titles in the taskbar update normally (at switching between tabs), also window borders highlight normally at hovering over the window.

**Expected result:**

Several chromium windows or fullscreen window work normally.

**Comment by psychon** [comment]
Are you using a composite manager (e.g. `xcompmgr` or `picom`)? Does killing that composite manager make things work? Does running AwesomeWM with `--no-argb` make things work? (Sorry, I cannot easily say how to start awesome with an extra command line argument. It depends on how you start AwesomeWM)

In X11, the window manager only places windows, but it is not involved in drawing the windows' contents. Hence I suspect a problem elsewhere.

**Comment by pemakhov** [comment]
Thank you for your answer. I don't use any composite manager.
Unfortunately, I didn't manage to run awesome with `--no-argb` flag. After a brief surfing the internet, I still can't imagine how can I do it in Ubuntu.

**Comment by ShayAgros** [comment]
If you run on a physical machine (and not ssh/vnc to it ) you can run `awesome` with different arguments on a different tty.

* On your machine press `Alt + Ctrl + F#` (where # can be any number between 1-9). The screen should change eventually to a black screen with a terminal. 
* Choose *one* of these black screens
* Enter your username and password in to log in
* After logging in run ``startx `which awesome` --no-argb``. This should start an awesome instance on this tty. You can test Chrome on this one. *Note* That Chrome should probably be closed on your original awesome instance because some applications don't like to be launched to two different ttys and they would fail to start
* When you're done log-out of awesome (`modkey + Shift + q` key binding by default)
* To return to your original tty just keep looking for `Alt + Ctrl + F#` combination which brings you back to your original awesome instance (the graphical interface launched after boot is started on one of the ttys, usually number 2 or 7 but it can vary)

**Comment by pemakhov** [comment]
@ShayAgros thank you for your instructions. 

With `--no-argb` my problem disappears. Does it mean that I have some kind of composer installed? I checked twice even though I don't remember installing them.

**Comment by psychon** [comment]
Anything that is fixed by running with `--no-argb` is a Xorg bug (likely in your video driver, whichever that is). If you are not using a compositing manager, then there should be no downsides in using `--no-argb` (and the upside is usually "makes the X11 server behave sanely").

**Comment by pemakhov** [comment]
Eventually, I've created a custom xsession where I run awesome with `--no-argb` option and for now, I don't experience any problems. Thank you very much for your help.

**Comment by xinhaoyuan** [comment]
Also you can try disabling chrome hardware acceleration - sometimes that helps.
