### ISSUE TITLE
Error: wibox.widget.graph: attempt to perform arithmetic on field 'border_width' (a nil value)

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#3333]
```
error while running function!
stack traceback:
	/home/user/.config/awesome/vicious/init.lua:101: in function 'update_value'
	/home/user/.config/awesome/vicious/init.lua:142: in function 'update'
	/home/user/.config/awesome/vicious/init.lua:220: in function 'update'
	/home/user/.config/awesome/vicious/init.lua:195: in function 'regregister'
	/home/user/.config/awesome/vicious/init.lua:224: in function 'register'
	/home/user/.config/awesome/rc.lua:538: in function 'my_vicious_register'
	/home/user/.config/awesome/rc.lua:618: in main chunk
error: /usr/share/awesome/lib/wibox/widget/graph.lua:462: attempt to perform arithmetic on field 'border_width' (a nil value)
```

Output of `awesome --version`:

```
awesome v4.3-992-gfda950d18 (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

Regression in c48e138b0: https://github.com/awesomeWM/awesome/commit/c48e138b01f54dbbdcf0bfa59fb86c7bbec94b72#diff-a7fbbb267f5d802c8978befe19471ea94047d665e04c210cf2daf710d4860756R308

**Comment by Elv13** [comment]
Fixed by https://github.com/awesomeWM/awesome/pull/3326 (unmerged, but getting there)

**Comment by albel727** [comment]
I can split out the bugfixing code out of #3326, i.e. all up to `Avoid incremental transform shifting during graph bar rendering` and cherry-pick `Fix border_color/border_width bugs in graph widget` on top of it, and make a pull request of it. 

I think that would make a lot of sense, because the rest of #3326 is mostly `new functionality` territory, and it's getting big and out of scope. If there's a bug in there, one then could just revert it all, without touching the essential bugfixing part.

**Comment by actionless** [comment]
https://github.com/awesomeWM/awesome/pull/3326 was finally merged

**Comment by blueyed** [comment]
Note / just for reference: with https://github.com/awesomeWM/awesome/pull/3326 (and https://github.com/albel727/awesome/commit/0aa63249a18641251a1bf77423739164f0eab39f squashed therein) it is required now to also set the border width explicitly, which is good, but changed behavior.
