### ISSUE TITLE
typo in docs for awful.keygrabber

### ISSUE THREAD

**Issue by ckp95** [awesomeWM/awesome#3350]
https://awesomewm.org/doc/api/classes/awful.keygrabber.html

In the "Using keygrabber for modal keybindings (VI like)" section there is a code snippet which has a typo.

```lua
    root_keybingins = {
```
should be

```lua
    root_keybindings = {
```

**Comment by Aire-One** [comment]
Thank you for reporting this typo!

It was already fixed in the git version, see: https://github.com/awesomeWM/awesome/commit/7c54e1cbf2a6f568804eeb5f77ecc0759535016a

As a check, we can see the typo is not present in the git version of the API documentation: https://awesomewm.org/apidoc/core_components/awful.keygrabber.html

I'm closing this issue. Please note this kind of contribution is very welcomed, and we appreciate the effort :)
