### ISSUE TITLE
list of signals

### ISSUE THREAD

**Issue by basaran** [awesomeWM/awesome#3365]
Hello,

Is there a list of all the signals that can be used with AwesomeWM ? I couldn't find in the documentation. Thank you.

**Comment by Aire-One** [comment]
Do you want https://awesomewm.org/doc/api/libraries/awesome.html#Signals ?

If you want a complete list of all signals you can connect to, it would be harder. Each component implementing `gears.object` can define its own custom signals. They are documented for all standard classes in their API reference page. For example, in the `wibox.widget.imagebox` documentation page, there is a section "Signals" https://awesomewm.org/doc/api/classes/wibox.widget.imagebox.html#Signals. You can find here all signal you can use with an imagebox.

**Comment by basaran** [comment]
I was actually looking for the client class signals which was only providing the bare function names in the api docs. However, with your `emit_signal` tip, I was able to `grep` from the source code. Thank you very much. Closing.

![image](https://user-images.githubusercontent.com/30809170/121832043-1a66ba00-cc97-11eb-9458-5b23570411db.png)

**Comment by Aire-One** [comment]
https://awesomewm.org/doc/api/classes/client.html#Signals

It gives the signal name, description and arguments list.

(Also check the git version where we did some improvements https://awesomewm.org/apidoc/core_components/client.html#Signals)

What are you missing in the documentation?

**Comment by basaran** [comment]
I was looking here:

https://awesomewm.org/doc/api/classes/signals.html

My ctrl + f, on the client class somehow got me to the signals link on the left side. Honestly, I always end up getting lost in the API documentation but that's most likely due to my lack of understanding of the ecosystem. It's improving though, thank you for your kind help.

**Comment by Elv13** [comment]
For the client, I suggest you look at https://awesomewm.org/apidoc/core_components/client.html like @Aire-One mentions. It is *not* the same link. That's the link for the development version. One of the main change is that the signals (and pretty much everything else) is better documented. You can see the `1 signal` thing in each of the property and can "click to show more" to see their parameters. Note that most of that is auto-generated. Nearly all properties have signals.

There is no "sections" for the property signals because it would make the page way too large and most signals don't warrant an extended description or code example. It would end up being a copy-paste of the property doc and that's not very useful.
