### ISSUE TITLE
Unsetting all tags from a client doesn't re-arrange the layout

### ISSUE THREAD

**Issue by Nooo37** [awesomeWM/awesome#3398]
Output of `awesome --version`:

awesome v4.3-1066-g832483dd6 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

**How to reproduce the issue:**

- open the default config
- open a terminal and some other windows
- switch to one of the tiling layouts
- run `awesome-client "client.focus:tags {}"` in the terminal

**Actual result:**

The focused client (the terminal in which the command is run) gets unset from all tags leaving a "hole" in the tiling layout of the current screen.

**Expected result:**

The leftover clients should have gotten re-arranged accordingly so that no hole appears.

**Comment by aflorea-2k** [comment]
It's my first time playing with Awesome's C code, so bear with me.

I believe the issue can be fixed in the C declaration of `client:tags` :

https://github.com/awesomeWM/awesome/blob/260f6dbe97c37189271e6745b898bfa541c6254a/objects/client.c#L3153-L3154

My (idea for a) solution :
- Enumerate all tags of client, save them in a table
- At the end of the function, before the return, update all those tags' layouts.

Sadly, I don't know how Awesome handles layout updates, nor I am experimented with lua's C API. If someone with more experience could look at this, it'd be great :)
Also, my solution updates all tags; we could only update those that the client disappears from.

**Comment by Nooo37** [comment]
Sorry, I think this is a duplicate of #3104 as `:toggle_tag` also just calls `:tags`
