### ISSUE TITLE
wibox.widget.textclock default format is wrong in online docs

### ISSUE THREAD

**Issue by Tyilo** [awesomeWM/awesome#3415]
Output of `awesome --version`:

Not relevant

**How to reproduce the issue:**

Go to https://awesomewm.org/doc/api/classes/wibox.widget.textclock.html#wibox.widget.textclock

**Actual result:**

The default format is shown as for the `textclock` function is shown as:
```
format=" %a %b %d
```

**Expected result:**

It should show the actual default, which is:
```
format=" %a %b %d, %H:%M"
```

**Comment by Tyilo** [comment]
The docs are still wrong for the stable version, so I think it should be updated.

**Comment by Aire-One** [comment]
There are some issue with the doc for awesome stable. Since the doc is generated from the source code, and we don't provide support for the stable version, we'll not update the stable versons of the documentation.

Sorry about that, but we just don't have the manpower to support multiple versions of awesome, and we focus on the development.
We, however, look forward to fix the issues you would have with the git version of the doc. As @actionless mentioned, this particular issue have already been fixed ;)
