### ISSUE TITLE
Please add Tree Style tiling.

### ISSUE THREAD

**Issue by leier69** [awesomeWM/awesome#3420]
There has been some many forks and iterations of tree style tiling for awesome. example: https://github.com/guotsuan/awesome-treetile.

It would be really "awesome" if Awesomewm had an official one with support for borders, gaps, and resizing.

**Comment by Elv13** [comment]
Here are the patches to do it
https://github.com/awesomeWM/awesome/pull/644

Yes, they are very old, but they still work. Long story short, this PR is impossible to merge until 5.0 because it causes some noticeable behavior changes. There is a few more implementations floating around which work with 4.x. All of them have some limitation. The current AwesomeWM layout engine makes it pretty much impossible to get perfectly right.

https://github.com/xinhaoyuan/layout-machi
https://github.com/guotsuan/awesome-treetile
https://github.com/RobSis/treesome

(closing because it is a duplicate)
