### ISSUE TITLE
Screenshots: Expansion of the 'content' Interface

### ISSUE THREAD

**Issue by poisson-aerohead** [awesomeWM/awesome#3447]
I am a long time user and always wished that awesome had better screenshot support. I obviously know about client.content, as it is covered in the documentation. I spent a little time studying the source and learning to build and install release versions of Awesome and have successfully added a root.content() method and screen.content property to the API. In my rc.lua I bound everything to Super-PrntScrn for a full root window screenshot, Super-Alt-PrntScrn for the active physical screen screenshot, and Super-Control-PrntScrn for the active client window screenshot. I have verified on a two monitor setup that everything works correctly. I am now going to work on using the mouse grabber library within the lua config scripts to build a snip tool that I will bind to Super-Shift-PrntScrn.

This is so tremendously useful to me that I am probably going to go forward with running this patched version as my window manager, assuming you don't want the change, but I thought I would offer it to the upstream. I am aware that this is technically an API change and so the answer might be "no". For this reason, I did not open a pull request.

Anyway, let me know. I am happy to contribute (it actually will alleviate my need to keep my patched version up to date).

**Comment by Aire-One** [comment]
Hello

New features are very welcomed. This screenshot feature sound amazing, I can't wait to see what you did there! 

I'm not sure to understand what you mean by "API changes". Any new feature implementation is expected to alter the API in some way. What we are more concerned about are breaking changes for the end-user rc.lua (please note it doesn't means we automatically refuse such change). Otherwise, there shouldn't be any issue.

Please note we'll review your PR and ask for any change we think necessary to merge it. Just go ahead and submit your PR, we'll be happy to work out the best to help you merge your patch!

**Comment by poisson-aerohead** [comment]
> New features are very welcomed. This screenshot feature sound amazing, I can't wait to see what you did there!

Great. It is a pretty straightforward change. I caught one mistake (I am new to using Cairo and I had done it wrong) but I fixed it this morning so I wanted to let Awesome run for a bit to make sure the patch is not obviously unstable. So far it looks good. I have it running with my laptop hooked up to the flat screen TV and I have been just trying to stress it a bit (opening and closing a lot of windows and taking various kinds of screenshots on each screen).

> I'm not sure to understand what you mean by "API changes". Any new feature implementation is expected to alter the API in some way. What we are more concerned about are breaking changes for the end-user rc.lua (please note it doesn't means we automatically refuse such change). Otherwise, there shouldn't be any issue.

OK I understand, I guess _everything_ is an API change in some way. I guess it just felt weird modifying a core class and core library, I normally think of Awesome mods as being in Lua. This will not break the default libraries or rc.lua. It should not break anything unless some user out there added a 'content' member to either the 'root' or 'screen' objects in their setup, which seems unlikely. Also, this change puts the documentation of root and screen out of date.

Pull request is here: #3448

**Comment by poisson-aerohead** [comment]
Hey, I tried to correct a spelling error in the message by --amend and I don't know if I put a hiccup into the PR now.

**Comment by Aire-One** [comment]
Thanks for your PR! :rocket: 

> Hey, I tried to correct a spelling error in the message by --amend and I don't know if I put a hiccup into the PR now.

Hm... It indeed seems you have some unnecessary commits in your PR. I guess you can remove the 2 first commits (and maybe the final merge?).

Regarding your --amend, I can't say if it worked. Note that you have to push it with the -f (--force) flag. Otherwise, it will not be accepted by your remote as you are altering the git history.

I'll close this issue, let's continue talking in the PR thread instead.
