### ISSUE TITLE
Possible typo in awful.popup maximum_width property

### ISSUE THREAD

**Issue by Kemystra** [awesomeWM/awesome#3459]
Output of `awesome --version`:

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
**How to reproduce the issue:**

Make an `awful.popup` in `awful.screen.connect_for_each_screen()`.
```
s.systray_window = awful.popup {
        widget = {
            {
                wibox.widget.systray {
                    screen = s,
                    visible = true,
                },
                forced_num_cols = 3,
                layout = wibox.layout.grid,
            },
        
            maximum_width = 100,
            height = 30,
            widget = wibox.container.constraint,
        },
    
        ontop = true,
        hide_on_right_click = false,
        visible = false,
        preferred_anchors = "middle",
        preferred_positions = "bottom"
    }
```
(Note the `maximum_width` property, and the `systray` widget)

**Actual result:**

The `awful.popup` got longer than its supposed to (180 pixels).
Noticed a (typo?) mistake in the docs: [awful.popup](https://awesomewm.org/doc/api/classes/awful.popup.html#awful.popup.maxmimum_width)

Instead of `maximum_width`, it wrote `maxmimum_width`. The explanation underneath are also either misleading or wrong.

**Expected result:**

The `awful.popup` should respect the `maximum_width` property, and keep its size to 100 pixels.

**Comment by Kemystra** [comment]
Alright, I think I saw my mistake. The maximum_width property is inside the `wibox.container.constraint`, not the popup itself. But even then, this means a bug inside the mentioned container.

**Comment by Aire-One** [comment]
As mentioned by @unai-ndz, the typo issue was fixed in the git version. Given you use the stable version, you'll have to mimic the typo to make this property work. 

> Alright, I think I fixed(?) my mistake. The maximum_width property is inside the `wibox.container.constraint`, not the popup itself. 

Yup, the code example you provide has this issue. The maximum_width property shouldn't be in the widget, but as a "top level property" in the popup constructor. 

> But even then, this means a bug inside the mentioned container.

I don't think so. The container you use here is the constraint container and it doesn't have a maximum_width property. It only accept width or/and forced_width. See https://awesomewm.org/doc/api/classes/wibox.container.constraint.html
