### ISSUE TITLE
vim-like bookmarks feature ?

### ISSUE THREAD

**Issue by franzhuang** [awesomeWM/awesome#3495]
Is there quickest ways to switch to a specific client?
I mean, like drop-down terminal, I can press a key or a  combination to switch to a client.
Tilix terminal's quake mode is a drop-down terminal which I like very much , however , it's a little delayed when I drop down on awesomeWM,and it's getting slower (two+ seconds) when codes are getting complicated in tilix.
I know someone assigns different tags (workspaces) to specific clients so that he can swich to specific client through specific tag.
Is there other options, I mean, vim-like bookmarks feature that allows one to go to client in fastest way.
Or if you have other tricks can do the same thing?

**Comment by RobertMueller2** [comment]
You could add an arbitrary property to a client in order to use that as a bookmark, and then iterate clients to locate. It could be a bit static but shouldn't take too long to script.

Alternatively, If you are specifically looking for quake dropdown functionality, you could use https://github.com/lcpz/lain/blob/master/util/quake.lua . Another quick alternative to locate a window might be rofi -show window.
