### ISSUE TITLE
Slow disappearance of windows [old machine]

### ISSUE THREAD

**Issue by vogu66** [awesomeWM/awesome#3548]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Close windows, make them invisible, or change desktop. As far as I can tell it is much less problematic when opening windows. It also does not happen when inverting two windows of different sizes. The graphics card usage spikes when a window disappears, as opposed to when one appears.

**Actual result:**

Very slow fading disappearance of the window, before the new result appears instantly.

**Expected result:**

As noted in the title, this is a pretty old machine, although it does have an ssd. So I'm not expecting the absolute best performance, but it does seem quite intriguing that windows disappearing is so slow while windows appearing is reasonably fast. Is there a default option which might say to the windows to fade out or something and that I could change?

I'm using Manjaro, with Wayland and picom (compton) as a compositor, the two latter may be other culprits but I don't know enough to know where to poke to get things better, I'm just using the default config. On a newer machine with the same config I've never noticed anything like that, but it has much better specs so it just may be faster at doing things in general.

**Comment by sclu1034** [comment]
> I'm using Manjaro, with Wayland

Awesome is an X11 window manager. It is not possible to run Awesome with/on Wayland.
The same goes for picom and compton, which are X11 compositors.

Unless you're running Awesome + picom inside an XWayland session ontop of a Wayland compositor, in which case bad performance wouldn't surprise me.

Please verify whether your issue appears when you run Awesome
- with a default configuration,
- without compositor
- and in a regular Xorg session (no Wayland)

If that setup runs fine, the issue is caused by one of the other components.

**Comment by vogu66** [comment]
Well, that's good to know at least, thanks a bunch.

Running with a default config comes down to removing the .config/awesome/rc.lua file, right, or there is more? I'll first try the configuration and the compositor, installing xorg would take a bit more time. Thanks again!

**Comment by vogu66** [comment]
Well, it was installed like that by default. I guess there is a reason there is no more manjaro awesome community edition.

Well, it was the compositor. The system is _much_ more snappy now. Thanks a lot!
