### ISSUE TITLE
After upgrade awesomewm, panels stop showing

### ISSUE THREAD

**Issue by jpointsman** [awesomeWM/awesome#3581]
I use the custom theme from [the-glorious](https://github.com/manilarome/the-glorious-dotfiles)
After upgrading awesomewm, all panels from this theme stop showing. They all required "layout" module

I got a system notification:
    Oops, an error happened!
    /home/user/.config/awesome/layout/init.lua:28: attempt to index a nil value (field 'top_panel')
 
Output of `awesome --version`:
awesome v4.3-1356-g9895aeb0d (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no

**Comment by Aire-One** [comment]
Hello, 

You should probably report this issue to the dotfiles author, since for now, this doesn't look like a bug or regression introduced by us. (Also, given the repo seems unmaintained, it's maybe a bad idea to continue to use these dotfiles)

Anyway, we had another issue recently about this dotfiles repository: #3563. Can you take a look at it, more specifically this comment:  https://github.com/awesomeWM/awesome/issues/3563#issuecomment-1046276438
