### ISSUE TITLE
Redraw systray icons on background color change

### ISSUE THREAD

**Issue by Darksonn** [awesomeWM/awesome#359]
New icons in the systray are given the background color `beautiful.bg_systray` when created, but if I change this value, old icons are not updated to the new color.

I realise that just changing the value doesn't notify the systray, but even creating a new systray object and recreating the wibox containing it to contain a new systray, doesn't update the icons.

How can I trigger a redraw of all systray icons?

**Comment by blueyed** [comment]
Have you tried emitting the `widget::updated` signal?

**Comment by Darksonn** [comment]
Running the below line does not update the icons in the systray:

    systray:emit_signal("widget::updated")

**Comment by psychon** [comment]
Anyone compiling from C directly, open `systray.c` and edit the function `systray_update()`. Before the call `xcb_map_window(globalconf.connection, em->win)`, add the following (line 287):

    xcb_clear_area(globalconf.connection, 1, em->win, 0, 0, 0, 0);

Congratulations, your systray now flickers every time the wibox is updated. Could someone tell me if this also means that changes to the background color of the systray are properly applied?

Do we even support changes to values in `beautiful` at run time? Lots of stuff will break, because the value is only grabbed once during startup and thus will keep using the old value.

@Darksonn Why do you need to change the color anyway?

(Oh and in case someone wants to know what that patch does: It "clears" the systray icon's window and forces a redraw. Hence the flickering.)

**Comment by Darksonn** [comment]
@psychon 

I'll try to do the change you mentioned in `systray.c` as soon as I can make awesome compile (see referenced issue just above).

As to answer the question, the reason is aesthetics related, and I have the background of the elements in the wibox alternate. However the starting color of the alternation, depends on the color (focus/nofocus) of the rightmost window in the tasklist.

**Comment by Darksonn** [comment]
@psychon I changed the line in the `systray.c` file, and the background is properly applied, perhaps we could bind some signal or boolean flag to have that function be called next time `systray_update()` is called?

Personally I'm going to keep the change in the C code until I have a better solution, I'm not experiencing any flickering.

**Comment by blueyed** [comment]
@Darksonn 
There's #402 now that should fix this.  Can you test/confirm it?

**Comment by Darksonn** [comment]
Confirmed, #402  solves the bug.

**Comment by Darksonn** [comment]
After using a build with #402 for a while, I installed dropbox on my machine. The background of the dropbox icon is _not_ updated by the changes in #402.

The dropbox icon continues to have the background it had when it was created, several other icons right beside it work fine.

**Comment by psychon** [comment]
I don't know if dropbox bundles a Qt version or uses Qt from the system, but I'm sure that that's a bug in Qt. It should be fixed with 5.6 (or 5.5? I'm not sure, but if you want, I can look it up; there was something recently).

Could you try with a fixed Qt version for dropbox and reopen if the problem persists? Thanks
