### ISSUE TITLE
"Test previous commits" got broken due to changes on github

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#3592]
```
Fetching fork
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
error: could not fetch fork
Error: Process completed with exit code 1.
```

i'm not sure if it's bug on the github side, since what we're using here is url generated by github itself, ie:

```
          git remote add fork "${{ github.event.pull_request.head.repo.git_url }}"
```

so, idk if they gonna replace it to be https or do we need to find the new way to get a https git url of the fork

**Comment by sclu1034** [comment]
Probably not a bug on their side, but I do find it a weird design choice that the Actions runner isn't at least considered authenticated for public read access. But I guess that's how it is.
If it works, the easiest solution would probably be to just use `clone_url` instead of `git_url` (see https://docs.github.com/en/rest/reference/repos#get-a-repository).
