### ISSUE TITLE
Support for XKB - changing keyboard layouts in 3.5.6

### ISSUE THREAD

**Issue by tigrisathon** [awesomeWM/awesome#360]
Hello. There has been a pull request recently, which implemented better support for different keyboard layouts and added support for non-English input in promptboxes (menubar and standard prompt): https://github.com/awesomeWM/awesome/pull/227 It has been merged to master.

I tried merging all the commits within this pull request to 3.5.6 (via git-cloning 3.5 branch from this repository and using git cherry-pick successively with all the commits within this pull request. All the commits applied succesfully, except "19137a55c3c2c80d77f7d9993292acc3784cbe35". There is a conflict:
Conflicts:
        awesomeConfig.cmake
        event.c
        keygrabber.c
        keyresolv.c
        keyresolv.h
        xkb.c

As i am new at git and at programming, i do not know, what to do. Could you please tell me, if there is a way to apply these changes to 3.5.6? Thank you.

**Comment by blueyed** [comment]
You could also try using master, which is considered to be quite stable and has a lot of improvements.

**Comment by tigrisathon** [comment]
As I know, most of the third-party widgets/addons are written for 3.5, not for currently developed branch, so there may be random bugs. It seems to me, 3.5 is preferred now.

**Comment by blueyed** [comment]
Yes, that might be the case, but in general that's not a problem.

You can just try it, and if there are problems, then go back to 3.5.x again.

Apart from that, resolving this conflict would be a good exercise for you then.. :)
E.g. the conflict in `awesomeConfig.cmake` is probably rather trivial.
You might want to start here: http://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging#Basic-Merge-Conflicts.  Also, the option `merge.conflictstyle = diff3` is generally helpful (add it with `git config --global merge.conflictstyle diff3` to your config).

Anyway, I am closing this issue, because it's no problem with awesome itself.

You might want to ask in the IRC channel (#awesome on OFTC) for further support.
