### ISSUE TITLE
Cannot map XF86PowerOff anymore on EndeavourOS

### ISSUE THREAD

**Issue by ad-on-is** [awesomeWM/awesome#3602]
Since a few days, my keymapping on `XF86PowerOff` does not work anymore. When I press it, my computer straight shuts down, instead of doing the action defined in `awful.key()`

```
OS: EndeavourOS Linux x86_64 
Host: 82B1 Lenovo Legion 5 15ARH05H 
Kernel: 5.17.1-arch1-1 
```

Am I missing something?

**Comment by Aire-One** [comment]
Hello @ad-on-is, I don't think this issue is related to Awesome WM.

I'm not familiar with EndeavousOS, but given it's Archlinux based, maybe you should check https://wiki.archlinux.org/title/Power_management#Power_management_with_systemd. I think you are interested in the config from the `/etc/systemd/logind.conf` file, and you want to switch `HandlePowerKey` to `ignore`.

Please double-check my hint with your distribution's wiki/forum, and probably also check the recent changes they did.

**Comment by ad-on-is** [comment]
> Hello @ad-on-is, I don't think this issue is related to Awesome WM.
> 
> I'm not familiar with EndeavousOS, but given it's Archlinux based, maybe you should check https://wiki.archlinux.org/title/Power_management#Power_management_with_systemd. I think you are interested in the config from the `/etc/systemd/logind.conf` file, and you want to switch `HandlePowerKey` to `ignore`.
> 
> Please double-check my hint with your distribution's wiki/forum, and probably also check the recent changes they did.

You're right. For some reason logind was grabbing that key. I did as you suggested, and it works now.
