### ISSUE TITLE
Question: licensing of rc.lua

### ISSUE THREAD

**Issue by Luexa** [awesomeWM/awesome#3613]
\<Not Legal Advice\>

Hello, I was curious about the licensing of the sample `rc.lua` file, which everyone is expected to derive their config from. AwesomeWM as a whole is GPL and most files have license headers; however, I noticed the `rc.lua` file did not. I'm sort of hoping this means the sample config is not GPL (which would mean all config derived from that would have to be GPL), but if that's true it would imply there is no specific license assigned to `rc.lua`.

Might I recommend 0BSD? It's a variant of ISC (which itself is a battle-tested equivalent to MIT) that does not have the attribution requirement and therefore is the most flexible, sublicenseable license there is for sample files like this config. From what I've read, it has advantage over CC0 due to not mentioning the ambiguous/invalid concept of public domain and messy amounts of patent law (both of which cause some groups to avoid it like the plague), advantage over Unlicense due to being more battle-tested (it's derived from ISC which itself was made by lawyers to be a simpler equivalent to MIT) and again not mentioning public domain, and advantage over WTFPL due to being an actual license and not... y'know.

Although now that I think of it, you might not have a choice in the matter considering it's using the API of a GPL library (not everywhere recognizes this sort of copyleft but still)... Oh well. I just wanted confirmation of what I had feared (config being GPL).

\</Not Legal Advice\>

**Comment by Aire-One** [comment]
Hello, 

First of all, you have to note that I'm here "just for fun", so you'll have to take my reply with a grain of salt.

According to the project's README.md (and the LICENCE file goes the same way) :

> License
> The project is licensed under GNU General Public License v2 or later. You can read it online at (v2 or v3).

Then reading https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL :

> If a library is released under the GPL (not the LGPL), does that mean that any software which uses it has to be under the GPL or a GPL-compatible license? (#IfLibraryIsGPL)
> 
> Yes, because the program actually links to the library. As such, the terms of the GPL apply to the entire combination. The software modules that link with the library may be under various GPL compatible licenses, but the work as a whole must be licensed under the GPL. 

If I understand that correctly, as long as you use any of the Awesome WM libraries, you have to use a GPL-compatible license de facto.

If you want my feelings, you can do whatever you want with your personal configuration. No one is going to chase you for your `rc.lua` licensing decision.

Btw, it's a "common knowledge" that Amazon uses (used?) awesome for the Kindle: https://awesome.naquadah.narkive.com/hrScDHec/wm-in-kindle-touch. And no one cares enough to ask them to publish their Awesome WM configuration. I think people are just happy to see that others (even big players) are using their hobby project ☺️

**Comment by Luexa** [comment]
Alright thanks for the response. I'm not super bothered anyway I guess; now that I think of it my dotfiles aren't on the open internet so I'm not exactly distributing anything -> no GPL issues.

**Comment by sclu1034** [comment]
(I'm not a lawyer)
(in the repository, the file is actually called `awesomerc.lua`, but that's the source for what's commonly referred to as "the default `rc.lua`")

> If I understand that correctly, as long as you use any of the Awesome WM libraries, you have to use a GPL-compatible license de facto.

That only holds true if you were to bundle or otherwise include that library. Most projects don't do that.
Merely writing `require("awful")` does not include the actual library in any way (neither in source nor binary form).
You have to install it some other way (as part of Awesome, usually) and have Lua's loaders figure out how to point to it. At runtime, that `require` call could actually end up pointing to a completely different implementation of the same API.
And with the Google vs Oracle case finally decided, APIs alone do fall under Fair Use, so just calling `awful.widget.taglist()` doesn't make your code a derivate just yet.

> most files have license headers; however, I noticed the `rc.lua` file did not

This is not specific to `rc.lua`.
Some C files do have a GPL header, but a lot of files in the repository don't. E.g. the entirety of `lib/`.

> I'm sort of hoping this means the sample config is not GPL (which would mean all config derived from that would have to be GPL), but if that's true it would imply there is no specific license assigned to `rc.lua`.

On GitHub (or similar hosting services) the common case is that a single LICENSE file (or similar) in the root is intended to apply to the whole project. Very few people actually add licence headers to their source files.
Therefore, if a root licence file exists one should assume that it applies to all files, _unless explicitly noted otherwise_. We do not exempt `rc.lua`, so it falls under GPL, just like the rest.

----

> And no one cares enough to ask them to publish their Awesome WM configuration

No one has to ask. You can just download it, the link is in the very post you referenced.
