### ISSUE TITLE
CI: Luacheck rules seem to have changed

### ISSUE THREAD

**Issue by sclu1034** [awesomeWM/awesome#3627]
I'm not sure when exactly it started, but Luacheck is now showing warnings for things that haven't changed in years. Mainly in two categories:

- `'not (x >= y)' can be replaced by 'x < y'`
- `used variable '_<something>' with unused hint`

Neither of those is hard to fix.

**The question is**:

1. Do we want to keep those Luacheck rules (which are usually derived from community best practices) and change our code?
2. Or do we want to disable the rules project-wide to keep the code unchanged?

Disabling the rules individually at the affected places would be a third option, but I think it would be better to keep those checks consistent across the code base.

**Comment by Aire-One** [comment]
> I have most of the PR ready, assigning to me

Hello Elv. Do you have any ETA for this PR? (Just a thought I had, because we have a new PR with this error. No pressure)

**Comment by actionless** [comment]
yeah it's breaking automerge atm

**Comment by Elv13** [comment]
I nearly finished the PR yesterday while chatting with a few of you. I know
it's taking time. Sorry. It's not just a find and replace to remove the
underscores. Those underscores are there mostly because 1: they shadow
something else or 2: they are there on purpose to mark undocumented/private
parameters. So it's rather important to properly investigate each of them
(hundreds of them).

**Comment by sclu1034** [comment]
Implemented in #3655.
