### ISSUE TITLE
When will the next release happen?

### ISSUE THREAD

**Issue by NobbZ** [awesomeWM/awesome#3644]
Output of `awesome --version`:

```
awesome 4.3 (Too long)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: [string "return require('lgi.version')"]:1: module 'lgi.version' not found:
	no field package.preload['lgi.version']
	no file './share/lua/5.2/lgi/version.lua'
	no file './lgi/version.lua'
	no file './lgi/version/init.lua'
	no file './lib/lua/5.2/lgi/version.so'
	no file './lgi/version.so'
	no file './lib/lua/5.2/loadall.so'
	no file './lib/lua/5.2/lgi.so'
	no file './lgi.so'
	no file './lib/lua/5.2/loadall.so'
```

**How to reproduce the issue:**

Look at the awesomewm.org website or the GitHub releases

**Actual result:**

Most recent release is 4.3 from ~3 years ago.

**Expected result:**

There should be a 4.4 or 5.0 release.

**Additional Information**

There are some distributions that follow a strict "released versions only" policy, and for some of them using awesome built from source is harder than for others.

Therefore it would be nice, if there was a new release soonish. At least it seems as if the project itself is still alive.

**Comment by sclu1034** [comment]
When it's ready.

[Milestone v4.4](https://github.com/awesomeWM/awesome/milestone/9) would be a rough list of what needs to be done, still.

**Comment by dm17** [comment]
Maybe releasing a v4.4-beta that some distros could decide to try (maybe with added warning) would get the `git` version in more users hands and thus better tested and thus v4.4 released sooner? Seems like a negligible difference from everyone building from git themselves, but I believe it could help in the home stretch ;)

**Comment by dm17** [comment]
> @dm17 Please read the comment directly above yours.

Sorry, and thanks for that. It just seems more realistic to have a `v4.3.1` or `v4.4-beta` before `v4.4`. I know that isn't only my view, but I realize the preference of the Awesome devs should take preference over a handful of users.

**Comment by sclu1034** [comment]
Things merged into `master` aren't split between fixes and features, so a patch version bump isn't really possible.

And a "beta" release isn't something you should just do at an arbitrary point (even though the gaming industry with it's "Early Access" tries to make it otherwise).
Plus, there would be no difference between such a tag and just building off of `master` or a fixed commit. Distributions don't package beta releases, so you would still have to build it from source.
It would merely be highlighting an arbitrary commit for no reason other than to satisfy "the reported version looks different now".

**Comment by actionless** [comment]
linux distributions which encourage unstable/unreleased versions of the software - already have tooling for installing it - like AUR, PPA etc
