### ISSUE TITLE
Extending Awesome by linking the C API?

### ISSUE THREAD

**Issue by oezingle** [awesomeWM/awesome#3675]
I've realized that `client.geometry()` returns the geometry of the client with decorations, so I've been looking for solutions to get the size of the client sans titlebar. 

I've noticed that [client_get_undecorated_geometry()](https://github.com/awesomeWM/awesome/blob/master/objects/client.c#L2269) in `objects/client.c` provides exactly the functionality I'm looking for, but isn't exposed to the Lua API. Of course, I could submit a pull request with changes to expose `client:undecorated_geometry()` or something, but I'm trying to stick to the stock `awesome` package and figured that my use case is niche enough that I could write my own C module and be done with the whole process. 

In short, my question is: can I include `objects/client.h` and link the awesome C API / library into a program I've written in any meaningful way? I'd rather avoid forking the whole project for a tiny feature that I may be the only person to use, meaning I lose maintenance.

I've seen a claim [on Reddit](https://www.reddit.com/r/awesomewm/comments/erahyo/comment/ff8goat/) that you can, in fact, write C/C++ modules yourself for awesome, but it doesn't go into any detail and I haven't seen any mention of it elsewhere. Am I misinterpreting the fact that you can fork Awesome, or can I actually write a *module* (in the sense that I can write freestanding C/C++ code) for mysefl?

Any help on this matter would be greatly appreciated!

**Comment by Elv13** [comment]
You can do C/C++/Anything modules, but they only have access to the same Lua APIs by pushing/popping data from the Lua VM. That makes them pretty useless for your use case.

For the original question, this is the code:

```lua
client.connect_signal("request::manage", function(c); gears.timer.delayed_call(function()
        local _, top_size = c:titlebar_top()
        local _, right_size = c:titlebar_right()
        local _, bottom_size = c:titlebar_bottom()
        local _, left_size = c:titlebar_left()

        local c_geo = c:geometry()

        local actual_geo = {
            x      = c_geo.x + left_size,
            y      = c_geo.y + top_size,
            width  = c_geo.width - right_size - left_size,
            height = c_geo.height - bottom_size - top_size,
        }

        print("TOTAL SIZE", c_geo.x, c_geo.y, c_geo.width, c_geo.height)
        print("TB SiZE", top_size, right_size, bottom_size, left_size)
        print("C SIZE", actual_geo.x, actual_geo.y, actual_geo.width, actual_geo.height)
end); end)
```

And yes, this is undocumented. There is a lot of problems with the current client geometry and titlebar APIs. There is always a vague willingness to replace the whole thing, but nothing is close to get merged. You can read more about this [here](https://github.com/awesomeWM/awesome/pull/3559) and [here](https://github.com/awesomeWM/awesome/issues/650#issuecomment-312502332). The idea is that the new API will be in line with all other widgets API. The "actual" client window will be just another widget and the client "frame" will be much closer to just another wibox.

As for the last part, yes, adding a `c.undecorated_geometry` read-only property would be nice. Note that this is a property, not a method. We are slowly deprecating all the accessor methods in favor of properties. The ones which are left is mostly because they are some backward compatibility issues if I try to deprecate them.

**Comment by oezingle** [comment]
Thanks for the quick reply - the limitation with Lua API integration makes sense but it's a bit of a shame we can't play around with the functionality exposed on the C side. 

I'm perfectly content using the function you've handed to me on a silver platter, but seeing a `c.undecorated_geometry` property would be awesome (heh) too.

Closing the issue, thanks for the help!
