### ISSUE TITLE
Awesomewm doesn't appear in the desktop selection on linux mint.

### ISSUE THREAD

**Issue by DARKBOW923** [awesomeWM/awesome#3731]
So basically i installed awesomewm in my linux mint machone and i couldn't start it, it doesn't appear in the desktop selection while icewm and many others do.

**Comment by Aire-One** [comment]
Hello @DARKBOW923,

This issue seems to be unrelated to Awesome.

You need to configure the display manager to have a new entry for the newly installed WM.

I did a quick search and every tutorial around mention 2 packages to install Awesome on Linux Mint: `sudo apt install awesome awesome-extra`. Make sure you have installed both. I can't tell for sure because https://packages.linuxmint.com is unavailable, but I guess the awesome package is only the WM while awesome-extra includes the display manager configuration :shrug:
