### ISSUE TITLE
Key chords

### ISSUE THREAD

**Issue by tarneaux** [awesomeWM/awesome#3762]
It would be nice to have a native way to bind key chords from a table, kind of like how xmonad does it.
I have tried doing this with the key grabber, but couldn't get it to work.
An example of how this could be implemented: instead of defining a function in a key binding, we could use some `keychord` class and in there use either the entire path of keys to press (like `mtl` for pressing m, t, l) for each element or just a tree of dictionaries, kind of like whick-key does it for vim.
It would also be nice to have some way of showing what has already been typed in the key chord in a wibar.

**Comment by actionless** [comment]
isn't there already a lib or two for doing that?

**Comment by tarneaux** [comment]
Now I remember it being in one of the user-made extensions (bling, lain...). However I don't remember which one it was.

**Comment by unai-ndz** [comment]
A little late but I have this implemented in the git version. My config is not public but I could extract the important bits.

If I remember correctly I do it by changing the global keybinds when the first chord is pressed and then restoring them when the chord is finished or cancelled. And a widget to show the state of the chord.

**Comment by tarneaux** [comment]
@unai-ndz Yeah that would be nice

**Comment by tarneaux** [comment]
@unai-ndz Thanks!

**Comment by cybergazer** [comment]
Please reopen, every implementation of this is extremely convoluted and impractical, I spent 3+ hours on trying to do this and gave up because the API for it now is to confusing and similarly every 3rd party software to make keychords on Linux is useless or unmaintained.

This is how it should be if looking to implement this:

```
awful.key(prefix({ modkey, }, "k", 2000),  "b" function() awful.spawn("librewolf") end),
```

Awesomewm is the best tiling window manager in existence imo it just really needs this one feature, or else people run out of keys to map stuff to and switch to your competition aka xmonad.

**Comment by actionless** [comment]
>  and switch to your competition aka xmonad.


sorry, but what's the problem here?
