### ISSUE TITLE
lain's helpers.lua doesn't work correctly with awesome from master. timer api changed?

### ISSUE THREAD

**Issue by tigrisathon** [awesomeWM/awesome#380]
awesome v3.5.2-594-g836aded-dirty (The Fox)
If I run some widgets from lain (https://github.com/copycat-killer/lain), I get following error: https://i.imgur.com/sYAaGl2.png, though it works ok with awesome 3.5.6 (release). Here is fragment of code in helpers.lua, which causes error:

helpers.timer_table = {}
function helpers.newtimer(name, timeout, fun, nostart)
helpers.timer_table[name] = capi.timer({ timeout = timeout })
helpers.timer_table[name]:connect_signal("timeout", fun)
helpers.timer_table[name]:start()
if not nostart then
helpers.timer_table[name]:emit_signal("timeout")
end
end

Has anything related to timers changed since 3.5.6? What changes should be made to make it work?
Thank you.
P.S. Please add "question" tag.

**Comment by psychon** [comment]
`timer` is now called `gears.timer`. For backwards compatibility, `awful/init.lua` does this at the beginning to make a function called `timer` available again:
```
local gtimer = require("gears.timer")
function timer(...)
    util.deprecate("gears.timer")
    return gtimer(...)
end
```
However, this is only done while awful is loaded and so is not available before, so you should `require("awful")` before you `require("lain")`.

If this should be fixed in lain, it could do something like `local timer = timer or require("gears.timer")`. (Or, judging from the error message, `local capi = { timer = timer or require("gears.timer") }`.)

Should we somehow improve backwards compatibility with this timers change. How?

**Comment by tigrisathon** [comment]
I have changed positions in my rc.lua, so that all the core modules are on the first place, and the problem has disappeared. My fault. Currently there are no lua errors when using lain's widgets, but when using some of them (for example, alsa.lua, mem.lua) they give no output (do not appear on the panel), though some of them (cpu.lua, for example) do. Could you please check them on your configuration? https://github.com/copycat-killer/lain/wiki

**Comment by psychon** [comment]
Sorry, you better ask @copycat-killer that

**Comment by tigrisathon** [comment]
Ok, gonna ask him. Thank you for your advice)

**Comment by tigrisathon** [comment]
Argh, it's my fault again. His widgets do not display anything unless it is explicitly stated when calling them. For example,
myspuusage = lain.widgets.cpu() will have no effect, but
mycpuusage = lain.widgets.cpu({
    timeout = 4,
    settings = function()
        widget:set_markup("Cpu " .. cpu_now.usage)
    end
})
will show what it has to show.

**Comment by copycat-killer** [comment]
@tigrisathon Of course they won't display anything, if you don't set them properly first.

Read the wiki next time.
