### ISSUE TITLE
Floating property in rule is ineffective

### ISSUE THREAD

**Issue by OscarCapac** [awesomeWM/awesome#3818]
Output of `awesome --version`:
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**
Set up a simple rule involving floating like this
```
{ rule = { floating = true },
  properties = { titlebars_enabled = true },
 },
```

**Actual result:**
Floating client will not have a titlebar.

**Expected result:**
Floating client will receive a titlebar.

**Comment by gabrieldlima** [comment]
> Output of `awesome --version`: awesome v4.3 (Too long) • Compiled against Lua 5.3.6 (running with Lua 5.3) • D-Bus support: heavy_check_mark • execinfo support: heavy_check_mark • xcb-randr version: 1.6 • LGI version: 0.9.2
> 
> **How to reproduce the issue:** Set up a simple rule involving floating like this
> 
> ```
> { rule = { floating = true },
>   properties = { titlebars_enabled = true },
>  },
> ```
> 
> **Actual result:** Floating client will not have a titlebar.
> 
> **Expected result:** Floating client will receive a titlebar.

To troubleshoot this issue, you can try the following steps:

Check your AwesomeWM configuration file (rc.lua or rc.lua.d) and ensure that there are no conflicting rules or settings that might override the titlebars_enabled property for floating clients.

Verify that the theme you are using includes a titlebar for floating clients. Some themes might have different configurations for different client types, so make sure the theme you are using has a titlebar defined for floating clients. You can check the theme's documentation or configuration files for more details.

Confirm that the rule you have defined for floating clients is placed correctly in your configuration file. Rules in AwesomeWM are processed in order, so if you have another rule that matches the same client and applies different properties, it could override the titlebars_enabled setting.

If the issue persists, try updating your AwesomeWM installation to the latest version. The issue you are facing might be a bug that has been fixed in a newer release.

**Comment by OscarCapac** [comment]
> Confirm that the rule you have defined for floating clients is placed correctly in your configuration file. Rules in AwesomeWM are processed in order, so if you have another rule that matches the same client and applies different properties, it could override the titlebars_enabled setting.

How does the overwrite work. Are rules placed before overwritten by later rules or is it the other way around ? 
I'm mostly using the default rc.lua by the way.

**Comment by Aire-One** [comment]
Hello @OscarCapac,

When defining a new rule, the `rule` sub-table defines what the client have to match to apply the `properties`. This check is run at the client detection, which is very early in the client life cycle. It is expected that the floating status is unknown at this stage.

So `rule = { floating = true }` will never be triggered. You'll have to find another way to target the clients you want here.

**Comment by OscarCapac** [comment]
That makes sense. Thank you
