### ISSUE TITLE
Better SVG support

### ISSUE THREAD

**Issue by worron** [awesomeWM/awesome#390]
Is it possible use vector scaling for SVG icons in awesome?

**Comment by worron** [comment]
@psychon
I made an experimental [widget](https://github.com/worron/redflat/blob/ebbb6433a07fc2ed1455a9d356b0e1c2ad97c674/gauge/svgbox.lua) based on your example. It works and works better than my workarounds used before. But render to temporary file still seems like overhead. Main question: is there any other way translate  pixbuf to cairo surface?

**Comment by psychon** [comment]
Just do `require("lgi").Gdk`. Gdk provides a function `gdk_cairo_set_source_pixbuf` (or something like that) which lgi makes available on cairo contexts. After this you can just use `cr:set_source_pixbuf(some_pixbuf)`.

However, I would like to avoid making awesome depend on Gdk, because using Gdk from a window manager doesn't really work well (too much traps to fall into).

**Comment by Elv13** [comment]
Here is an example how to load GDK/GTK icons asynchronously using the
function mentioned by Uli
https://github.com/Elv13/awesome-configs/blob/master/utils/fd_async.lua#L414

Have fun

**Comment by worron** [comment]
Thank you very much. Now it works as desired.  And example is useful.
I admit it may be not safe globally, but now I'm fully satisfied with this Gdk trick. Hope it will be ok for personal using, until awesome will get foolproof vector scaling feature.

**Comment by actionless** [comment]
can we move it somehow to imagebox to be able to set size automatically?

**Comment by worron** [comment]
It is quite possible, but there are some reasons not to do it.
1) In post above Uli Schlachter spoke against making awesome depend on Gdk.
2) It will conflict with recoloring feature 5806048. In my imagebox modification recolor is going after scaling and it's ok. In your approach icon transformed to recolored surface long before it reach imagebox, and there are no way to proper scaling.

**Comment by psychon** [comment]
Awesome should still do something better by default for SVGs. Perhaps it might even make sense to support animations (GdkPixbuf does!) :-)
Some quick API idea: Add a new object kind (image? I don't know) which has:
- `:query_size()` for some preferred size
- `:get_for_size(width, height)` for getting a surface (this could then render a SVG at the needed size)

This could also be extended to support animations. Just emit some signal when a redraw is needed. The signal is only emitted if `:get_for_size()` was called since the last time it was emitted, so animations which aren't displayed would automatically stop.

Also: https://github.com/awesomeWM/awesome/pull/369#issuecomment-127178507

**Comment by Elv13** [comment]
It is now possible to use functions as background images for some widgets. Those can return a correctly sized SVG using librsvg API

**Comment by psychon** [comment]
Is this fixed by #2779?

**Comment by worron** [comment]
I guess so.
