### ISSUE TITLE
Stdout not working correctly for awful.spawn.with_line_callback but stderr does

### ISSUE THREAD

**Issue by finnurthorisson** [awesomeWM/awesome#3925]
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

```lua
local cpubraille = wibox.widget.textbox(" [⠀⠀⠀⠀⠀⠀⠀⠀]", true);
awful.spawn.with_line_callback("cpubraille", {
	stdout = function(line)
		cpubraille.text = " ["..line.."]"
	end
})
```

https://codeberg.org/nazrin/cpubraille

Changing the `stdout` callback to `stderr` and changing [these two lines](https://codeberg.org/nazrin/cpubraille/src/branch/master/src/main.c#L81-L82) from `printf(...)` to `fprintf(stderr, ...)` fixes the issue and the output from the program shows up

**Expected result:**

Stdout should work the same as stderr, should it not? I got the idea to try stderr after finding [this Reddit post](https://www.reddit.com/r/awesomewm/comments/12ce9y6/c_program_using_printf_doesnt_play_with/) from a year ago which seems to have the same problem

**Comment by finnurthorisson** [comment]
It seems adding an explicit `fflush(stdout);` fixed it. Still, what causes it to work in the terminal but not awesome, but also stderr for some reason works?

**Comment by sclu1034** [comment]
> Stdout should work the same as stderr, should it not? 
No, they do not. `stdout` is buffered by default, `stderr` is unbuffered by default.

Anything sent to `stderr` is forwarded directly to whoever listens on the socket, but `stdout` collects input until the buffer is full or explicitly flushed (the latter is what you do with `fflush`), and only then forwards the data.

And it does work slightly differently in a terminal, because the default buffering on `stdout` changes from fully buffered to line buffered when connected to an interactive device. At that point, a newline character will trigger a flush even before the buffer is full.

**Comment by finnurthorisson** [comment]
But why would an interface that receives output line by line not be line buffered, who would that be useful for?

The documentation states that „[with_line_callback](https://awesomewm.org/doc/api/libraries/awful.spawn.html#with_line_callback) will execute the callbacks every time a new line is printed by the command:“, not „printed and then flushed“. I think either the docs should specify this caveat or, even better, the stdout pipe should be set to line buffer

**Comment by sclu1034** [comment]
It's the spawned application that controls the configuration of `stdout`, not AwesomeWM.
