### ISSUE TITLE
[Feature Request] Vastly improve documentation

### ISSUE THREAD

**Issue by s1nistr4** [awesomeWM/awesome#3938]
The documentation of awesomewm is unreadable and unhelpful for most people, it mostly just lists out what's in the API rather than going into specific examples and teaching how to do helpful things in it and it's preventing me from using awesomewm as a daily driver

Improving the documentation would make this project significantly more popular because people can well, use it, and know how to use it.

I can name countless examples of major issues with the docs: 

- One extremely common use case in a tiling window manager is to remap 1-9 to other keys because it's more comfortable. In the docs, this doesn't exist. The closest you get to it is https://awesomewm.org/doc/api/classes/tag.html which is unhelpful, I copied/pasted the function move_to_new_tag into awful.key and it gave a lua error.

- Assigning floating windows to specific programs. There's some docs on the window rules, https://awesomewm.org/doc/api/libraries/awful.rules.html which does kind of have some practical examples, but once you get to anything specific like a pop-up window in another program, nothing in here works. Idk if it goes by title, command name, etc, none of it is explained.

- This is the docs on theming https://awesomewm.org/doc/api/sample%20files/theme.lua.html Literally just a copy/paste of the stock theme file

- This is the docs for awful.spawn https://awesomewm.org/doc/api/libraries/awful.spawn.html The problem is that if you run any of those commands your mouse will be in an infinite loading spinner. You have to put ```awful.spawn("commandname", false)``` to get it to go away. This is a majorly important thing to know and it's not mentioned anywhere in the docs

I can go on but this could all be fixed if there were practical examples and it explained what each function did, this project would benefit immensely if the docs are fixed, I can't stress it enough. Improving it would only net you significantly more users.

Also kind of unrelated but I figure I'd bring it up instead of having a separate issue, it would benefit immensely from having a dark mode.

**Comment by actionless** [comment]
https://awesomewm.org/apidoc/documentation/05-awesomerc.md.html

**Comment by Elv13** [comment]
> One extremely common use case in a tiling window manager is to remap 1-9

We willfully don't want to document specific use cases. In the past, there was some helper functions for common things. However, everybody definition of "common use cases" and how they should behave was different. They have been deprecated and most of them removed.

The API documentation document what the API is and what it does. We attempt to provide working code examples of how those API elements behave. The development doc has them for over 60% of the 10000+ API elements. All of them unit tested. This is very time consuming to write. We also aim to be consistent on this. The example show *how it behaves*, they do not attempt to show how to use them. Because everything is documented consistently, after a non-negligible learning curve, the users tend to be able to quickly figure out the "how" using the documentation.

> Assigning floating windows to specific programs.

Yes, this is confusing. The problem is sadly not easy to document since different application implement their windows differently. Please use `xprops` to see what the application did and base your rules on that. There is no single answer  that works for everything. Us attempting to do some kind of abstraction would be futile. There would always be more corner cases to cover. Chasing them all would result in unmaintainable code.

> This is the docs on theming

The page you are looking for is https://awesomewm.org/apidoc/documentation/06-appearance.md.html . This is the list of all theme variables. Yes, some links are broken, I know. However, most work. From those links, click `Click to display more` and this will show the `Used by:` table. Click on those links to see the associated properties with the corresponding examples of valid values. Again, we cannot document how to make Awesome "pretty" because everybody's definition of "pretty" is different. What is called what is documented here https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html . Adding tutorial for how to skin every single elements would make the documentation too large and thus harder to navigate. We intend to document the behavior of everything rather than do tutorials.

> This is the docs for awful.spawn [...]  an infinite loading spinner. 

This happens because the application does not implement the startup notification protocol properly. There is no way for us to detect that. There is doc on how to ignore it. A more modern fix would be to delegate this to `systemd` using `cgroups`. This will require some code and while on my todo list, I didn't do it yet. It would also only works for users of systemd, with all the political backlash this would cause.
