### ISSUE TITLE
AwesomeWM tutorial?

### ISSUE THREAD

**Issue by DevMSri** [awesomeWM/awesome#3954]
Hi, I am new to awesome and have just moved from hyprland, being a semi-noob at Linux, I was wondering if there are any up-to-date tutorials or documents which walk through how to rice awesome and how to customize it effectively. Thank you!

**Comment by actionless** [comment]
https://awesomewm.org/apidoc/documentation/07-my-first-awesome.md.html#

**Comment by Elv13** [comment]
The problem here is that everybody's definition of "rice awesome" is different. What I personally suggest is to get the development version (git version) and use the development documentation. It has examples for most things. After the "my first awesome" actionless linked above, read [The widget system](https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html). This will give you a good idea of the jargon and what different things are called. After that, you can look at their own doc pages and see the examples. For example, here's the [wallpaper](https://awesomewm.org/apidoc/popups_and_bars/awful.wallpaper.html).

If you find something that is unclear, please comment on https://github.com/awesomeWM/awesome/issues/1373 with what you would like to be clarified.

Keep in mind that the documentation is similar to Javadoc/Doxygen rather than something like Python documentation. By that, I mean it is a structured documentation rather than freestyle/wall_of_text one. It explains in detail how everything behave and what options the API has rather than give endless examples of how to achieve random things.

**Comment by actionless** [comment]
> What I personally suggest is to get the development version (git version) and use the development documentation

https://github.com/awesomeWM/awesome/issues/3937
