### ISSUE TITLE
Transparency for titlebars not working

### ISSUE THREAD

**Issue by timroes** [awesomeWM/awesome#416]
It seems that creating titlebars on clients can't have true transparency.

I added `awful.titlebar(c, { size = 30 }):set_widget(..)` to my config and added `theme.titlebar_bg_normal = "#F5F5F5AA"` to my theme.lua. The color is correctly applied to the titlebar, but it only has pseudo transparency (merging with wallpaper).

I found, that there might be multiple problems: The `awesome.composite_manager_running` variable is always `false` even though compton is running. I saw, that you use `_NET_WM_CM` to detect a running compositor. Might it be that some compositors (like compton) won't set this property correctly?

I found, that this property is used in the `wibox.drawable` to switch to pseudo transparency (https://github.com/awesomeWM/awesome/blob/master/lib/wibox/drawable.lua#L38). I modified this file so that always the else path will be taken and restarted, but still my titlebars only had pseudo transparency.

Do you have any ideas where the problem might be? Can you use real transparency (with compton or another compositor) for titlebars?

Btw, compton itself seems to work, i.e. the clients that have opacity != 1 use real transparency (and not pseudo one).

**Comment by psychon** [comment]
Compton does acquire `_NET_WM_CM_S?`:
https://github.com/chjj/compton/blob/b1889c1245e6f47eedfae6063100d5a16f584e2b/src/common.h#L207
https://github.com/chjj/compton/blob/master/src/compton.c#L4891-L4906
Would be nice if you can somehow figure out why this does not work.

To check if real transparency is being applied, try adding this to your config:
```lua
local gears = require("gears") -- No idea if the default config already does this
client.connect_signal("manage", function(c)
    t = timer({ timeout = 5 })
    t:connect_signal("timeout", function()
        gears.surface(awful.titlebar(c, { size = 30}).drawable.surface):write_to_png("/tmp/titlebar.png")
    end)
    t:start()
end)
```
This should create a screenshot as `/tmp/titlebar.png` of each titlebar 5 seconds after a new client appears. If that PNG contains a transparent background, then transparency is wroking. If the PNG has your wallpaper as its background, then pseudo-transparency is used.

**Comment by timroes** [comment]
Apparently I was yesterday to tired to code correctly (I made a mistake when trying to jump in the else path of `wibox.drawable`). I just wrote a working version of `wibox.drawable` which will - this time really - always use real transparency despise `awesome.composite_manager_running` value.

Now the behavior changed: I don't get pseudo transparency anymore, but neither real one. It seems, that the background color (set to #F5F5F599 in my case) will be drawn on black (and not on the real background). Decreasing the opacity resulted in a more and more dark gray (as you can see from VLC titlebar):

![](http://fs2.directupload.net/images/150818/s7297ogy.png)

As you can also see on the screenshot transparent clients work just fine.

I've just uploaded my current config to a dev brach: https://github.com/timroes/awesome-config/tree/develop

Perhaps someone with compton installed could try if he/she gets real transparent titlebars with this config. For the case pseudo transparency is used, just add `false and` to line 34 of the `lib/wibox/drawable.lua` (as seen on the left side in the screenshot).

I've also played around with #405 and tried several combinations of `cr.operator` and `paint_with_alpha` but was not able to produce a version in which my titlebars got transparent.

Why the variable `awesome.composite_manager_running` is always `false` for me seems to be an unrelated issue (as long as I modify the `wibox.drawable`) and I will try to look into this these days and hopefully find a reason for that.

**Comment by psychon** [comment]
Could you still try my code snippet and see if the resulting PNG contains a transparent background or is also gray/blackish? E.g. open with gimp, add a new layer, fill it with red and move it below the image. Does the red shine through?

Also, you don't happen to start awesome with `--no-argb`, do you? (I assume no, since otherwise your terminal shouldn't have working transparency either, but I better ask)
The behavior you describe is what would happen without a composite manager running. Hm.... Weird.

Oh and: Does transparency work on your wibox, but just not on titlebars, or is is also broken on wiboxes?
Quick test could be something like `echo 'test_wibox = require("wibox")({x = 10, y = 10, width = 100, height = 100, ontop = true, visible = true, bg = "#ff000080"})' | awesome-client`. This should open a wibox of size 100x100 containing only a semi-transparent red background. You should be able to move something behind it (if there isn't something behind it already). To get rid of that wibox again, the following *might* work: `echo 'test_wibox.visible = false' | awesome-client`.

**Comment by timroes** [comment]
@psychon You are a genius again! Of course I still had `--no-argb` from a very old performance issue in my xsession (where I didn't look at all for issues)... no idea why the client transparency works though.

Removing it solved both issues: `awesome.composite_manager_running` is now `true` and transparency works like I would expect it.

Thanks a lot! And sorry for the ticket.
