### ISSUE TITLE
Compton frame-opacity leaks on the content of the screen

### ISSUE THREAD

**Issue by BenoitZugmeyer** [awesomeWM/awesome#425]
I use compton to have semi-opaque window borders. It worked great on awesome 3.5.6, until I updated to awesome master (up to date).

Strangely, the border is semi-opaque as expected, but there is an additional semi-opaque zone of the same width as the border, on every side of the window. Here is a snapshot to illustrate:
![snapshot2](https://cloud.githubusercontent.com/assets/61787/9429927/6c0d92fa-49e1-11e5-8c58-d707f440672b.png)

In this snapshot, I use the default awesome rc, with the default theme. I only changed the border width to 10px to clearly see the issue. I launched compton without a configuration file, only --frame-opacity to 0.5 (as you can see on the snapshot).

I don't think it is a compton issue, as it worked as expected with the stable version of awesome. I tried with both compton master and the latest release (v0.1_beta2)

Does anyone is having the same issue?

**Comment by psychon** [comment]
Could you perhaps try to do a git bisect between awesome 3.5.6 and master?
I don't have any idea what could cause this and my first reaction would be to blame compton.

**Comment by BenoitZugmeyer** [comment]
Bisect result:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
4a094fa4824836ee5a029a6c0e147b5b3e2bee12
55bffbcc459a780f3d8b8d6756783fb97145d481
We cannot bisect more!
```

So the problematic commit seems to be 4a094fa4824836ee5a029a6c0e147b5b3e2bee12

**Comment by psychon** [comment]
Thanks a lot for bisecting this. I always forget that `git bisect skip` exists. :-)

Hm. I'm not really sure what the spec says. Using the window border that X11 offers is something that apparently few WMs do (I can only think of non-reparenting ones) and EWMH doesn't seem to definitely say that the `border_width` of the frame window should be included. I'd be interested in seeing another reparenting WM that uses the borders and implements `_NET_FRAME_EXTENTS`.

Perhaps this should be reported to compton so that we can see what they see? It might also make sense to have the spec clarified (what's the intention and how can the wording be improved?). I'll write to the wm-spec list when I can find the time (sorry, might take a while).

**Comment by psychon** [comment]
The result seems to be that we are right, see the thread starting in https://mail.gnome.org/archives/wm-spec-list/2015-August/msg00000.html

**Comment by BenoitZugmeyer** [comment]
Thank you for taking care of this!

**Comment by richardgv** [comment]
I am the current maintainer of compton. Thanks for analysis! I have pushed a fix for the problem to compton as c156abb on `richardgv-dev` branch. Could you please check if the problem still appears with a build of compton on `richardgv-dev` branch?

**Comment by BenoitZugmeyer** [comment]
I just tested compton on richardgv-dev branch, and it fixes the issue! thank you. Closing this issue.

**Comment by richardgv** [comment]
@BenoitZugmeyer: Great. I have merged it to the `master` branch of compton.
