### ISSUE TITLE
Big Icon

### ISSUE THREAD

**Issue by salorium** [awesomeWM/awesome#487]
![28-09-2015 00 50 29](https://cloud.githubusercontent.com/assets/1009923/10125609/4ae2c52c-657b-11e5-9832-25b8567417e8.png)
Steam icon too big

**Comment by psychon** [comment]
Is this the systray? That'd likely be a steam bug then (although I wonder how they manage to do this...)

**Comment by nuko8** [comment]
[System Tray Protocol Specification](http://standards.freedesktop.org/systemtray-spec/systemtray-spec-latest.html) says:

> Tray icons may be assigned any size by the system tray, and should do their best to cope with any size effectively.

This sounds like Awesome can do something with icon sizes if it will.

If we take a look at `systray_process_client_message()` of `systray.c`,  the function retrieves the geometry of the tray icon window, but that data is discarded at present.

If that data contains something meaningful, then comparing it with the systray's size, calculating a magnification based on it, retrieving the pixmap from the given window ID, magnifying the pixmap accordingly, and redrawing the window with the resulting pixmap, might be a possible way to cope with the issue, though I'm not sure if it is feasible and don't know how to code this for myself with `xcb` stuff.

**Comment by salorium** [comment]
![28-09-2015 15 01 54](https://cloud.githubusercontent.com/assets/1009923/10135950/fac61112-65f1-11e5-8575-f081881b459c.png)
When i restart awesome, the icon size is correct

**Comment by psychon** [comment]
@psychon Maybe awesome should request SubstructureRedirect for the tray window. That would definitely stop tray icons from resizing themselves. This just has to make sure that the resulting ConfigureRequests don't confuse anything.... This might be as simple as changing `systray_init` to do:
```C
    xcb_create_window(globalconf.connection, xscreen->root_depth,
                      globalconf.systray.window,
                      xscreen->root,
                      -1, -1, 1, 1, 0,
                      XCB_COPY_FROM_PARENT, xscreen->root_visual,
                      XCB_CW_BACK_PIXEL | XCB_CW_EVENT_MASK, (const uint32_t [])
                      { xscreen->black_pixel, XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT });
```

**Comment by nuko8** [comment]
The following is an attempt to incarnate the rough idea in my previous comment: https://gist.github.com/nuko8/6de406c9650acea22745

What was suggested by @psychon is also incorporated into the patch, because, having read @salorium's second report, I think it is the right thing to do.

That said, I'm not sure if the patch indeed fixes @salorium's problem.  I'd appreciate it if someone could check that.

**Comment by psychon** [comment]
Could someone test if #509 fixes this issue?

@nuko8 Sorry, but you cannot be sure when a systray icon is done painting itself or when it is updated and thus i don't think randomly taking screenshots will work well.

**Comment by nuko8** [comment]
I agree on your view.  

But my patch doesn't take screenshots that way.  Screenshots are taken in `systray_update()` with the condition that the icon the client provides, doesn't fit into the space the systray allocates for it.

I should have added some comment on my patch which would tell you all it was not an implementation truly faithful to my initial idea.

That said, I always prefer to a better solution and your patch looks OK to me.  So, go ahead, please :-)

**Comment by salorium** [comment]
With https://github.com/awesomeWM/awesome/commit/017660de489ac729dceabe6ef8be2f097c53cf39
I start awesome and i have no system tray icon : 
![13-10-2015 13 24 14](https://cloud.githubusercontent.com/assets/1009923/10453663/6fe7cb30-71ae-11e5-94b1-6dd1d2e3dcff.png)
After restart awesome, system tray icon appear : 
![13-10-2015 13 24 21](https://cloud.githubusercontent.com/assets/1009923/10453682/9860fd98-71ae-11e5-8349-f214ed28d59d.png)
I start steam and system tray icon disappear : 
![13-10-2015 13 24 48](https://cloud.githubusercontent.com/assets/1009923/10453698/b563634a-71ae-11e5-9714-afca83dc986e.png)
I restart awesome, system tray icon appear : 
![13-10-2015 13 24 54](https://cloud.githubusercontent.com/assets/1009923/10453717/d5e6fe10-71ae-11e5-9470-73b5123bd1c0.png)

**Comment by psychon** [comment]
Do I understand correctly that either all or none of the icons are visible? It doesn't happen that just a single icon is missing...?

**Comment by psychon** [comment]
Also, according to IRC, if another systray becomes visible after steam, then steam is visible, too.
Except for steam, does this new problem happen with any other software? (that perhaps isn't proprietary and requires me to install a complete i386 userland)

**Comment by salorium** [comment]
Sorry for no new
When I run steam, all my icon disappears.

**Comment by ahodesuka** [comment]
ibus' gtk3 ui also causes all systray icons to disappear, if you enable it's tray icon.
I noticed it pushes the right click menu way down (my systray is at the top of my screen).
![tray](https://cloud.githubusercontent.com/assets/1155344/11450016/2118ea58-9552-11e5-9ca8-1f62d761b856.gif)

**Comment by psychon** [comment]
@ahodesuka Thanks, took me a while to set up ibus (and I still do not know what it actually does...), but at least I can reproduce this issue.

Could you edit `/usr/share/awesome/lib/wibox/widget/systray.lua` and add something at line 87 (My line number might be a bit off)? Right now the line says `ret:emit_signal("widget::layout_changed")`. *Copy* that line and add additionally `ret:emit_signal("widget::redraw_needed")` (order between these two lines does not matter). That fixes the problem here.

What happens (at least here) is that ibus creates a tray icon. The systray is updated. Then ibus destroys this tray icon again and creates a new one (with no time in-between for the systray to update). Since the number of icons did not change since the last update, the code wrongly concludes that the systray does not need to be redrawn/updated. Thus, no redraw occurs. And no, I do not know why this makes icons disappear.

**Comment by ahodesuka** [comment]
Adding `ret:emit_signal("widget::redraw_needed")` fixed the problem for me.
It also fixes steam from doing the same thing.
