### ISSUE TITLE
Provide a default keybinding for unminimizing

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#501]
-- Unminimize a client.
    awful.key({modkey, "Shift"}, "n", function()
        awful.client.restore()
    end),

**Comment by blueyed** [comment]
> vdevatman: for that matter minimize is mod-shift-n for me already.  Might be also a relevant change to the default config.  I have mod-shift-ctrl-n for unminimize.

**Comment by VdeVatman** [comment]
I just felt frustrated when I pressed that keystroke several times and then all my tiles were minimized and had no way to recover them all without using the mouse which I try to use the less the better

But it doesn't seems to be a problem since it is well documented within rc.lua and is quite easy to change the behaviour.

> vdevatman: there's no unminimize default key mapping AFAIK.  Ref: https://github.com/awesomeWM/awesome/blob/master/awesomerc.lua#L300-L305
> - blueyed

**Comment by psychon** [comment]
da9e4a52df1da6f1bc2affbf07
