### ISSUE TITLE
menubar: no category icons with Adwaita theme

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#522]
The Adwaita theme gets used by default, but provides no icons for the categories, e.g. applications-accessories.

These would be provided by "gnome".

Maybe fallback themes should be used in this case?

Should the lookup for categories only look into `categories` / `Context=Categories` subdirs?

/cc @nuko8

**Comment by blueyed** [comment]
btw: I am heavily trying to optimize the menubar/theme handling code, but there are e.g. still ~9300 calls to `file_readable` just for handling the category icons, that cannot be found..!

**Comment by Elv13** [comment]
There is already a solution for that by using the GTK implementation, it is asynchronious and very fast. It work without crash for me (compared to some other LGI async API), probably because it never perform recursive async operations. I am also currently porting that whole code to C (with some C++ features mixed in) and plan to use dlopen to avoid adding a dependency on GTK at install time (but use it if it's installed). Here is the (very early, and mostly written today) code https://gist.github.com/Elv13/d5d2cf7d2fa23d75a35c (original https://github.com/Elv13/awesome-configs/blob/master/utils/fd_async.lua ) . It doesn't yet plug with lua or have the request object logic. This code is also planned to be a private API used by a lua frontend.

So, if you want my opinion on this, rather than implement the proper XDG icon spec and fallback themes and so on, lets just use a solution that's already implemented and much faster than lua lookups anyway. I still need to port the socket, download, dbus, icons and INI parsing code to "big-C" and write the lua side, but it is progressing well. The code is also not release quality, it's looking ugly, leak memory as hell and don't have error handlers at all.

**Comment by blueyed** [comment]
> So, if you want my opinion on this, rather than implement the proper XDG icon spec and fallback themes and so on, lets just use a solution that's already implemented and much faster than lua lookups anyway. 

:+1: 

But it will take some time until the icon lookup / theme handling could be used through this, right?

**Comment by Elv13** [comment]
Oh, yes and by the way, I already optimized that code in my 3.4 config
https://github.com/Elv13/awesome-configs/commit/ddb34e83ec0ac6cb3c8555b440208504b101a681#diff-32f0db718b66dfb55ada04bd075a0c77L1

However, I dropped this a year ago when I switched to the much faster GTK implementation. The Awesome `menubar` module is a fork of the previous `freedesktop` module I was using in my config, they diverged long time ago and the maintainer of freedesktop never cared to merge my fixes.

**Comment by Elv13** [comment]
> But it will take some time until the icon lookup / theme handling could be used through this, right?

Umm, I am quite unreliable given I am traveling all the time, but as I already ported 75% of `fd_async` and ran some early tests on the code, it seem to work quite well, I suggest you could give me a week and see if I can get something together. If I don't then, well, I guess you are right :P 

The big part is the GDbus code, a port of my `wirefu` module, but I can put that on hold and focus on getting the async IO and resources code working first.

**Comment by nuko8** [comment]
@blueyed 
>The Adwaita theme gets used by default, but provides no icons for the categories, e.g. applications-accessories.

I have installed `adwaita-icon-theme 3.18.0` on my machine and I'm sure I have both `/.../share/icons/Adwaita/<size>/categories/*.png` and `applications-accessories.png` .

So I cannot understand what you really mean.  Is it a matter which may vary on a version in use?

Note also that querying a non-existent icon is very, very costly for the icon lookup algorithm, which may take time of second order.  I guess all you've got --slow menubar startup and excessive calls-- are due to that.

**Comment by blueyed** [comment]
Yes, I have files in `/usr/share/icons/Adwaita/scalable/categories` myself (in adwaita-icon-theme 3.14.0-2ubuntu8):

```
/usr/share/icons/Adwaita/scalable/categories/applications-graphics-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/preferences-system-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/applications-games-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/applications-utilities-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/system-help-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/preferences-other-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/applications-science-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/applications-engineering-symbolic.svg
/usr/share/icons/Adwaita/scalable/categories/applications-multimedia-symbolic.svg
```

**Comment by nuko8** [comment]
I've just pushed a PR to handle scalable icons correctly (PR #525)

I hope this partially solves your problem.

But I can't save the issue on the missing `applications-accessories`, which seemingly exists as fixed size icons...

**Comment by blueyed** [comment]
Yeah, the icons exist in 3.18.0-1, but are also missing in 3.16.2.1-2ubuntu1 (Ubuntu 15.10).

What do you think about using a fallback theme for this also?

**Comment by blueyed** [comment]
The changelog for 3.18.0-1 contains some hint (2nd entry), so maybe it's only a Debian/Ubuntu issue?!
```
adwaita-icon-theme (3.18.0-1) unstable; urgency=medium

  [ Andreas Henriksson ]
  * Drop libgtk*-bin build-dependency
    - there's no point to gtk-update-icon-cache during build,
      we let the postinst do it on package install.
  * Add missing build-dependency on gtk-3-examples
    - the gtk-encode-symbolic-svg program is used during build to
      create specially prepared png files (faster to load than svg).

  [ Pedro Beja ]
  * New upstream release.

 -- Andreas Henriksson <andreas@fatal.se>  Wed, 23 Sep 2015 19:19:02 +0200
```

**Comment by blueyed** [comment]
With 3.18.0-1 they exist in:
```
% find /usr/share/icons/Adwaita/ -name applications-accessories.png
/usr/share/icons/Adwaita/24x24/categories/applications-accessories.png
/usr/share/icons/Adwaita/48x48/categories/applications-accessories.png
/usr/share/icons/Adwaita/16x16/categories/applications-accessories.png
/usr/share/icons/Adwaita/32x32/categories/applications-accessories.png
/usr/share/icons/Adwaita/22x22/categories/applications-accessories.png
```

**Comment by nuko8** [comment]
> What do you think about using a fallback theme for this also?

It's not a fallback.  The fallback is `hicolor` icons.  You'll never have Adwaita icons after all lookups fail.

The only reason I chose Adwaita was that it has been [the default theme of recent versions of GTK](https://blogs.gnome.org/mclasen/2014/06/13/a-new-default-theme-for-gtk/).  If we change the default right now, we'll soon revert to Adwaita, won't we?

For those who can't use the latest Adwaita icons, either `theme.icon_theme = "gnome"` in `theme.lua` or `beautiful.icon_theme = "gnome"`in `rc.lua` will do.

**Comment by psychon** [comment]
Closing this since the code does what the spec says. If Ubuntu does not provide the category icons, then Ubuntu does not provide the category icons.
