### ISSUE TITLE
Changing song in spotify makes awesome hang for a few seconds

### ISSUE THREAD

**Issue by ElGoreLoco** [awesomeWM/awesome#524]
When I change a song (or it automatically changes) I can't move between tags and clients and the mouse doesn't work (I can move it but clicking doesn't work). But if I'm writing something (I tested in firefox, vim and the terminal) I can still type.

Another thing that I noticed is that if I change a song and close a terminal right after that (using `exit`), it leaves a gap and when it stops hanging, the clients go where they should.

I think this is happening because of the notification that spotify sends: right when awesome starts working again, a notification appears for a moment.

**Comment by psychon** [comment]
Does the notification include an image (e.g. album cover)?
If it is the notification, could you run `dbus-monitor` and capture its output?
Could you also open a terminal with `top` and see if awesome has high CPU usage while hanging?
Also, what's your awesome version? (I am asking because https://github.com/awesomeWM/awesome/commit/ed763b9ad39e17161c5571be360542ead4b41050 speeds up the code for handling images sent to naughty via dbus and I guess you are seeing exactly this problem)

**Comment by ElGoreLoco** [comment]
Yes, the notification has an image (I remember it was pretty big).
The output of dbus-monitor is [here](https://gist.github.com/ElGoreLoco/e599ed743efd83bc795e).
When that happens one of my four cores goes 100%, they usually are very low usage.
My awesome version is `3.4.15` (it says that it has D-Bus support).

Sorry for the late answer.

**Comment by psychon** [comment]
`3.4.15` is before ed763b9ad39e17161c5571be (awesome 3.5.2), so I guess this was already fixed. Sorry, but I will just close this then.
(For the dbus info: Spotify is sending two 300x300 images and the old code isn't efficient at digging through those 263 KiB)
