### ISSUE TITLE
set_markup crashes awesome with invalid text

### ISSUE THREAD

**Issue by hari-rangarajan** [awesomeWM/awesome#546]
Can't an exception be caught and logged instead. Of course, the markup needs to be done right; but it makes no sense to crash and exit the WM.

```
stack traceback:
	[C]: in function 'error'
	...usr/local/share/awesome/lib/wibox/widget/textbox.lua:73: in function 'set_markup'
	/usr/local/share/awesome/lib/awful/tooltip.lua:135: in function 'set_markup'
	/etc/xdg/awesome/rc.lua:671: in function 'xxxx_notifier'
	/etc/xdg/awesome/rc.lua:684: in main chunk
error: ...usr/local/share/awesome/lib/wibox/widget/textbox.lua:73: Error on line 6: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
```

**Comment by nuko8** [comment]
The relevant part of the code is seemingly this:
```lua
local attr, parsed = Pango.parse_markup(text, -1, 0)
 -- In case of error, attr is false and parsed is a GLib.Error instance.
 if not attr then error(parsed.message or tostring(parsed)) end
```
Apart from who is to blame for the crash, the following might be a reasonable question: Is there any guarantee that the invocation of the `lgi` function is protected, or that it always return to the caller without raising an error or exception?

**Comment by nuko8** [comment]
To be more specific, although I'm not sure if non-critical errors like incorrect markup deserve `error()`, I think it would be better to replace the code with
```diff
diff --git a/lib/wibox/widget/textbox.lua b/lib/wibox/widget/textbox.lua
index 90a37fe..8432766 100644
--- a/lib/wibox/widget/textbox.lua
+++ b/lib/wibox/widget/textbox.lua
@@ -68,9 +68,12 @@ function textbox:set_markup(text)
         return
     end
 
-    local attr, parsed = Pango.parse_markup(text, -1, 0)
-    -- In case of error, attr is false and parsed is a GLib.Error instance.
-    if not attr then error(parsed.message or tostring(parsed)) end
+    local status, attr, parsed = pcall(Pango.parse_markup, text, -1, 0)
+    if not status then
+        error(attr)
+    elseif not attr then
+        error(parsed.message or tostring(parsed))
+    end
 
     self._markup = text
     self._layout.text = parsed

```

**Comment by psychon** [comment]
@hari-rangarajan I know that everyone uses the word in a different meaning than I do, but there is no crash here. Also, saying that this crashes and exits the WM is a bit too broad, because during runtime we (try to) just catch and log any error. I bet that here the error occurred during startup and this is about the only case were such errors really are fatal. 

@nuko8 `Pango.parse_markup` AFAIK does not throw lua errors (perhaps unless you call it with e.g. a table instead of a string). Also, why do you do a protected call if you then just want to re-throw the error? Just let the original error propagate (e.g. this produces a better stacktrace).

Also, if we want to we can make `:set_markup` return a "result" value instead of throwing an error. I bet that 99% of code will ignore that value, but right now 99% of code doesn't expect an error here either.
This plan would require going through a lot of code (e.g. naughty currently relies and handles the error, awful.tooltip would need to return the status code from its ':set_markup'  wrapper etc).

I'm not really sure which version makes more sense, but I can see value in not having this throw an error.

**Comment by nuko8** [comment]
@psychon

> `Pango.parse_markup` AFAIK does not throw lua errors

Since the code handles `GLib.Error`,  it wants to handle errors which are originally represented in terms of `GError`, that is, those errors which are caused by a C function invocation, not that conveyed by Lua's error handling mechanism or convention.

If a C function is not written in such a way that it cooperatively works with Lua's error handling mechanism or convention, any crash caused within the internal of the function is fatal for Awesome, or you cannot expect anything from `GError`.  So, the essence of what I meant in my comments was  "Protect Awsome from non Lua-error-handling-compliant C function crashes."

> Also, why do you do a protected call if you then just want to re-throw the error? 

That's why I wrote "although I'm not sure if non-critical errors like incorrect markup deserve error()."  

When I was writing that, I thought some error recovery was appropriate, but I had no time to elaborate on that.  I think it's too fragile if a WM stops woking only for incorrect markup.

> Also, if we want to we can make :set_markup return a "result" value instead of throwing an error. I bet that 99% of code will ignore that value, but right now 99% of code doesn't expect an error here either.
>
>This plan would require going through a lot of code (e.g. naughty currently relies and handles the error, awful.tooltip would need to return the status code from its ':set_markup' wrapper etc).

Your argument is understandable.  I know :-)

While I'm thinking like that way, I wish my favorite window manager could be robust enough against any non-fatal glitches coming from **external** libraries and runtimes.

**Comment by hari-rangarajan** [comment]
@psychon When I filed the issue, it crashed straight out of the WM to  XDM login. I can't seem to make that happen from within Xephyr. I will have to try to create it without Xephyr. I have to note though that this is not the first time crashing to the XDM login has happened to me.

**Comment by blueyed** [comment]
@hari-rangarajan 
> When I filed the issue, it crashed straight out of the WM to XDM login.

Just to be clear: that will happen in case it gets triggered while loading your config, although I got the impression that is should rather fall back to the default config in that case.
I think it would be great to have a test case (in `tests/`) to reproduce/test this.
