### ISSUE TITLE
Useless gaps should not get applied to single client in tiled layout

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#564]
Given a single client in a tiled layout, it should not have useless gaps.

Apart from the "wasted" space, a maximized (floating) client behind it will be partly visible.

**Comment by Elv13** [comment]
"wasted" space is the whole point of that thing ;)

Anyway, I had this conversation with a herbstluftwm user at my previous job and my first uselessgap pull request was the outcome of that discussion. According to him, he wanted the wasted space with a single client "because it look cool". I will never understand that, but whatever. So, there is at least 1 person in the universe who disagree with you. Maybe you should just turn off useless gap when `#tag:clients() == 1` from the signal?

**Comment by blueyed** [comment]
> he wanted the wasted space with a single client "because it look cool"

Would be OK, but I have actually 2 clients, where only one of them is tiled and the other is maximized.

**Comment by psychon** [comment]
Perhaps `if #awful.client.tiled(s) == 1 then`?

**Comment by motdef** [comment]
is it possible to make the new behaviour optional?

**Comment by psychon** [comment]
@motdef 
```lua
local getgap = awful.tag.getgap
function awful.tag.getgap(t, numclients)
    return getgap(t, 42)
end
```

**Comment by motdef** [comment]
That's great thanks, I didn't know you could overload lua functions like that.
