### ISSUE TITLE
Current master branch segfaults Xorg

### ISSUE THREAD

**Issue by mikar** [awesomeWM/awesome#623]
Hey,

the current master branch (720cd879f339760f459b7ae333007a6ae9b5965b) segfaults xorg at startup on my machine.  Out of 20 starts via startx it started only once or twice, the rest of the time Xorg immediately errors out.
I haven't tried any other commits and I'm currently back to a working awesome 3.5.6.
Let me know if you need more information.

stderr:
https://ptpb.pw/lncd/sh

Xorg.0.log:
https://ptpb.pw/24jO/sh

System information:
Thinkpad W541
`Linux w541 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux`

lspci:
https://ptpb.pw/utIl/sh

**Comment by psychon** [comment]
If you want, I can do something more about the crash in awesome. The problem is that after the X11 server dies and libxcb noticies, `xcb_get_setup()` starts returning `NULL` and no code handles that case safely. I already fixed this in libxcb (newer libxcb will continue to return non-`NULL`) and if you want, I can also make libxcb-image handle a `NULL` return from `xcb_get_setup()` correctly.

The crash in the X server is a bug in X.org which you should report there. I cannot do anything about it. If you report it there, please provide the link here.

If you want, you could do a `git bisect` to figure out where awesome started crashing the server, but that info won't help me, but might be interesting to the intel video driver guys (the server crashes in the intel driver).

**Comment by mikar** [comment]
Thanks for the reply. My vacation just ended but i hope i will find the time next week to track down the issue with bisect and submit a bug report to Xorg.
When i do, i will report it here.

**Comment by mikar** [comment]
I have been back on the master branch since Friday and have failed to reproduce this issue. It might have been a configuration issue but I will keep an eye on it.
