### ISSUE TITLE
Chromium keyboard now working afte upgrade awesome to 3.5.7

### ISSUE THREAD

**Issue by hdhog** [awesomeWM/awesome#647]
tAfter upgrade to awesome 3.5.7 keyboard don't work in chromium. all keys of any keyboard layout. Mouse working)
xprop chromium window http://pastebin.calculate-linux.ru/ru/show/11699 

3.5.6 awesome is working

**Comment by psychon** [comment]
From your `xprop` output:
```
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
```
I don't know what chromium is doing, but apparently it does not want any keyboard input. We are just doing as requested.

**Comment by hdhog** [comment]
build awesome 3.5.6 version. keyboard in chromium working
xprop 3.5.6 http://pastebin.calculate-linux.ru/ru/show/11700

**Comment by blueyed** [comment]
@hdhog 
And it's still happening with 3.5.7 for you?

**Comment by psychon** [comment]
Sigh. Ok, here is the long version of my explanation:

It's this commit that is part of 3.5.7, but not 3.5.6: https://github.com/awesomeWM/awesome/commit/9b5ab994b024a42df38724a093509afe8eb89a8e

Before, when nothing had the input focus, we would focus the root window. This has the effect that whatever contains the mouse pointer (yeah, X11 sometimes is surprising) gets key events (try it out in awesome 3.5.6: Disable sloppy focus, give the focus to chromium, type. It will work. Then move the mouse pointer to some other window without focusing it and type. Even though awesome shows that chromium has the input focus, the input appears in that other window.).
Now we have a special, 'invisible' window which we give the input focus to if nothing should be focused. That way the key events go to that window (and are ignored) instead of following the mouse pointer.

So things working in 3.5.6 is only an accident and you can also make this break in 3.5.6 by not using sloppy focus.

Does that make things clear? Does that explanation seam reasonable enough that you believe that it's a bug in Chromium?

(Disclaimer: Someone already mentioned this in IRC and that's way I know this. They also mentioned that it is fixed in newer versions of chromium, I think.)
