### ISSUE TITLE
[question] Mutating hierarchy context

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#648]
In `Radical`,  my menu module, all menu have a global context (usually called "data") that contain the menu settings and item model. I was wondering if there could be a way to pass it to all fit/layout/draw methods of all children widgets of the menu.

The menu can be in a wibox, they don't always "own" it, so monkeypatching the `._` elements isn't generic enough.

I could see other use cases, like replacing the text foreground color is a more flexible way than `wibox.widget.background` method. Actually, having the "beautiful" variable there instead of always using the global one. This way, widgets could have their own theme.

Is it a good idea of should I just keep adding the `_data` field to all menu sub-widgets and be done with it?

**Comment by psychon** [comment]
You can just make a copy of the context and pass it on to child widgets. However, that would render fit/layout caches useless since they are keyed on the context, so for extra performance, you should make a global variable `local context_to_own_context = setmetatable({}, { __mode = "v" })` and use that for caching your own contexts.

The existence of these caches is also the reason why contexts must not be modified: The cache uses the table as its caching key and thus would still return cached data if such a table is modified.

So TL;DR (didn't test this code):
```lua
local contexts_to_own_context = setmetatable({}, { __mode = "v" })
local function make_own_context(context, data)
  local data_cache = contexts_to_own_context[data]
  if not data_cache then
    data_cache = setmetatable({}, { __mode = "v" })
    contexts_to_own_context[data] = data_cache
  end
  local result = data_cache[context]
  if not result then
    result = awful.util.table.join(context) -- makes a copy, I think
    result.data = data
  end
  return result
end
```
Note that this function assumes that `data` is never modified, but copied instead... Seems like this is quite complicated and a bit error-prone.

> I could see other use cases, like replacing the text foreground color is a more flexible way than wibox.widget.background method. Actually, having the "beautiful" variable there instead of always using the global one. This way, widgets could have their own theme.
Uhm. A widget can equally well use `cr:set_source_rgba(something)` in its `before_draw_children` method as it can replace the text foreground color in a context, so I don't understand why this would be better. And having lots of "local" contexts is complicated (see the code above) and would render the fit caches less efficient. I don't think this is the way to go for passing settings to sub-widgets in the long term.

**Comment by psychon** [comment]
Closing. The question "Can I do magic with the context?" was answered with "Not really, this breaks the caches which should make things go fast."
