### ISSUE TITLE
vlc freezes for ~ 10 secs on pause then play or quit

### ISSUE THREAD

**Issue by anibalpacheco** [awesomeWM/awesome#660]
Thats it, this issue is not present when using gnome-session for example.
I'm using Arch Linux and the last awesome and vlc stable packages updates for archlinux.
Any suggestions?

**Comment by psychon** [comment]
Check the VLC logs if they say anything useful?
Try running awesome with the `--no-argb` argument. (This is the only real idea that I have; if this helps, then the bug is somewhere in your video driver.)

**Comment by anibalpacheco** [comment]
Clue: the argument didn't help but launching vlc from the terminal solves the issue.

**Comment by psychon** [comment]
The only difference that I can come up with for this are environment variables. You should be able to grab them via `xargs --null --max-args=1 < /proc/$(pidof vlc)/environ` and can then compare between "starting VLC from a terminal" and "starting VLC somehow else".

Closing this for now since this doesn't seem to be awesome related. Feel free to reopen when you know which environment variable causes this. Even if you figure this out yourself, it would still be nice to leave a comment explaining what the problem was.
