### ISSUE TITLE
Ontop client bug

### ISSUE THREAD

**Issue by flyboy14** [awesomeWM/awesome#667]
When I make an ontop client window fullscreen and then back to non-fullscreen state, it also appears not to be ontop anymore.

**Comment by psychon** [comment]
This is done on purpose: https://github.com/awesomeWM/awesome/blob/cd63cabaddabd61bbbea44bf4dc8a4f575901e92/objects/client.c#L1112-L1119
Alternatively, we would have to define an arbitrary "stronger than" relation between these properties to decide which one is ignored when more than one is active.

**Comment by flyboy14** [comment]
So, if I understood correctly, client couldn't be both fullscreen and ontop at the same time?

**Comment by psychon** [comment]
Yup.

Awesome thinks in layers. At the very top are "ontop" windows. Below that come "fullscreen" windows, then "above" windows. Then "normal", "below" and "desktop" (in this order). That's what the comment that I linked to above means with "a window cannot be in multiple layers at the same time". Put differently, a fullscreen client is automatically something like ontop. (However, we do allow clients with type "desktop" to be "ontop" and ignore their desktop property as long as they are ontop, so perhaps something similar could be done here... but would that make sense? I'm not sure)

And yet I also think that this bug report has a valid point (unexpected behaviour, but "it's a feature, not a bug" :-) ).

**Comment by blueyed** [comment]
@psychon 
> define an arbitrary "stronger than" relation between these properties to decide which one is ignored when more than one is active

I'd vote for that..

**Comment by Elv13** [comment]
@blueyed Then we would be better to just implement z-index and emulate the current layers on top of that. Most WMs have those ontop/normal/above/below/desktop layer concepts. Also, I don't mind the current behavior, it work fine for me.

**Comment by rogorido** [comment]
@flyboy14 this is already closed, and this is only a workaround but it seems to work for me:

```
client.connect_signal("property::fullscreen",
		      function(c)
			 if c.class == "mpv" and c.fullscreen == false then
			    c.ontop = true
			 end
		      end)
```

**Comment by blueyed** [comment]
@rogorido 
For this to work you need to be aware that a client should be ontop after all.

@Elv13 
> Most WMs have those ontop/normal/above/below/desktop layer concepts.

Sure.  But this is about internal implementation, and a simple fix for this might really be to allow having "fullscreen = true" and "ontop = true" set at the same time, but then only use "ontop" for stacking.

> Also, I don't mind the current behavior, it work fine for me.

Yes, it is not too bad, but it is really confusing that a "fullscreen" client gets not only tiled suddenly when setting ontop, but also that its fullscreen state is not restored/kept when unsetting "ontop".

I came across this via https://github.com/blueyed/awesome-cyclefocus/issues/26: I am using "ontop = true" temporarily to ensure a client is visible when cycling, and this requires additional handling of the other related properties (fullscreen, above, and below) - not only for the current client, but also others (because you need to unset ontop for others to make fullscreen clients visible).

For reference, this is where the order is used:
https://github.com/blueyed/awesome/blob/57e05cda1c05eeb793973ff214713bf7d2ad48c5/stack.c#L125-L156
