### ISSUE TITLE
Awesome doesn't set _NET_WORKAREA

### ISSUE THREAD

**Issue by kapsh** [awesomeWM/awesome#677]
There are no _NET_WORKAREA EWMH for Awesome's root window. For comparing, this is part of `xprop -root` dump in Openbox: 
```
_NET_ACTIVE_WINDOW(WINDOW): window id # 0x60000d
_NET_CLIENT_LIST(WINDOW): window id # 0x60000d
_NET_SHOWING_DESKTOP(CARDINAL) = 0
_NET_CURRENT_DESKTOP(CARDINAL) = 0
_NET_DESKTOP_NAMES(UTF8_STRING) = "desktop 1", "desktop 2", "desktop 3", "desktop 4"
_NET_WORKAREA(CARDINAL) = 0, 0, 1920, 1080, 0, 0, 1920, 1080, 0, 0, 1920, 1080, 0, 0, 1920, 1080
_NET_DESKTOP_VIEWPORT(CARDINAL) = 0, 0, 0, 0, 0, 0, 0, 0
```

Yes, there is screen.workarea property in API. But third party applications cannot get this value in easy way. 
For example I want to run rdesktop -g workarea as manpage says: 
```
-g <geometry>
Desktop geometry (WxH). If geometry is the special word "workarea", 
the geometry will be fetched from the extended window manager hints 
property _NET_WORKAREA, from the root window.
```
Expected result is rdesktop window which covers desktop without wibox, but actual is fullscreen window.

**Comment by psychon** [comment]
We stopped setting `_NET_WORKAREA` in commit 9c020877dd1357d7d42a29526d3567586f3db330 because, well, what should this property be set to in a multi-screen configuration?
The problem is that `_NET_WORKAREA` has to describe the workarea of *all*  screens, so you cannot really compare this with `screen[1].workare`.

If you have a good idea on what to do here, feel free to say so. Otherwise I'll keep claiming "the standard is unimplementable".

**Comment by kapsh** [comment]
Sounds reasonable. I need a couple of experiments on multi-screen config before answer.
