### ISSUE TITLE
Client with two tags always gets focus when switching between those tags

### ISSUE THREAD

**Issue by lohfu** [awesomeWM/awesome#733]
When i have a client belonging to two tags, when i switch between the tags focus will always be on the shared tag even if it was not focused.

i tried solving it with the following code (both with and without the timer) to no avail.

```
awful.tag.viewonly(awful.tag.gettags(i)[j]) awful.screen.focus(i) 
local focus_timer = timer({ timeout = 0.2 })
focus_timer:connect_signal("timeout", function()
    local c = awful.mouse.client_under_pointer()
    if not (c == nil) then
        client.focus = c
        c:raise()
    end
    focus_timer:stop()
end)
```

also, i noticed that moving the mouse does not change focus until it leaves the initial client

**Comment by psychon** [comment]
Did you `focus_timer:start()` your timer? (= Does your code actually do anything?)

This issue is likely the same as https://awesome.naquadah.org/bugs/index.php?do=details&task_id=574.

**Comment by lohfu** [comment]
my god i had indeed simply forgot to call `focus_timer:start()`. sorry.

why do i need the timer at all? setting the timeout to 0.001 makes it barely noticable though. would you recommend any other fix?

and yes, it seems it is a duplicate of that issue... was not aware there were 2 issue trackers.

**Comment by psychon** [comment]
That other issue tracker is the old, read-only issue tracker from before we moved to GitHub.

The issue here is that the focus history is global. When you switch to a tag and no client has the input focus, then `awful.autofocus` picks the newest entry from the focus history that is currently visible. Thus, if the client that is on both tags was focused on the "old" tag (even when you later moved the focus elsewhere), it will also be picked on the "new" tag.

So the issue here is that you think of the focus history "per tag" while it really is global.

**Comment by rogorido** [comment]
> So the issue here is that you think of the focus history "per tag" while it really is global.

And is there any workaround for this? This is maybe one of the few things which are very very annoyable in awesome....

**Comment by Elv13** [comment]
Nothing technically prevent you from implementing per-tag and per-screen histories. It just require connecting a bunch of signals (mostly "tagged", "untagged", "manage" "focus" and "unfocus") then use that as the source for tag switching focus and mod4+tab

**Comment by rogorido** [comment]
Thanks for your answer. I'm using awesome only since 2-3 days... could you maybe only point out in which source files I should look in order to have an idea?

**Comment by Elv13** [comment]
(warning, those API doc files are for Awesome git HEAD (master branch) and not really compatible with 3.5, but as it isn't documented at all for 3.5, I have nothing else to show you)

See:
http://awesomewm.github.io/apidoc/classes/client.html
http://awesomewm.github.io/apidoc/classes/tag.html
https://github.com/awesomeWM/awesome/blob/master/lib/awful/client/focus.lua

**Comment by rogorido** [comment]
Thanks... I didn't know this new apidoc (btw: are the socalled useless_gaps already implemented in master? no need to use lain anymore?).

Just a very small question: i only use mpv (the video player) as sticky. That is: i would only need a kind of rule which says: "afted select tag, if the client is mpv and it is sticky, then skip it and jump to the previous one". Would it be maybe possible to rewrite the function focus.filter in focus.lua? Or need I something more complex?

**Comment by Elv13** [comment]
You can use `awful.client.iterate` to implement custom filters. You can also "monkeypatch" function if you like to, but keep in mind that if you use modules like lain, they may not expect this and have issues.

>  are the socalled useless_gaps already implemented

Yes, they are

> no need to use lain anymore?

If you use it for the useless gaps only, then no.

**Comment by rogorido** [comment]
thanks. I'll take a look at it.

**Comment by psychon** [comment]
@rogorido Some bad hack that might help you a bit would be an `awful.rules`-rules that matches mpv and uses the following callback:
```
function(c)
    local t = timer{ timeout = 1 }
    t:connect_signal("timeout", function()
        if not c.valid then t:stop() return end
        awful.client.focus.history.delete(c)
    end)
    t:start()
end
```
It is a really, really bad hack that removes a client from the focus history once per second. Yes, I should feel bad for proposing this. (No, I did not test if this actually works)

**Comment by rogorido** [comment]
@psychon: thanks. But it does not seem to work... 

This is the well known "problem" of the sticky windows, as mentioned above. But, I'm wondering whether there are plans to implement history per tag (or something else). Or do you not use sticky windows? If yes, how do you tackle with this "problem"?

**Comment by psychon** [comment]
Hm, ok.. sorry then. :-(

**Comment by Elv13** [comment]
In my case, I use my own history implementation. I think @blueyed also does so. So for the "top 3" contributors, at least 2 doesn't use the default history implementation. That says a lot about its "quality".

I would agree with patched adding global, per screen and per tag history (maybe using some shared implementation). I don't even mind much if it breaks the API. The current one is indeed quite broken. However I have immediate plans to do this. I got a very long list of pull requests in progress. And I wont add anything else to my TODO list for 3.6.0.

It also has to be able to cycle the focus without changing the history for all the alt+tab implementations (this is why both me and blueyed use our own)

**Comment by rogorido** [comment]
@Elv13 thanks for your answer (I suppose you mean "However I have NOT immediate plans to do this"...).

Could you maybe point out where you modifications are? I can not find them in your repository...

**Comment by Elv13** [comment]
They are in my https://github.com/Elv13/radical module
Warning, I hope you are into pastafarism, because that module is a giant spaghetti monster. It also doesn't solve your issue (I don't use sticky clients)
https://github.com/Elv13/radical/blob/awesome3.6/impl/alttab/init.lua

The other implementation is here https://github.com/blueyed/awesome-cyclefocus and is probably a better start.

**Comment by rogorido** [comment]
@Elv13 thanks! I will try to understand it...

**Comment by rogorido** [comment]
I'm still thinking about this issue, because it is the only thing I miss to make awesome perfect to my needs. 

If I understand the code rightly, the autofocus code is quite simple... Then my question is: since I have only this problem with mpv clients, could it be possible to patch the function check_focus_tag in autofocus.lua (3.5.9) and make it check whether the client is mpv and is sticky? (this is of course only a hack for my problem, not a general solution!)

If the answer is yes, have you maybe some tips which potential problems I should in any case consider?

**Comment by psychon** [comment]
Of course you can do such a check. Something like the following might work (assuming there is only ever a single sticky client; only the second line is new):
```
local c = aclient.focus.history.get(s, 0)
if c and c.sticky then c = aclient.focus.history.get(s, 1)
if c then client.focus = c end
```
The new line ignores the first client that it got from the focus history if it is sticky and instead gets the previous client from the focus history. No idea about problems (except for the obvious one: If you have more than one sticky client, this won't do the right thing)

**Comment by rogorido** [comment]
@psychon thnaks a lot. I will it a try in the next days. (I only have a sticky client: the mpv window).

Maybe another "solution" I'm thinking about (a solution for my problem, not in general for this issue): when I switch to another tag (A->B),  is there a way to get the selected client in A and put the reference in a table with key=tag and value=client? Then maybe I could implement autofocus to check this table and focus the client (if it exists).

This issue is because (if I understand your explanations rightly) awesome does not have a history per tag. BUT: for solving my "problem" I'm not interested in a history per tag, but just in finding out which client was focused the last time I was using tag A.

The question is therefore: which ist the best method to get the last selected client in tag A when I switch out of it?

**Comment by rogorido** [comment]
@psychon thanks for your code. I managed to solve the issue (for my needs...). I have the following now in autofocus.lua:
```
local function check_focus(obj)
    -- When no visible client has the focus...
    if not client.focus or not client.focus:isvisible() then
        local c = aclient.focus.history.get(obj.screen, 0)
	if c and c.sticky then
	       c = aclient.focus.history.get(obj.screen, 1)
        end
        if c then client.focus = c end
    end
end
```

**Comment by osleg** [comment]
You can use focusable=false (if it's still writable), in conjuction with MPV sticky it might bring you the exact behaviour you looking for.
Check #237 and #241 for the idea :)
