### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by nenadalm** [awesomeWM/awesome#76]
Hi. I have rendering issues with some applications (e.g. gvim).

When I open long document in gvim and scroll using keys (j, k - down, bottom) everything works fine.
When I use vertical scrollbar with mouse, everything works fine too.
But when I use mouse wheel, only small parts re-render during scrolling, so the text is terribly broken.

```shell
$ cat /etc/issue
Fedora release 20 (Heisenbug)
Kernel \r on an \m (\l)

$ awesome -v
awesome v3.5.5 (Kansas City Shuffle)
 • Build: Apr 14 2014 18:44:32 for x86_64 by gcc version 4.8.2 (mockbuild@)
 • Compiled against Lua 5.2.2 (running with Lua 5.2)
 • D-Bus support: ✔
```

**Comment by psychon** [comment]
I cannot really tell you how to do so, but can you start awesome with the `--no-argb` option?

My suggestion would be that this is the same bug as https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1089 and the bug is actually in your video driver.

Why I think so: Awesome doesn't influence GVim's content. It just tells the X server the position of the GVim window. Because of this, a bug like this pretty much must be in your video driver.

**Comment by nenadalm** [comment]
Thank you very much! It seems the issue is solved.
