### ISSUE TITLE
Default config: non-working (commented) code with tags in rules

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#799]
https://github.com/awesomeWM/awesome/blob/e24cb901cbe95718901c5b0b73b15ac0448f989d/awesomerc.lua#L454-L456:

    -- Set Firefox to always map on tags number 2 of screen 1.
    -- { rule = { class = "Firefox" },
    --   properties = { tag = tags[1][2] } },

Accessing tags here (when setting up the rules) won't work.
For my rules, I've wrapped them in `gears.screen.connect_for_each_screen(function(s) ... end)`.

The default config could also be changed to use `screen.primary` then regardless?!

**Comment by psychon** [comment]
Uhm... how could something like this even work with multiple screens? I have no good idea right now.

**Comment by Elv13** [comment]
Yeah, moving the scan screen down really broken this use case for me. Tyrannical have a declarative tag syntax like the new widget system one.

```lua
...
    {
        name = "Term",
        init        = true                                           ,
        exclusive   = true                                           ,
        icon        = utils.tools.invertedIconPath("term.png")       ,
        screen      = {config.scr.pri, config.scr.sec} ,
        layout      = awful.layout.suit.tile                         ,
        focus_new   = true                                           ,
        selected    = true,
        nmaster     = 2,
        mwfact      = 0.6,
        index       = 1,
        max_clients = five_layout,
        class       = {
            "xterm" , "urxvt" , "aterm","URxvt","XTerm"
        },
    } ,
...
```

You can use `screen=` to tell where you want the tag to be created (either a screen index or an array of indices). In the case the number of screen didn't match, it would simply fallback to the lowest valid index or use `[1]`. This is how Tyrannical handled moving tags to the right screen when you connected a new one (and Awesome restarted).

The problem with this construct is that it doesn't really work with screen objects for obvious reasons. I can probably invent a fix for this, after all, it broke because Awesome got better, not the other way around. So I will find a solution myself.

But another thing is a little more problematic. Declaration like `screen = screen.count() >= 3 and 2 or 1` don't really work anymore as they are interpreted when the config is parsed and no screens are present. Again, it is a new "problem" introduced because of a feature I rather like. However this one doesn't really have a solution beside wrapping that in a function (fugly, but functional...).

I guess it will become unavoidable to come up with a "[screen future](https://en.wikipedia.org/wiki/Futures_and_promises)" kind of concept to address these use case (both the one @blueyed mentioned) and mine. Otherwise making rules will get confusing and have `function()` boilerplate everywhere. That wont be easy to solve as the screens may or may not ever arrive.

**Comment by psychon** [comment]
We could deprecate Xinerama and "no extension" support (or: just define screens before loading the config in these cases). Then we could use something like "LVDS1" to identify the screens before they are present. `screen["LVDS1"]` already works (if using RandR and such a CRTC (or was it output?) is present).
However, this is not portable between configs...

Perhaps we should revert the "move `screen_scan()` down"-commit for now (or hide it behind some `#ifdef`) until we have some ideas on what to do exactly. However, I'm worried that this might mean "just ignore the problems until someone else has a good idea".

We could also start with some middle-ground: Have already-present screens defined before the config is loaded and only use the signals for screen additions/removals. I wouldn't want this behavior in a release (no one will test their code for screen additions/removals), but at least we don't break everything immediately.

**Comment by blueyed** [comment]
> We could also start with some middle-ground: Have already-present screens defined before the config is loaded and only use the signals for screen additions/removals.

Sounds fine to me.

**Comment by Elv13** [comment]
> We could also start with some middle-ground: Have already-present screens defined before the config is loaded and only use the signals for screen additions/removals.

+1

**Comment by Elv13** [comment]
> We could deprecate Xinerama

Please don't, unless you plan to add a "manual mode" where screens can be defined from lua in case Xinerama is present. People who use Xinerama probably don't connect and disconnect screens anyway. My 3.4 fork had a manual mode because of a driver bug where `radeon` would expose 1 giant screen instead of 3 even if xrandr or xinerama were enabled and `xorg.conf` told to expose 3 screens. However I just hardcoded it in C, but I guess exposing it to lua would not be that hard. Multi-GPU setups only work in SLI (TwinView extension, only supported on high end GPUs), Eyefinity (only for radeon and very buggy) or Xinerama mode since full Mosaic was dropped from the NVIDIA driver.

**Comment by psychon** [comment]
Some thoughts:
- We can refer to screens by name (LVDS1) and number (for Xinerama). This helps a bit with Elv13's `screen      = {config.scr.pri, config.scr.sec} ,`.
  - This requires a change in `awful.rules` and possible many more places.
- We can refer to tags by name. These are not required to be unique, but in practice I think they always are and people using non-unique tag names will have to find their own solutions.
  - This requires a change in `awful.rules`
- `screen = screen.count() >= 3 and 2 or 1` @Elv13 Why do you have such constructs? My guess would be that this can be fixed by using screen names (`LVDS1`), but I'm not totally sure.

**Comment by Elv13** [comment]
> Why do you have such constructs?

Because I gave names to the numbers ;) In reality, it looks like `config.screen.notif or config.screen.pri`

**Comment by funeralismatic** [comment]
```
error while running fubction!
stack traceback
    /home/funeralismatic/.config/awesome/rc.lua:789: in main chunk
error: /home/funeralismatic/.config/awesome/rc.lua:789: attempt to index field "?" (a nil value)
```

```
787	{ rule_any = { class = { "Neovim", "Spacefm" }},
788		properties = {
789			tag = tags[1][1]
790		}
791	},
```

```lua
awful.layout.layouts = {
	awful.layout.suit.floating,
	awful.layout.suit.tile.left,
	awful.layout.suit.tile,
	awful.layout.suit.fair,
	awful.layout.suit.max,
}

tags = {}
awful.screen.connect_for_each_screen(function(s)
	tags[s] = awful.tag(
		{ "dev", "web", "med", "trm", "etc" },
		s,
		{
			awful.layout.layouts[4],
			awful.layout.layouts[2],
			awful.layout.layouts[5],
			awful.layout.layouts[4],
			awful.layout.layouts[1]
		}
	)
end)
```

All `tag` property in rules give this error.

```
awesome v3.5.2-1396-g6e8337e-dirty (The Fox)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
```
