### ISSUE TITLE
useless_gaps applied to a single client

### ISSUE THREAD

**Issue by zainin** [awesomeWM/awesome#859]
Looks like the changes made in `awful/layout/init.lua` (#790) removed the improvements made in #564. Without the check that has existed in `awful.tag.getgap`, useless_gap is now applied regardless of the number of clients.

I've fixed it locally like this, but there's probably a more elegant solution:
```
if #client.tiled(screen) == 1 then  
    useless_gap = 0  
else
    useless_gap = t and t.gap or 0
end
```

**Comment by actionless** [comment]
i was proposing that already:
https://github.com/awesomeWM/awesome/issues/826

**Comment by Elv13** [comment]
I will fix it properly later today. I removed it because while the idea make sense, the implementation was rather hacky. Having comments like "if your not happy with this hack, then monkeypatch this function to remove it" isn't really the way I want the API to be. I will add a new "gap_ignore_first" (boolean) or something property (need a better name).

**Comment by actionless** [comment]
and what do you think about also checking `awful.tag.getmfpol(t) == "expand"` ?

**Comment by Elv13** [comment]
This has been fixed a while ago
