### ISSUE TITLE
rendering problem when moving horizontally.

### ISSUE THREAD

**Issue by mahdiG** [awesomeWM/awesome#876]
Hi. I'm using v3.5.9 on Kali-rolling. There's a rendering problem when moving objects to left and right. It's like there's a line and pixels below and above it are not in the same column.

**Comment by psychon** [comment]
Objects? What kind of objects? Do you have a screenshot? And perhaps some step-by-step instructions on what exactly you do?

**Comment by mahdiG** [comment]
For example this is what happens when I resize the window to left. It also happens in 2D games (DDNet) when I move to left and right. This doesn't happen in gnome-shell on the same OS.
![vlcsnap-2016-05-06-20h01m56s331](https://cloud.githubusercontent.com/assets/4989445/15077918/f3a6699a-13c5-11e6-85b9-8d79f0ea83cd.png)
![vlcsnap-2016-05-06-20h02m05s930](https://cloud.githubusercontent.com/assets/4989445/15077919/f3af6996-13c5-11e6-9206-b377b1e6a9a1.png)
![vlcsnap-2016-05-06-20h02m11s370](https://cloud.githubusercontent.com/assets/4989445/15077920/f3ba37a4-13c5-11e6-9209-f0da202044cc.png)

**Comment by psychon** [comment]
You mean the broken alsamixer? Well, a window manager only positions windows, it is not involved in drawing them. This bug likely is in your video driver. Which one are you using (intel, nvidia binary blob, nouveau, amd-something, fglrx, ...)?

Are you using a compositing manager (xcompmgr, compton, ...)? If so, can you try without? If not, can you perhaps try with one? :-)
Can you try starting awesome with `--no-argb` and see if this makes a difference?

**Comment by mahdiG** [comment]
I'm using the open-source amd/ati driver. I used compton and it made things worse. I tried with --no-argb and it fixed the video tearing but now I don't know how to run awesome --no-argb instead of awesome by default.

**Comment by psychon** [comment]
How do you start awesome? Perhaps you have to edit `/usr/share/xsessions/awesome.desktop` and add the argument to the `Exec`-line.

Anything fixed by `--no-argb` is a bug in the video driver. You can report this issue upstream at bugs.freedesktop.org, but I don't have any nice, easy way to have them reproduce the problem, so anyone wanting to reproduce this would need to install awesome. All that I can say to help them is: "awesome is a reparenting WM which uses depth=32 for its frame windows, even for 'normal' windows with depth=24. This causes the reported rendering issue. If run with `--no-argb`, awesome uses the server's default visual instead and the problem goes away."
If you do report this issue upstream, please provide the link to the bug report. Thanks.

**Comment by mahdiG** [comment]
I changed the exec line in /usr/share/xsessions/awesome.desktop to `awesome --no-argb` and after choosing awesome in lightdm I got this error:
![xsession](https://cloud.githubusercontent.com/assets/4989445/15144679/43d5631e-16c6-11e6-879e-15cde4002c07.jpg)

**Comment by psychon** [comment]
Sigh. Aren't desktop files create? I guess that means you need to create a wrapper script `/usr/bin/awesome-no-argb` that contains
```
#!/bin/sh
exec awesome --no-argb
```
(remember to make this executable, `chmod +x /usr/bin/awesome-no-argb`). Afterwards, you can do `Exec=awesome-no-argb`.

**Comment by Jajauma** [comment]
I guess passing some arguments to the Exec'ed binary in a .desktop file is expected to work actually. I maintain the similar .desktop file downstream https://github.com/JajaumaPackages/awesome/blob/master/awesome-noargb.desktop for the same reason (e.g. to mitigate some visual glitches on buggy vboxvideo) and it works just as one expecting it to do. No extra quoting (escaping) nor shell wrapping seem to be needed.
