### ISSUE TITLE
preserve tag on reload if screen vanished

### ISSUE THREAD

**Issue by Konfekt** [awesomeWM/awesome#924]
There are initially two screens, then one is disconnected, and then AwesomeWM restarted (Meta+Ctrl+R). 

Expected: An application showing on `[6][2]` (Tag 6, Screen 2) now shows on `[6][1]` (Tag 6, Screen 1). In particular, on the *same* tag.
Currently: An application showing on `[6][2]` (Tag 6, Screen 2) now shows on `[1][1]` (Tag 1, Screen 1).

This is with AwesomeWM 3.5.6. Has it changed  in the meanwhile?

**Comment by Elv13** [comment]
> This is with AwesomeWM 3.5.6. Has it changed in the meanwhile?

Yes, this will be one of the major features of Awesome 3.6. Please test our git master branch and report any issues. The git-master branch also implement some hooks to move tags to another screen instead of destroying them. It isn't implemented by default but can be activated from rc.lua. The documentation has yet to be written (this is new from a couple of weeks ago).

I am closing this as it wont be fixed in the 3.5 branch.
