### ISSUE TITLE
Cannot un-minimize window in Xfce4

### ISSUE THREAD

**Issue by yuggmatt** [awesomeWM/awesome#927]
When using awesome as the window manager for Xfce, the windows cannot be un-minimized when clicking on the corresponding entry in Xfce's task bar. Instead, they are getting the urgent status.
This seems to be the same problem as reported on the mailing list here: http://www.mail-archive.com/awesome%40naquadah.org/msg08202.html (Gnome+Awesome)

The workaround provided (adding c.minimized = false in ewmh.activate() ) is working, but it requires modifying core libs by hand.

See: http://www.mail-archive.com/awesome%40naquadah.org/msg08207.html for more details on the problem.

OS: debian sid
Awesome: 3.5.9-1
Xfce4: 4.12.3

**Comment by Elv13** [comment]
Related:
https://www.mail-archive.com/awesome@naquadah.org/msg08202.html

**Comment by blueyed** [comment]
Can you check if it works with awesome from Git master?

**Comment by yuggmatt** [comment]
The problem is still there with awesome from git master.

**Comment by psychon** [comment]
The second link above really has all the details. Gnome wants to focus a window and so sends us a `_NET_ACTIVE_WINDOW` ClientMessage. `ewmh.c` handles this by emitting a `request::active` on the client. `awful.ewmh.activate` catches this and because `c:isvisible()` is false (the client is minimized!), it doesn't do anything besides making the client urgent.

Should that function perhaps do `if context == "ewmh" then c.minimized = false end`? I'm not sure, what do others say?

**Comment by psychon** [comment]
Perhaps it also makes sense to do the more general `if hints.raise then c.minimized = false end`

**Comment by actionless** [comment]
> The issue at hand was introduced in b824d00 to fix #455.

just from comments it seems what it's chained to more changes:

https://github.com/awesomeWM/awesome/issues/455#issuecomment-143159565

**Comment by Elv13** [comment]
> @Elv13 Since the commit message doesn't explain much, any reason why we shouldn't revert f681ace ?

Looking at my logs, this was for FS#1098 and was reported on IRC / tested by the user. Also, are you sure f681ace is such a bad thing? I mean why focus unfocusable clients, the whole point of `c.focusable` is to avoid focusing the client. Reverting f681ace would totally regress that feature, no?
