### ISSUE TITLE
Add menubar customization options

### ISSUE THREAD

**Issue by silverhammermba** [awesomeWM/awesome#941]
In `lib/menubar/init.lua`, labels are hard-coded to use `theme.bg_normal` if they are not focused. Elsewhere in awesome, fg/bg colors are usually selected from several alternatives, falling back to the `_normal` variants as a last resort. For example `lib/awful/menu.lua` tries `menu_bg_normal` first.

I just ran into a situation where I wanted to set the menubar differently from the taskbar and currently that seems to be impossible. It would be simple (and consistent) to add alternatives e.g. `menu_bg_normal`.

**Comment by blueyed** [comment]
Seems sensible.
Do you like to create a PR for it?

**Comment by silverhammermba** [comment]
Sure. I'll get around to it at some point. I'm on vacation at the moment.

**Comment by doronbehar** [comment]
I think I have the same problem in [`mytheme.lua`](https://github.com/doronbehar/awesome-files/blob/master/mytheme.lua#L45) as well, this is how my menu looks like:

![not so awesome menu](http://i.imgur.com/MUCKm66.png)

As you can see, I don't have a different `bg_color` for the focused menu items versus the unfocused `bg_color` and thus only applies to the root menu. In addition, the root menu's items' font is different than the global `theme.font`.

This issue has annoyed me ever since I created my own theme out of the default one and I can't figure out what am I doing wrong.

Any help appreciated, Thanks.

**Comment by blueyed** [comment]
@doronbehar 
Have you tried awesome master, with https://github.com/awesomeWM/awesome/issues/949 in particular?

**Comment by doronbehar** [comment]
The function that was changed in #949 is defend on my machine as follows:
```none
$ grep 'local function label(o)' -A9 /usr/share/awesome/lib/menubar/init.lua
local function label(o)
    if o.focused then
        return colortext(o.name, (theme.menu_fg_focus or theme.fg_focus)),
               (theme.menu_bg_focus or theme.bg_focus),
               nil,
               o.icon
    else
        return o.name, (theme.menu_bg_normal or theme.bg_normal), nil, o.icon
    end
end
```

And my `awesome --version`'s output is as follows:
```
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

I'm using Arch Linux.

**Comment by blueyed** [comment]
On Arch Linux, you could try the `awesome-git` package.

**Comment by doronbehar** [comment]
I tried `awesome-git`, I haven't changed anything in `mytheme.lua` and still no difference. Even with the default theme, the menu still looks like in the picture I posted. Is there any way we can explain this?

**Comment by blueyed** [comment]
@doronbehar 
Looks like a different issue to me then.
Please create a new one.
