### ISSUE TITLE
Client move/resize cursor changes?

### ISSUE THREAD

**Issue by funeralismatic** [awesomeWM/awesome#956]
Previously, when you drag or resize the window, it was a human-readable cursor (arrows), instead now simply crosshair. What are the reasons for this change?

(It's just a question.)

**Comment by funeralismatic** [comment]
@Elv13, can you give me a link to the commit in which you made the changes that I described above? I don't know what to look for.

**Comment by psychon** [comment]
Commit f8f57fb6b71a69a6a5f9efb8218912984e597e8c adds a mouse grabber with cursor "cross" and cdcfb913f1e631453e5101c04ae8a590a4334e55 removes the old mouse grabber which used "fleur" as its cursor. At least I think that these are the relevant commits. It's just a theory.

**Comment by funeralismatic** [comment]
@psychon, thank you.

**Comment by Elv13** [comment]
> @Elv13, can you give me a link to the commit in which you made the changes that I described above? I don't know what to look for.

The whole resize and move code was rewritten for the following reasons:

 * The old code had many copy pasted "mousegrabbers" logic. Some versions had extra features, like snapping, while other did not. It was not possible to use those extra features in other "mousegrabbers" without monkeypatching Awful.
 * Some features, like TWM or BlackBox like resizing could not be implemented due to the lack of "extensibility" of the various "mousegrabbers"
 * Implementing new layouts required to implement a new "mousegrabber", making them hard to create.
 * A new API called the request API was introduced last year with the goal of turning all "internal Awesome decision" into a observer->delegate like pattern. This is useful for focus stealing policies and unwanted changes. The mouse resize/move was the last major component to be ported to that API
 * Finally, I am working on a new layout system (not for the next release) able to implement smarter layouts, like i3 ones. When doing this, I found many "nodes" in Awesome client placement pipeline that were unsuitable for alternative layout systems.

As for the regression, a patch is coming.

**Comment by Elv13** [comment]
@funeralismatic Can you test the patch? I am working on something else right now and I don't have much time.

The commit also add some beautiful options to replace the cursor.

**Comment by funeralismatic** [comment]
@Elv13, thanks for the explanation.

>Can you test the patch?

Out of the box nothing changed.

`beautiful_cursor_mouse_*` doesn't work too.

I do something wrong?
