### ISSUE TITLE
Why don't timers execute the function right after they are started?

### ISSUE THREAD

**Issue by julianuu** [awesomeWM/awesome#968]
It looks to me like that timers first wait before they exececute the function the first time. Why is it like that? For my purposes it would make more sense if the function would be executed at the moment the timer is started.

I could execute the function manually in rc.lua the first time, but when the execution of that function takes some time then the whole startup of awesome would be greatly delayed. I can't find a nice workaround.

But more importantly, I don't see a lot of cases where the current behaviour of timers would be benefitial. Well maybe there are situations where functions really need the fact that the system has been running for a specified time before they are being called, but I don't know any examples for that.

**Comment by psychon** [comment]
A quick random-thought answer: Because timers-that-run-immediately can easily be simulated with the current system (just emit the `timeout` signal immediately on the timer object) while the other way around is hard to do (the callback would have to ignore its first invocation except for setting a flag so that the following invocation does the actual work).

I would suggest to write a simple wrapper function for creating timers that fire immediately:
```lua
function create_and_fire_timer(timeout, callback)
    local t = timer({ timeout = timeout })
    t:connect_signal("timeout", callback)
    t:start()
    t:emit_signal("timeout")
end
```
Or the same for git/master:
```lua
function create_and_fire_timer(timeout, callback)
    gears.timer.start_new(timeout, callback):emit_signal("timeout")
end
```

> I could execute the function manually in rc.lua the first time, but when the execution of that function takes some time then the whole startup of awesome would be greatly delayed. I can't find a nice workaround.

Why do you feel that your slow callback function delays startup of awesome, but does not delay the "actual working" of awesome? I think that in both cases you should have a noticable delay, no?

If you really just want to get "out of awesome startup", how about using a 0 seconds timer for starting your timer?
```lua
function create_and_fire_timer(timeout, callback)
    local first_t = timer({ timeout = 0 })
    first_t:connect_signal("timeout", function()
        first_t:stop()
        local t = timer({ timeout = timeout })
        t:connect_signal("timeout", callback)
        t:start()
        t:emit_signal("timeout")
    end)
    first_t:start()
end
```

**Comment by julianuu** [comment]
Ah thanks I see! So do I understand right that `t:emit_signal("timeout")` just makes that `callback` is called?

About the delay, I noticed that the window manager can only be used after it is done processing rc.lua, so if a function in rc.lua needs some time then I can't do anything before it's done, whereas functions called by a timer appear to run in the background.

**Comment by psychon** [comment]
> So do I understand right that `t:emit_signal("timeout")` just makes that callback is called?

Yup.

> whereas functions called by a timer appear to run in the background.

They do not. Perhaps you were just lucky enough to never notice this? Slow startup might be much more noticable than slow reactions at some random time.

I'll close this under the assumption that all problems were dealt with (or at least were worked around).
