### ISSUE TITLE
Rules with tag and screen always use screen 1's tags

### ISSUE THREAD

**Issue by dcbishop** [awesomeWM/awesome#988]
Using the following rule:

           { rule = { class = "Firefox" },
             properties = { screen = 2, tag = "3" } },

Results in tag 3 on screen 1 as being marked as having the window on it. Nothing appears under tag 3 on screen2 Switching tag3 on screen 1 makes the window appear on screen 2. Switching tags on screen 2 with screen1's tag3 selected merges screen 2's selected tag with the Firefox window.

**Comment by psychon** [comment]
What's your awesome version? I'm assuming you are using a git/master version since otherwise the symptoms would be a lot different.
Could you test if the following patch helps?
```diff
diff --git a/lib/awful/rules.lua b/lib/awful/rules.lua
index cc672c6..f899685 100644
--- a/lib/awful/rules.lua
+++ b/lib/awful/rules.lua
@@ -268,7 +268,7 @@ local force_ignore = {
 function rules.high_priority_properties.tag(c, value)
     if value then
         if type(value) == "string" then
-            value = atag.find_by_name(nil, value)
+            value = atag.find_by_name(c.screen, value)
         end
 
         c:tags{ value }
```
@Elv13 Am I missing anything or should the above be committed to master? If I understand `awful.rules` correctly, it applies the `screen` property before `tag`, so this should work. And of course having `nil` here explains why it does not work for @dcbishop (the code will use the first tag with name "3", which will be the tag for screen 1; Thus the client ends up with a tag that belongs to a different screen).

**Comment by dcbishop** [comment]
Yep I'm running git.

That patch fixed it. Thanks.

**Comment by blueyed** [comment]
Thanks!

This looks like an issue that I am seeing myself also from time to time.

@psychon 
Do you plan to or have already written a test for it?  (I would volunteer to do this otherwise)
We have some tests with multiple screens already, don't we?

**Comment by psychon** [comment]
@blueyed Nice timing, I just submitted #992 with just the above patch and no test. Currently we don't really have any multi-screen tests (well, one, but that's nothing generic) and I don't want to invent the necessary test infrastructure currently. Feel free to investigate that if you want.
